iPIC3DxPEACE: plot5_paper_in-situ-data Namespace Reference
plot5_paper_in-situ-data Namespace Reference
Functions
def scalr (a)
Variables
string data_path = sys.argv[1]+'dataP/'
DEFINE PARAMETERS ########################.
int cycle = 5999
int nrun = 2
string traj_path = './trajectory_files/'+sys.argv[2]+'-flyby-1st_MSO-trajectory1.txt'
string good_path = sys.argv[1]+'texts/output_dataP-new_'+sys.argv[2]+'.txt'
output_file = open(sys.argv[1]+'texts/output_good-pcls_%i_%i_'%(nrun,cycle)+sys.argv[2]+'.txt','w')
float dr = 0.03
float conv_T = 21.5/(0.031**2)
END DEFINITION ###########################.
from_VTK = fb.from_VTK(data_path)
silent
x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
xc = from_VTK.meta['xc']
yc = from_VTK.meta['yc']
zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
tt = (tt-tt[i_CA])/60.
xx = xx[imin:imax]
yy = yy[imin:imax]
zz = zz[imin:imax]
unpack
dd = np.sqrt(xx**2+yy**2+zz**2)
i_CA = np.where(dd==min(dd))
int enter = 0
imin = ii
imax = ii
good_data_files = np.loadtxt(good_path,unpack=True,dtype='int')
d = h5.File(data_path+'restart%i_%i.hdf'%(good_id,nrun),'r')
x_pcls = d['particles/species_0/x/cycle_'+str(cycle)][:]
y_pcls = d['particles/species_0/y/cycle_'+str(cycle)][:]
z_pcls = d['particles/species_0/z/cycle_'+str(cycle)][:]
u_pcls = d['particles/species_0/u/cycle_'+str(cycle)][:]
v_pcls = d['particles/species_0/v/cycle_'+str(cycle)][:]
w_pcls = d['particles/species_0/w/cycle_'+str(cycle)][:]
float e_pcls = conv_T*(u_pcls**2+v_pcls**2+w_pcls**2)
list versor = [xx[ii+1]-xx[ii],yy[ii+1]-yy[ii],zz[ii+1]-zz[ii]]
distance = np.sqrt((1.-versor[0]**2)*(xx[ii]-x_pcls)**2 + (1.-versor[1]**2)*(yy[ii]-y_pcls)**2 + (1.-versor[2]**2)*(zz[ii]-z_pcls)**2)
idx_sphere = np.where(distance<dr)
Function Documentation
scalr()
def plot5_paper_in-situ-data.scalr (a)
Definition at line 80 of file plot5_paper_in-situ-data.py.
def scalr(a):
    return np.sqrt(a[0]**2+a[1]**2+a[2]**2)
# open particle files
Variable Documentation
conv_T
float plot5_paper_in-situ-data.conv_T = 21.5/(0.031**2)
END DEFINITION ###########################.
Definition at line 37 of file plot5_paper_in-situ-data.py.
cycle
int plot5_paper_in-situ-data.cycle = 5999
Definition at line 16 of file plot5_paper_in-situ-data.py.
d
plot5_paper_in-situ-data.d = h5.File(data_path+'restart%i_%i.hdf'%(good_id,nrun),'r')
Definition at line 87 of file plot5_paper_in-situ-data.py.
Referenced by CG(), and PSK::coutOutputAdaptor.write().
data_path
string plot5_paper_in-situ-data.data_path = sys.argv[1]+'dataP/'
DEFINE PARAMETERS ########################.
path to simu pcls data
Definition at line 15 of file plot5_paper_in-situ-data.py.
dd
plot5_paper_in-situ-data.dd = np.sqrt(xx**2+yy**2+zz**2)
Definition at line 54 of file plot5_paper_in-situ-data.py.
distance
plot5_paper_in-situ-data.distance = np.sqrt((1.-versor[0]**2)*(xx[ii]-x_pcls)**2 + (1.-versor[1]**2)*(yy[ii]-y_pcls)**2 + (1.-versor[2]**2)*(zz[ii]-z_pcls)**2)
Definition at line 119 of file plot5_paper_in-situ-data.py.
Referenced by EMfields3D.initBEAM(), EMfields3D.initDipole(), and EMfields3D.initDipole2D().
dr
float plot5_paper_in-situ-data.dr = 0.03
Definition at line 23 of file plot5_paper_in-situ-data.py.
Referenced by EMfields3D.SetLambda().
e_pcls
float plot5_paper_in-situ-data.e_pcls = conv_T*(u_pcls**2+v_pcls**2+w_pcls**2)
Definition at line 100 of file plot5_paper_in-situ-data.py.
enter
int plot5_paper_in-situ-data.enter = 0
Definition at line 59 of file plot5_paper_in-situ-data.py.
from_VTK
plot5_paper_in-situ-data.from_VTK = fb.from_VTK(data_path)
Definition at line 40 of file plot5_paper_in-situ-data.py.
good_data_files
plot5_paper_in-situ-data.good_data_files = np.loadtxt(good_path,unpack=True,dtype='int')
Definition at line 77 of file plot5_paper_in-situ-data.py.
good_path
string plot5_paper_in-situ-data.good_path = sys.argv[1]+'texts/output_dataP-new_'+sys.argv[2]+'.txt'
Definition at line 20 of file plot5_paper_in-situ-data.py.
i_CA
plot5_paper_in-situ-data.i_CA = np.where(dd==min(dd))
Definition at line 55 of file plot5_paper_in-situ-data.py.
idx_sphere
plot5_paper_in-situ-data.idx_sphere = np.where(distance<dr)
Definition at line 121 of file plot5_paper_in-situ-data.py.
imax
plot5_paper_in-situ-data.imax = ii
Definition at line 66 of file plot5_paper_in-situ-data.py.
imin
plot5_paper_in-situ-data.imin = ii
Definition at line 63 of file plot5_paper_in-situ-data.py.
nrun
int plot5_paper_in-situ-data.nrun = 2
Definition at line 17 of file plot5_paper_in-situ-data.py.
output_file
plot5_paper_in-situ-data.output_file = open(sys.argv[1]+'texts/output_good-pcls_%i_%i_'%(nrun,cycle)+sys.argv[2]+'.txt','w')
Definition at line 21 of file plot5_paper_in-situ-data.py.
silent
plot5_paper_in-situ-data.silent
Definition at line 41 of file plot5_paper_in-situ-data.py.
traj_path
plot5_paper_in-situ-data.traj_path = './trajectory_files/'+sys.argv[2]+'-flyby-1st_MSO-trajectory1.txt'
Definition at line 19 of file plot5_paper_in-situ-data.py.
tt
tuple plot5_paper_in-situ-data.tt = (tt-tt[i_CA])/60.
Definition at line 53 of file plot5_paper_in-situ-data.py.
u_pcls
plot5_paper_in-situ-data.u_pcls = d['particles/species_0/u/cycle_'+str(cycle)][:]
Definition at line 95 of file plot5_paper_in-situ-data.py.
unpack
plot5_paper_in-situ-data.unpack
Definition at line 53 of file plot5_paper_in-situ-data.py.
v_pcls
plot5_paper_in-situ-data.v_pcls = d['particles/species_0/v/cycle_'+str(cycle)][:]
Definition at line 96 of file plot5_paper_in-situ-data.py.
versor
list plot5_paper_in-situ-data.versor = [xx[ii+1]-xx[ii],yy[ii+1]-yy[ii],zz[ii+1]-zz[ii]]
Definition at line 116 of file plot5_paper_in-situ-data.py.
w_pcls
plot5_paper_in-situ-data.w_pcls = d['particles/species_0/w/cycle_'+str(cycle)][:]
Definition at line 97 of file plot5_paper_in-situ-data.py.
x
tuple plot5_paper_in-situ-data.x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
Definition at line 42 of file plot5_paper_in-situ-data.py.
x_pcls
tuple plot5_paper_in-situ-data.x_pcls = d['particles/species_0/x/cycle_'+str(cycle)][:]
Definition at line 90 of file plot5_paper_in-situ-data.py.
xc
plot5_paper_in-situ-data.xc = from_VTK.meta['xc']
Definition at line 45 of file plot5_paper_in-situ-data.py.
xx
plot5_paper_in-situ-data.xx = xx[imin:imax]
Definition at line 53 of file plot5_paper_in-situ-data.py.
y
tuple plot5_paper_in-situ-data.y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
Definition at line 43 of file plot5_paper_in-situ-data.py.
y_pcls
tuple plot5_paper_in-situ-data.y_pcls = d['particles/species_0/y/cycle_'+str(cycle)][:]
Definition at line 91 of file plot5_paper_in-situ-data.py.
yc
plot5_paper_in-situ-data.yc = from_VTK.meta['yc']
Definition at line 46 of file plot5_paper_in-situ-data.py.
yy
plot5_paper_in-situ-data.yy = yy[imin:imax]
Definition at line 53 of file plot5_paper_in-situ-data.py.
z
tuple plot5_paper_in-situ-data.z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
Definition at line 44 of file plot5_paper_in-situ-data.py.
z_pcls
tuple plot5_paper_in-situ-data.z_pcls = d['particles/species_0/z/cycle_'+str(cycle)][:]
Definition at line 92 of file plot5_paper_in-situ-data.py.
zc
plot5_paper_in-situ-data.zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
Definition at line 47 of file plot5_paper_in-situ-data.py.
zz
plot5_paper_in-situ-data.zz = zz[imin:imax]
Definition at line 53 of file plot5_paper_in-situ-data.py.