iPIC3DxPEACE: Parameters Namespace Reference
Parameters Namespace Reference
Enumerations
enum Enum {
SoA =0 , AoS , AoSvec , SoAvec ,
AoSintr , SoA_vec_onesort , AoS_vec_onesort , SoA_vec_resort ,
AoS_vec_resort , AoS_Relativistic , SoA =0 , AoS ,
AoSvec , SoAvec , AoSintr , SoA_vec_onesort ,
AoS_vec_onesort , SoA_vec_resort , AoS_vec_resort , AoS_Relativistic ,
SoA =0 , AoS , AoSvec , SoAvec ,
AoSintr , SoA_vec_onesort , AoS_vec_onesort , SoA_vec_resort ,
AoS_vec_resort , AoS_Relativistic
}
enum Enum {
SoA =0 , AoS , AoSvec , SoAvec ,
AoSintr , SoA_vec_onesort , AoS_vec_onesort , SoA_vec_resort ,
AoS_vec_resort , AoS_Relativistic , SoA =0 , AoS ,
AoSvec , SoAvec , AoSintr , SoA_vec_onesort ,
AoS_vec_onesort , SoA_vec_resort , AoS_vec_resort , AoS_Relativistic ,
SoA =0 , AoS , AoSvec , SoAvec ,
AoSintr , SoA_vec_onesort , AoS_vec_onesort , SoA_vec_resort ,
AoS_vec_resort , AoS_Relativistic
}
enum Enum {
SoA =0 , AoS , AoSvec , SoAvec ,
AoSintr , SoA_vec_onesort , AoS_vec_onesort , SoA_vec_resort ,
AoS_vec_resort , AoS_Relativistic , SoA =0 , AoS ,
AoSvec , SoAvec , AoSintr , SoA_vec_onesort ,
AoS_vec_onesort , SoA_vec_resort , AoS_vec_resort , AoS_Relativistic ,
SoA =0 , AoS , AoSvec , SoAvec ,
AoSintr , SoA_vec_onesort , AoS_vec_onesort , SoA_vec_resort ,
AoS_vec_resort , AoS_Relativistic
}
Functions
void init_parameters ()
bool get_USING_AOS ()
bool get_SORTING_SOA ()
bool get_SORTING_PARTICLES ()
bool get_RESORTING_PARTICLES ()
bool get_USING_XAVG ()
bool get_VECTORIZE_MOMENTS ()
Enum get_MOVER_TYPE ()
Enum get_MOMENTS_TYPE ()
int get_multiple_of_vector_width_in_doubles ()
int get_blockSize ()
int get_numBlocks ()
bool get_doWriteOutput ()
Enumeration Type Documentation
Enum [1/3]
enum Parameters::Enum
Enumerator
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
Definition at line 28 of file Parameters.h.
  {
    SoA=0, // struct of arrays
    AoS, // array of structs
    // for moments type
    AoSvec,
    SoAvec,
    AoSintr,
    // for mover type
    SoA_vec_onesort,
    AoS_vec_onesort,
    SoA_vec_resort,
    AoS_vec_resort,
    AoS_Relativistic
  };
Enum [2/3]
enum Parameters::Enum
Enumerator
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
Definition at line 28 of file Parameters.h.
  {
    SoA=0, // struct of arrays
    AoS, // array of structs
    // for moments type
    AoSvec,
    SoAvec,
    AoSintr,
    // for mover type
    SoA_vec_onesort,
    AoS_vec_onesort,
    SoA_vec_resort,
    AoS_vec_resort,
    AoS_Relativistic
  };
Enum [3/3]
enum Parameters::Enum
Enumerator
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
SoA
AoS
AoSvec
SoAvec
AoSintr
SoA_vec_onesort
AoS_vec_onesort
SoA_vec_resort
AoS_vec_resort
AoS_Relativistic
Definition at line 28 of file Parameters.h.
  {
    SoA=0, // struct of arrays
    AoS, // array of structs
    // for moments type
    AoSvec,
    SoAvec,
    AoSintr,
    // for mover type
    SoA_vec_onesort,
    AoS_vec_onesort,
    SoA_vec_resort,
    AoS_vec_resort,
    AoS_Relativistic
  };
Function Documentation
get_blockSize()
int Parameters::get_blockSize ()
Definition at line 38 of file Parameters.cpp.
{ return 8192; }
Referenced by BlockCommunicator< type >::init().
get_doWriteOutput()
bool Parameters::get_doWriteOutput ()
Definition at line 86 of file Parameters.cpp.
{ return true; }
Referenced by iPic3D::c_Solver::Finalize(), iPic3D::c_Solver::Init(), and iPic3D::c_Solver::WriteOutput().
get_MOMENTS_TYPE()
Parameters::Enum Parameters::get_MOMENTS_TYPE ()
Definition at line 45 of file Parameters.cpp.
{ return AoS; }
References AoS.
Referenced by iPic3D::c_Solver::CalculateMoments(), and init_parameters().
get_MOVER_TYPE()
Parameters::Enum Parameters::get_MOVER_TYPE ()
Definition at line 47 of file Parameters.cpp.
{ return AoS; }
References AoS.
Referenced by init_parameters(), and iPic3D::c_Solver::ParticlesMover().
get_multiple_of_vector_width_in_doubles()
int Parameters::get_multiple_of_vector_width_in_doubles ()
Definition at line 30 of file Parameters.cpp.
{ return 8; }
get_numBlocks()
int Parameters::get_numBlocks ()
Definition at line 39 of file Parameters.cpp.
{ return 4; }
Referenced by BlockCommunicator< type >::init().
get_RESORTING_PARTICLES()
bool Parameters::get_RESORTING_PARTICLES ()
Definition at line 76 of file Parameters.cpp.
{ return RESORTING_PARTICLES; }
References RESORTING_PARTICLES.
Referenced by get_USING_XAVG().
get_SORTING_PARTICLES()
bool Parameters::get_SORTING_PARTICLES ()
Definition at line 77 of file Parameters.cpp.
{ return SORTING_PARTICLES; }
References SORTING_PARTICLES.
Referenced by iPic3D::c_Solver::CalculateMoments().
get_SORTING_SOA()
bool Parameters::get_SORTING_SOA ()
Definition at line 78 of file Parameters.cpp.
{ return SORTING_SOA; }
References SORTING_SOA.
get_USING_AOS()
bool Parameters::get_USING_AOS ()
Definition at line 79 of file Parameters.cpp.
{ return USING_AOS; }
References USING_AOS.
get_USING_XAVG()
bool Parameters::get_USING_XAVG () inline
Definition at line 51 of file Parameters.h.
{ return get_RESORTING_PARTICLES(); }
References get_RESORTING_PARTICLES().
get_VECTORIZE_MOMENTS()
bool Parameters::get_VECTORIZE_MOMENTS ()
Definition at line 43 of file Parameters.cpp.
{ return false; }
Referenced by iPic3D::c_Solver::CalculateMoments(), EMfields3D::EMfields3D(), and init_parameters().
init_parameters()
void Parameters::init_parameters ()
Definition at line 55 of file Parameters.cpp.
{
  RESORTING_PARTICLES =
       get_MOVER_TYPE()==SoA_vec_resort
    || get_MOVER_TYPE()==AoS_vec_resort;
  SORTING_PARTICLES = get_VECTORIZE_MOMENTS()
    || get_MOVER_TYPE()==SoA_vec_onesort
    || get_MOVER_TYPE()==AoS_vec_onesort
    || get_MOVER_TYPE()==SoA_vec_resort
    || get_MOVER_TYPE()==AoS_vec_resort;
  SORTING_SOA = get_VECTORIZE_MOMENTS()
    || get_MOVER_TYPE()==SoA_vec_onesort
    || get_MOVER_TYPE()==SoA_vec_resort;
  USING_AOS =
       get_MOMENTS_TYPE()==AoS
    || get_MOVER_TYPE()==AoS
    || get_MOVER_TYPE()==AoSintr
    || get_MOVER_TYPE()==AoS_vec_onesort
    || get_MOVER_TYPE()==AoS_vec_resort;
}
References AoS, AoS_vec_onesort, AoS_vec_resort, AoSintr, get_MOMENTS_TYPE(), get_MOVER_TYPE(), get_VECTORIZE_MOMENTS(), RESORTING_PARTICLES, SoA_vec_onesort, SoA_vec_resort, SORTING_PARTICLES, SORTING_SOA, and USING_AOS.
Referenced by iPic3D::c_Solver::Init().