iPIC3DxPEACE: utility/errors.cpp File Reference
errors.cpp File Reference
#include "MPIdata.h"
#include "ompdefs.h"
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <sstream>
#include "errors.h"
Macros
#define implement_invalid_value_error(t1)
Functions
void fprintf_fileLine (FILE *fptr, const char *type, const char *func, const char *file, int line_number, const char *format,...)
implementation of declarations in errors.h
implement_invalid_value_error (double)
implement_invalid_value_error (int)
implement_invalid_value_error (const char *)
void eprintf_fileLine (FILE *fptr, const char *type, const char *func, const char *file, int line_number, const char *format,...)
Macro Definition Documentation
implement_invalid_value_error
#define implement_invalid_value_error (t1)
Value:
  void invalid_value_error_fileLine(const char* file, int line, const char* func, \
    const char* type, const char* expr, t1 val) \
  { \
    /* To be thread-safe, write the message to a string and \
     * then print it out as an atomic operation. */ \
    std::stringstream ss; \
    ss << "(" << MPIdata::get_rank() << "." << omp_get_thread_num() << ") " \
      << "ERROR in file " << file << ", line " << line  \
      << ", function " << func  \
      <<"\n\t" << type << " value: " << expr << " = " << val << endl; \
    fflush(stdout); \
    { fprintf(stdout,"%s",ss.str().c_str()); }  \
    fflush(stdout); \
    abort(); \
  }
Definition at line 57 of file errors.cpp.
Function Documentation
eprintf_fileLine()
void eprintf_fileLine (FILE * fptr, const char * type, const char * func, const char * file, int line_number, const char * format, ...)
a more verbose version of fprintf_fileLine for use in warnings and error messages
Definition at line 79 of file errors.cpp.
{
  // writing directly to fptr would avoid limiting the length
  // of the output string, but by first writing to a string
  // we achieve thread safety.
  //
  // write the message to a string.
  //
  const int maxchars = 1024;
  char error_msg[maxchars+2];
  // identify the process and thread
  char process_thread_str[50];
  #ifndef NO_MPI
    #ifdef _OPENMP
      snprintf(process_thread_str, 50, ", process %d, thread %d",
        MPIdata::get_rank(), omp_get_thread_num());
    #else
      snprintf(process_thread_str, 50, ", process %d",
        MPIdata::get_rank());
    #endif
  #else
    #ifdef _OPENMP
      snprintf(process_thread_str, 50, ", thread %d",
        omp_get_thread_num());
    #else
      sprintf(process_thread_str, "");
    #endif
  #endif
  char *sptr = error_msg;
  int chars_so_far=0;
  va_list args;
  va_start(args, format);
  chars_so_far = snprintf(sptr, maxchars,
    "%s in method %s(), file %s, line %d%s:\n\t",
    type,
    func, file, // my_basename(file),
    line_number, process_thread_str);
  /* print out remainder of message */
  chars_so_far += vsnprintf(sptr+chars_so_far, maxchars-chars_so_far, format, args);
  va_end(args);
  sprintf(sptr+chars_so_far, "\n");
  // print the message
  fflush(fptr);
    // #pragma omp critical // need this?
  { fprintf(fptr,"%s",error_msg); }
  fflush(fptr);
  abort();
References print_planet_main::args, plot1_paper_nBJ::format, MPIdata::get_rank(), and omp_get_thread_num().
Referenced by assert_error().
fprintf_fileLine()
void fprintf_fileLine (FILE * fptr, const char * type, const char * func, const char * file, int line_number, const char * format, ...)
implementation of declarations in errors.h
Definition at line 101 of file debug.cpp.
{
  //if(MPIdata::get_rank()) return;
  // writing directly to fptr would avoid limiting the length
  // of the output string, but by first writing to a string
  // we achieve thread safety.
  //
  // write the message to a string.
  //
  const int maxchars = 1024;
  char error_msg[maxchars+2];
  // identify the process and thread
  char process_thread_str[20];
  #ifndef NO_MPI
    #ifdef _OPENMP
      snprintf(process_thread_str, 20, "(%d.%d) ",
        MPIdata::get_rank(), omp_get_thread_num());
    #else
      snprintf(process_thread_str, 20, "(%d)",
        MPIdata::get_rank());
    #endif
  #else
    #ifdef _OPENMP
      snprintf(process_thread_str, 20, "(.%d) ",
        omp_get_thread_num());
    #else
      snprintf(process_thread_str, 20, "");
    #endif
  #endif
  char *sptr = error_msg;
  int chars_so_far=0;
  va_list args;
  va_start(args, format);
  chars_so_far = snprintf(sptr, maxchars,
    "%s%s %s(), %s:%d: ",
    process_thread_str,
    type,
    func, /*file,*/ my_basename(file),
    line_number);
  /* print out remainder of message */
  chars_so_far += vsnprintf(sptr+chars_so_far, maxchars-chars_so_far, format, args);
  va_end(args);
  sprintf(sptr+chars_so_far, "\n");
  // print the message
  fflush(fptr);
  fprintf(fptr,"%s",error_msg);
  fflush(fptr);
}
References print_planet_main::args, plot1_paper_nBJ::format, MPIdata::get_rank(), my_basename(), and omp_get_thread_num().
implement_invalid_value_error() [1/3]
implement_invalid_value_error (const char *)
implement_invalid_value_error() [2/3]
implement_invalid_value_error (double)
implement_invalid_value_error() [3/3]
implement_invalid_value_error (int)