var annotated_dup =
[
    [ "iPic3D", null, [
      [ "array1", "dc/d9a/structi_pic3_d_1_1array1.html", null ],
      [ "array2", "d2/d6f/structi_pic3_d_1_1array2.html", null ],
      [ "array3", "d4/d57/structi_pic3_d_1_1array3.html", null ],
      [ "array4", "dd/d8c/structi_pic3_d_1_1array4.html", null ],
      [ "array_fetch1", "d0/de8/classi_pic3_d_1_1array__fetch1.html", null ],
      [ "array_fetch2", "d7/da3/classi_pic3_d_1_1array__fetch2.html", null ],
      [ "array_fetch3", "dd/dfe/classi_pic3_d_1_1array__fetch3.html", null ],
      [ "array_ref1", "de/d52/classi_pic3_d_1_1array__ref1.html", null ],
      [ "array_ref2", "de/dc3/classi_pic3_d_1_1array__ref2.html", null ],
      [ "array_ref3", "da/d5a/classi_pic3_d_1_1array__ref3.html", null ],
      [ "array_ref4", "dc/d69/classi_pic3_d_1_1array__ref4.html", null ],
      [ "base_arr", "d6/d95/classi_pic3_d_1_1base__arr.html", null ],
      [ "c_Solver", "d3/d44/classi_pic3_d_1_1c___solver.html", null ],
      [ "const_array_get1", "db/d23/classi_pic3_d_1_1const__array__get1.html", null ],
      [ "const_array_get2", "d5/dce/classi_pic3_d_1_1const__array__get2.html", null ],
      [ "const_array_get3", "df/dea/classi_pic3_d_1_1const__array__get3.html", null ],
      [ "const_array_ref2", "dd/d25/classi_pic3_d_1_1const__array__ref2.html", null ],
      [ "const_array_ref3", "d6/d3b/classi_pic3_d_1_1const__array__ref3.html", null ],
      [ "const_array_ref4", "d5/df4/classi_pic3_d_1_1const__array__ref4.html", null ]
    ] ],
    [ "PSK", "de/db8/namespace_p_s_k.html", [
      [ "coutOutputAdaptor", "de/d40/class_p_s_k_1_1cout_output_adaptor.html", null ],
      [ "Dimens", "d6/d9c/class_p_s_k_1_1_dimens.html", null ],
      [ "Exception", "de/d63/class_p_s_k_1_1_exception.html", null ],
      [ "HDF5OutputAdaptor", "d2/d07/class_p_s_k_1_1_h_d_f5_output_adaptor.html", null ],
      [ "OutputAdaptor", "d9/de9/class_p_s_k_1_1_output_adaptor.html", null ],
      [ "OutputAgent", "de/d49/class_p_s_k_1_1_output_agent.html", null ],
      [ "OutputAgentBase", "d3/d90/class_p_s_k_1_1_output_agent_base.html", null ],
      [ "OutputException", "d6/d41/class_p_s_k_1_1_output_exception.html", null ],
      [ "OutputManager", "d1/dc3/class_p_s_k_1_1_output_manager.html", null ]
    ] ],
    [ "aligned_allocator", "d8/dd1/classaligned__allocator.html", "d8/dd1/classaligned__allocator" ],
    [ "array_bool", "d2/dbe/structarray__bool.html", null ],
    [ "array_double", "dc/d8e/structarray__double.html", null ],
    [ "array_int", "de/deb/structarray__int.html", null ],
    [ "Block", "dc/d27/struct_block.html", null ],
    [ "BlockCommunicator", "d6/db2/class_block_communicator.html", null ],
    [ "Caller_to_SetMaxThreadsForScope", "d7/d8a/class_caller__to___set_max_threads_for_scope.html", null ],
    [ "Collective", "db/dfb/class_collective.html", "db/dfb/class_collective" ],
    [ "ConfigFile", "d4/d18/class_config_file.html", "d4/d18/class_config_file" ],
    [ "Connection", "dd/d10/class_connection.html", null ],
    [ "doubleIDgenerator", "df/dd6/classdouble_i_dgenerator.html", null ],
    [ "Dvec4", "d9/d80/class_dvec4.html", null ],
    [ "EMfields3D", "dd/da6/class_e_mfields3_d.html", "dd/da6/class_e_mfields3_d" ],
    [ "FixedArray1D", "de/dfa/class_fixed_array1_d.html", null ],
    [ "FixedArray2D", "d7/d4d/class_fixed_array2_d.html", null ],
    [ "FixedArray2D1", "da/dcf/class_fixed_array2_d1.html", null ],
    [ "FixedArray3D", "d5/db4/struct_fixed_array3_d.html", null ],
    [ "FixedArray3D1", "dc/d02/class_fixed_array3_d1.html", null ],
    [ "FixedArray3D2", "d1/d04/class_fixed_array3_d2.html", null ],
    [ "FixedArray4D", "d5/dd1/class_fixed_array4_d.html", null ],
    [ "FixedArray4D1", "d2/d8a/class_fixed_array4_d1.html", null ],
    [ "FixedArray4D2", "d7/de7/class_fixed_array4_d2.html", null ],
    [ "FixedArray4D3", "d5/dc6/class_fixed_array4_d3.html", null ],
    [ "Grid3DCU", "d2/dd3/class_grid3_d_c_u.html", "d2/dd3/class_grid3_d_c_u" ],
    [ "InterfaceFluid", "df/d23/class_interface_fluid.html", null ],
    [ "Ivec8", "d5/d42/class_ivec8.html", null ],
    [ "Larray", "d1/d51/class_larray.html", null ],
    [ "Moments10", "d1/d1c/class_moments10.html", null ],
    [ "MPIdata", "d5/dac/class_m_p_idata.html", "d5/dac/class_m_p_idata" ],
    [ "myOutputAgent", "d6/de3/classmy_output_agent.html", "d6/de3/classmy_output_agent" ],
    [ "OutputWrapperFPP", "d3/d1e/class_output_wrapper_f_p_p.html", null ],
    [ "Particles3D", "d3/dc4/class_particles3_d.html", "d3/dc4/class_particles3_d" ],
    [ "Particles3Dcomm", "d1/da6/class_particles3_dcomm.html", "d1/da6/class_particles3_dcomm" ],
    [ "PHDF5fileClass", "df/d31/class_p_h_d_f5file_class.html", null ],
    [ "SpeciesParticle", "d8/d2e/class_species_particle.html", null ],
    [ "TimeTasks", "d6/d68/class_time_tasks.html", null ],
    [ "TimeTasks_caller_to_set_communication_mode_for_scope", "d2/d76/class_time_tasks__caller__to__set__communication__mode__for__scope.html", null ],
    [ "TimeTasks_caller_to_set_main_task_for_scope", "df/d77/class_time_tasks__caller__to__set__main__task__for__scope.html", null ],
    [ "TimeTasks_caller_to_set_task_for_scope", "d4/def/class_time_tasks__caller__to__set__task__for__scope.html", null ],
    [ "Timing", "d2/d46/class_timing.html", "d2/d46/class_timing" ],
    [ "VCtopology3D", "d0/dd1/class_v_ctopology3_d.html", "d0/dd1/class_v_ctopology3_d" ]
];