iPIC3DxPEACE: iPic3D Namespace Reference
iPic3D Namespace Reference
Classes
class array1
class array2
class array3
class array4
class array_fetch1
class array_fetch2
class array_fetch3
class array_ref1
class array_ref2
class array_ref3
class array_ref4
class base_arr
class c_Solver
class const_array_get1
class const_array_get2
class const_array_get3
class const_array_ref2
class const_array_ref3
class const_array_ref4
Functions
template<class type >
const type **** get_arr4 (const_array_ref4< type > &in)
template<class type >
type **** fetch_arr4 (array_ref4< type > &in)
template<class type >
const type *** get_arr3 (const_array_ref3< type > &in)
template<class type >
type *** fetch_arr3 (array_ref3< type > &in)
template<class type >
const type ** get_arr2 (const_array_ref2< type > &in)
template<class type >
type ** fetch_arr2 (array_ref2< type > &in)
template<class type >
type * fetch_arr (array_ref1< type > &in)
template<class type >
type * fetch_arr (array_fetch1< type > &in)
Function Documentation
fetch_arr() [1/2]
template<class type > type * iPic3D::fetch_arr (array_fetch1< type > & in) inline
Definition at line 901 of file Alloc.h.
  { return in.fetch_arr(); }
fetch_arr() [2/2]
template<class type > type * iPic3D::fetch_arr (array_ref1< type > & in) inline
Definition at line 898 of file Alloc.h.
  { return in.get_arr(); }
fetch_arr2()
template<class type > type ** iPic3D::fetch_arr2 (array_ref2< type > & in) inline
Definition at line 894 of file Alloc.h.
  { return in.fetch_arr2(); }
References iPic3D::array_ref2< type >::fetch_arr2().
fetch_arr3()
template<class type > type *** iPic3D::fetch_arr3 (array_ref3< type > & in) inline
Definition at line 887 of file Alloc.h.
  { return in.fetch_arr3(); }
References iPic3D::array_ref3< type >::fetch_arr3().
fetch_arr4()
template<class type > type **** iPic3D::fetch_arr4 (array_ref4< type > & in) inline
Definition at line 880 of file Alloc.h.
  { return in.fetch_arr4(); }
References iPic3D::array_ref4< type >::fetch_arr4().
get_arr2()
template<class type > const type ** iPic3D::get_arr2 (const_array_ref2< type > & in) inline
Definition at line 891 of file Alloc.h.
  { return in.get_arr2(); }
References iPic3D::const_array_ref2< type >::get_arr2().
get_arr3()
template<class type > const type *** iPic3D::get_arr3 (const_array_ref3< type > & in) inline
Definition at line 884 of file Alloc.h.
  { return in.get_arr3(); }
References iPic3D::const_array_ref3< type >::get_arr3().
get_arr4()
template<class type > const type **** iPic3D::get_arr4 (const_array_ref4< type > & in) inline
Definition at line 877 of file Alloc.h.
  { return in.get_arr4(); }
References iPic3D::const_array_ref4< type >::get_arr4().