CPP = mpicxx
OPTFLAGS = -DMPICH_IGNORE_CXX_SEEK -O2

# include files
INC_KVF = -I${PWD}/ConfigFile/src
INC_HDF5 = -I/usr/local/Cellar/hdf5-mpi/1.12.2/include

# libs
LIB_KVF = -L${PWD}/ConfigFile/src
LIB_HDF5 = -L/usr/local/Cellar/hdf5-mpi/1.12.2/lib
HDF5LIBS = -lhdf5 -lhdf5_hl

ipic3D: iPIC3D.cpp iPIC3D.o

iPIC3D.o: iPIC3D.cpp
	  ${CPP} ${OPTFLAGS} ${INC_HDF5} ${INC_MPI} ${INC_KVF} -c iPIC3D.cpp
