iPIC3DxPEACE: print_iPIC3D_comp-time Namespace Reference
print_iPIC3D_comp-time Namespace Reference
Variables
simu_path = sys.argv[1]
output_path = sys.argv[2]
runs = glob.glob(os.path.join(simu_path,'run*'))[::-1]
nrun = len(runs)
list cycle = []
list fields_comp = []
list fields_comm = []
list pcls_comp = []
list pcls_comm = []
list moments_comp = []
list moments_comm = []
ff = open(glob.glob(os.path.join(runs[i],'RUN*.out'))[0] ,'r')
list dims = [len(cycle),len(fields_comp),len(fields_comm),len(pcls_comp),len(pcls_comm),len(moments_comp),len(moments_comm)]
output = open(output_path+'/computational_time.txt','w')
Variable Documentation
cycle
list print_iPIC3D_comp-time.cycle = []
Definition at line 10 of file print_iPIC3D_comp-time.py.
dims
list print_iPIC3D_comp-time.dims = [len(cycle),len(fields_comp),len(fields_comm),len(pcls_comp),len(pcls_comm),len(moments_comp),len(moments_comm)]
Definition at line 35 of file print_iPIC3D_comp-time.py.
Referenced by readwriteparticles(), and readwritepartproc().
ff
print_iPIC3D_comp-time.ff = open(glob.glob(os.path.join(runs[i],'RUN*.out'))[0] ,'r')
Definition at line 19 of file print_iPIC3D_comp-time.py.
fields_comm
list print_iPIC3D_comp-time.fields_comm = []
Definition at line 12 of file print_iPIC3D_comp-time.py.
fields_comp
list print_iPIC3D_comp-time.fields_comp = []
Definition at line 11 of file print_iPIC3D_comp-time.py.
moments_comm
list print_iPIC3D_comp-time.moments_comm = []
Definition at line 16 of file print_iPIC3D_comp-time.py.
moments_comp
list print_iPIC3D_comp-time.moments_comp = []
Definition at line 15 of file print_iPIC3D_comp-time.py.
nrun
print_iPIC3D_comp-time.nrun = len(runs)
Definition at line 9 of file print_iPIC3D_comp-time.py.
output
print_iPIC3D_comp-time.output = open(output_path+'/computational_time.txt','w')
Definition at line 37 of file print_iPIC3D_comp-time.py.
Referenced by InterfaceFluid.ReadIdlAscii().
output_path
print_iPIC3D_comp-time.output_path = sys.argv[2]
Definition at line 6 of file print_iPIC3D_comp-time.py.
pcls_comm
list print_iPIC3D_comp-time.pcls_comm = []
Definition at line 14 of file print_iPIC3D_comp-time.py.
pcls_comp
list print_iPIC3D_comp-time.pcls_comp = []
Definition at line 13 of file print_iPIC3D_comp-time.py.
runs
print_iPIC3D_comp-time.runs = glob.glob(os.path.join(simu_path,'run*'))[::-1]
Definition at line 8 of file print_iPIC3D_comp-time.py.
simu_path
print_iPIC3D_comp-time.simu_path = sys.argv[1]
Definition at line 5 of file print_iPIC3D_comp-time.py.