iPIC3DxPEACE: particles/Particles3Dcomm.cpp File Reference
Particles3Dcomm.cpp File Reference
#include <mpi.h>
#include <iostream>
#include <math.h>
#include <limits.h>
#include "asserts.h"
#include <algorithm>
#include "VCtopology3D.h"
#include "Collective.h"
#include "Alloc.h"
#include "Grid3DCU.h"
#include "Field.h"
#include "MPIdata.h"
#include "ompdefs.h"
#include "ipicmath.h"
#include "ipicdefs.h"
#include "mic_basics.h"
#include "parallel.h"
#include "Particle.h"
#include "Particles3Dcomm.h"
#include "Parameters.h"
#include "ipichdf5.h"
#include "debug.h"
#include "TimeTasks.h"
Namespaces
namespace PclCommMode
Macros
#define sort_pcls(pcls, start_in, start_out, condition)
Enumerations
enum PclCommMode::Enum {
PclCommMode::do_apply_BCs_globally =1 , PclCommMode::print_sent_pcls =2 , PclCommMode::do_apply_BCs_globally =1 , PclCommMode::print_sent_pcls =2 ,
PclCommMode::do_apply_BCs_globally =1 , PclCommMode::print_sent_pcls =2
}
Functions
static void print_pcl (SpeciesParticle &pcl, int ns)
static void print_pcls (vector_SpeciesParticle &pcls, int start, int ns)
void print_pcls (vector_SpeciesParticle &pcls, int ns, longid *id_list, int num_ids)
Variables
static bool print_pcl_comm_counts = false
Class for particles of the same species, in a 2D space and 3component velocity.
static bool do_apply_periodic_BC_global = false
Macro Definition Documentation
sort_pcls
#define sort_pcls (pcls, start_in, start_out, condition)
Value:
{ \
  int start = (start_in); \
  assert(0<=start); \
  start_out = pcls.size(); \
  /* pidx traverses the array */ \
  for(int pidx=pcls.size()-1;pidx>=start;pidx--) \
  { \
    assert(pidx<start_out); \
    /* if condition is true, put the particle at the end of the list */ \
    if(condition(pcls[pidx])) \
    { \
      --start_out; \
      SpeciesParticle tmp_pcl = pcls[pidx]; \
      pcls[pidx] = pcls[start_out]; \
      pcls[start_out] = tmp_pcl; \
    } \
  } \
}
Definition at line 592 of file Particles3Dcomm.cpp.
Function Documentation
print_pcl()
static void print_pcl (SpeciesParticle & pcl, int ns) static
Definition at line 69 of file Particles3Dcomm.cpp.
{
  dprintf("--- pcl spec %d ---", ns);
  dprintf("u = %+6.4f", pcl.get_u());
  dprintf("v = %+6.4f", pcl.get_v());
  dprintf("w = %+6.4f", pcl.get_w());
  dprintf("q = %+6.4f", pcl.get_q());
  dprintf("x = %+6.4f", pcl.get_x());
  dprintf("y = %+6.4f", pcl.get_y());
  dprintf("z = %+6.4f", pcl.get_z());
  dprintf("t = %5.0f", pcl.get_t());
}
References dprintf, SpeciesParticle::get_q(), SpeciesParticle::get_t(), SpeciesParticle::get_u(), SpeciesParticle::get_v(), SpeciesParticle::get_w(), SpeciesParticle::get_x(), SpeciesParticle::get_y(), SpeciesParticle::get_z(), and ns.
Referenced by Particles3Dcomm::handle_received_particles().
print_pcls() [1/2]
void print_pcls (vector_SpeciesParticle & pcls, int ns, longid * id_list, int num_ids)
Definition at line 97 of file Particles3Dcomm.cpp.
{
  dprintf("=== species %d, with %d pcls ===", ns, pcls.size());
  for(int pidx=0; pidx<pcls.size();pidx++)
  for(int i=0;i<num_ids;i++)
  if(pcls[pidx].get_ID()==id_list[i])
  {
    dprintf("--- particle %d.%d ---", ns,pidx);
    dprintf("u[%d] = %+6.4f", pidx, pcls[pidx].get_u());
    dprintf("v[%d] = %+6.4f", pidx, pcls[pidx].get_v());
    dprintf("w[%d] = %+6.4f", pidx, pcls[pidx].get_w());
    dprintf("q[%d] = %+6.4f", pidx, pcls[pidx].get_q());
    dprintf("x[%d] = %+6.4f", pidx, pcls[pidx].get_x());
    dprintf("y[%d] = %+6.4f", pidx, pcls[pidx].get_y());
    dprintf("z[%d] = %+6.4f", pidx, pcls[pidx].get_z());
    dprintf("t[%d] = %5.0f", pidx, pcls[pidx].get_t());
  }
}
print_pcls() [2/2]
static void print_pcls (vector_SpeciesParticle & pcls, int start, int ns) static
Definition at line 82 of file Particles3Dcomm.cpp.
{
  for(int pidx=start; pidx<pcls.size();pidx++)
  {
    dprintf("--- particle %d.%d ---", ns,pidx);
    dprintf("u[%d] = %+6.4f", pidx, pcls[pidx].get_u());
    dprintf("v[%d] = %+6.4f", pidx, pcls[pidx].get_v());
    dprintf("w[%d] = %+6.4f", pidx, pcls[pidx].get_w());
    dprintf("q[%d] = %+6.4f", pidx, pcls[pidx].get_q());
    dprintf("x[%d] = %+6.4f", pidx, pcls[pidx].get_x());
    dprintf("y[%d] = %+6.4f", pidx, pcls[pidx].get_y());
    dprintf("z[%d] = %+6.4f", pidx, pcls[pidx].get_z());
    dprintf("t[%d] = %5.0f", pidx, pcls[pidx].get_t());
  }
}
References dprintf, ns, and print_global_ipic::start.
Referenced by Particles3Dcomm::apply_BCs_globally().
Variable Documentation
do_apply_periodic_BC_global
bool do_apply_periodic_BC_global = false static
Definition at line 743 of file Particles3Dcomm.cpp.
Referenced by Particles3Dcomm::apply_BCs_globally(), and Particles3Dcomm::recommunicate_particles_until_done().
print_pcl_comm_counts
bool print_pcl_comm_counts = false static
Class for particles of the same species, in a 2D space and 3component velocity.
Date
Fri Jun 4 2007
Author
Stefano Markidis, Giovanni Lapenta
Version
2.0
Definition at line 67 of file Particles3Dcomm.cpp.
Referenced by Particles3Dcomm::handle_received_particles(), Particles3Dcomm::recommunicate_particles_until_done(), and Particles3Dcomm::separate_and_send_particles().