iPIC3DxPEACE: post-process/post-process/include/Alloc.h File Reference
Alloc.h File Reference
#include <cstddef>
#include "asserts.h"
#include "arraysfwd.h"
Classes
class iPic3D::base_arr< type >
class iPic3D::array_ref1< type >
class iPic3D::const_array_ref2< type >
class iPic3D::array_ref2< type >
class iPic3D::const_array_ref3< type >
class iPic3D::array_ref3< type >
class iPic3D::const_array_ref4< type >
class iPic3D::array_ref4< type >
class iPic3D::array1< type >
class iPic3D::array2< type >
class iPic3D::array3< type >
class iPic3D::array4< type >
Namespaces
namespace iPic3D
Macros
#define ALIGNMENT (64)
#define ALLOC_ALIGNED
#define ASSUME_ALIGNED(X)
#define ALIGNED(X)
#define AlignedFree(S) (delete[] S)
#define AlignedAlloc(T, NUM) (new T[NUM])
#define assert_aligned(X, N) assert(is_aligned(X, N));
#define check_bounds(n, S)
#define newArr4(type, sz1, sz2, sz3, sz4) newArray4<type>((sz1),(sz2),(sz3),(sz4))
#define newArr3(type, sz1, sz2, sz3) newArray3<type>((sz1),(sz2),(sz3))
#define newArr2(type, sz1, sz2) newArray2<type>((sz1),(sz2))
Functions
bool is_aligned (void *p, int N)
template<class type >
type * newArray1 (size_t sz1)
template<class type >
type ** newArray2 (size_t sz1, size_t sz2)
template<class type >
type *** newArray3 (size_t sz1, size_t sz2, size_t sz3)
template<class type >
type **** newArray4 (size_t sz1, size_t sz2, size_t sz3, size_t sz4)
template<class type >
type **** newArray4 (type *in, size_t sz1, size_t sz2, size_t sz3, size_t sz4)
template<class type >
type *** newArray3 (type *in, size_t sz1, size_t sz2, size_t sz3)
template<class type >
type ** newArray2 (type *in, size_t sz1, size_t sz2)
template<class type >
void delArray1 (type *arr)
template<class type >
void delArray2 (type **arr)
template<class type >
void delArray3 (type ***arr)
template<class type >
void delArray4 (type ****arr)
template<class type >
void delArr1 (type *arr)
template<class type >
void delArr2 (type **arr, size_t sz1)
template<class type >
void delArr3 (type ***arr, size_t sz1, size_t sz2)
template<class type >
void delArr4 (type ****arr, size_t sz1, size_t sz2, size_t sz3)
template<class type >
const type **** iPic3D::get_arr4 (const_array_ref4< type > &in)
template<class type >
type **** iPic3D::fetch_arr4 (array_ref4< type > &in)
template<class type >
const type *** iPic3D::get_arr3 (const_array_ref3< type > &in)
template<class type >
type *** iPic3D::fetch_arr3 (array_ref3< type > &in)
template<class type >
const type ** iPic3D::get_arr2 (const_array_ref2< type > &in)
template<class type >
type ** iPic3D::fetch_arr2 (array_ref2< type > &in)
template<class type >
type * iPic3D::fetch_arr (array_ref1< type > &in)
template<class type >
type * iPic3D::fetch_arr (array_fetch1< type > &in)
Macro Definition Documentation
ALIGNED
#define ALIGNED (X)
Definition at line 96 of file Alloc.h.
AlignedAlloc
#define AlignedAlloc (T, NUM) (new T[NUM])
Definition at line 98 of file Alloc.h.
AlignedFree
#define AlignedFree (S) (delete[] S)
Definition at line 97 of file Alloc.h.
ALIGNMENT
#define ALIGNMENT (64)
Definition at line 85 of file Alloc.h.
ALLOC_ALIGNED
#define ALLOC_ALIGNED
Definition at line 94 of file Alloc.h.
assert_aligned
#define assert_aligned (X, N) assert(is_aligned(X, N));
Definition at line 104 of file Alloc.h.
ASSUME_ALIGNED
#define ASSUME_ALIGNED (X)
Definition at line 95 of file Alloc.h.
check_bounds
#define check_bounds (n, S)
Definition at line 112 of file Alloc.h.
newArr2
#define newArr2 (type, sz1, sz2) newArray2<type>((sz1),(sz2))
Definition at line 911 of file Alloc.h.
newArr3
#define newArr3 (type, sz1, sz2, sz3) newArray3<type>((sz1),(sz2),(sz3))
Definition at line 910 of file Alloc.h.
newArr4
#define newArr4 (type, sz1, sz2, sz3, sz4) newArray4<type>((sz1),(sz2),(sz3),(sz4))
Definition at line 909 of file Alloc.h.
Function Documentation
delArr1()
template<class type > void delArr1 (type * arr) inline
Definition at line 216 of file Alloc.h.
{ delArray1(arr); }
References delArray1().
delArr2()
template<class type > void delArr2 (type ** arr, size_t sz1) inline
Definition at line 218 of file Alloc.h.
{ delArray2(arr); }
References delArray2().
delArr3()
template<class type > void delArr3 (type *** arr, size_t sz1, size_t sz2) inline
Definition at line 220 of file Alloc.h.
{ delArray3(arr); }
References delArray3().
delArr4()
template<class type > void delArr4 (type **** arr, size_t sz1, size_t sz2, size_t sz3) inline
Definition at line 222 of file Alloc.h.
{ delArray3(arr); }
References delArray3().
delArray1()
template<class type > void delArray1 (type * arr) inline
Definition at line 205 of file Alloc.h.
{ AlignedFree(arr); }
References AlignedFree.
delArray2()
template<class type > void delArray2 (type ** arr) inline
Definition at line 207 of file Alloc.h.
{ delArray1(arr[0]); AlignedFree(arr); }
References AlignedFree, and delArray1().
delArray3()
template<class type > void delArray3 (type *** arr) inline
Definition at line 209 of file Alloc.h.
{ delArray2(arr[0]); AlignedFree(arr); }
References AlignedFree, and delArray2().
delArray4()
template<class type > void delArray4 (type **** arr) inline
Definition at line 211 of file Alloc.h.
{ delArray3(arr[0]); AlignedFree(arr); }
References AlignedFree, and delArray3().
is_aligned()
bool is_aligned (void * p, int N) inline
Definition at line 100 of file Alloc.h.
{
    return (unsigned long)p % N == 0;
}
newArray1()
template<class type > type * newArray1 (size_t sz1) inline
Definition at line 122 of file Alloc.h.
{
  type *arr = AlignedAlloc(type, sz1); // new type [sz1];
  return arr;
}
References AlignedAlloc.
newArray2() [1/2]
template<class type > type ** newArray2 (size_t sz1, size_t sz2) inline
Definition at line 128 of file Alloc.h.
{
  type **arr = AlignedAlloc(type*, sz1); // new type *[sz1];
  type *ptr = newArray1<type>(sz1*sz2);
  for (size_t i = 0; i < sz1; i++)
  {
    arr[i] = ptr;
    ptr += sz2;
  }
  return arr;
}
References AlignedAlloc, and test_new-features::i.
newArray2() [2/2]
template<class type > type ** newArray2 (type * in, size_t sz1, size_t sz2) inline
Definition at line 192 of file Alloc.h.
{
  type**arr = newArray1<type*>(sz1);
  type *ptr = in;
  for(size_t i=0;i<sz1;i++) {
    arr[i] = ptr;
    ptr += sz2;
  }
  return arr;
}
References test_new-features::i.
newArray3() [1/2]
template<class type > type *** newArray3 (size_t sz1, size_t sz2, size_t sz3) inline
Definition at line 140 of file Alloc.h.
{
  type ***arr = AlignedAlloc(type**, sz1); // new type **[sz1];
  type **ptr = newArray2<type>(sz1*sz2, sz3);
  for (size_t i = 0; i < sz1; i++)
  {
    arr[i] = ptr;
    ptr += sz2;
  }
  return arr;
}
References AlignedAlloc, and test_new-features::i.
newArray3() [2/2]
template<class type > type *** newArray3 (type * in, size_t sz1, size_t sz2, size_t sz3) inline
Definition at line 179 of file Alloc.h.
{
  type***arr = newArray2<type*>(sz1,sz2);
  type**arr2 = *arr;
  type *ptr = in;
  size_t szarr2 = sz1*sz2;
  for(size_t i=0;i<szarr2;i++) {
    arr2[i] = ptr;
    ptr += sz3;
  }
  return arr;
}
References test_new-features::i.
newArray4() [1/2]
template<class type > type **** newArray4 (size_t sz1, size_t sz2, size_t sz3, size_t sz4) inline
Definition at line 152 of file Alloc.h.
{
  type ****arr = AlignedAlloc(type***, sz1); //(new type ***[sz1]);
  type ***ptr = newArray3<type>(sz1*sz2, sz3, sz4);
  for (size_t i = 0; i < sz1; i++) {
    arr[i] = ptr;
    ptr += sz2;
  }
  return arr;
}
References AlignedAlloc, and test_new-features::i.
newArray4() [2/2]
template<class type > type **** newArray4 (type * in, size_t sz1, size_t sz2, size_t sz3, size_t sz4) inline
Definition at line 166 of file Alloc.h.
{
  type****arr = newArray3<type*>(sz1,sz2,sz3);
  type**arr2 = **arr;
  type *ptr = in;
  size_t szarr2 = sz1*sz2*sz3;
  for(size_t i=0;i<szarr2;i++) {
    arr2[i] = ptr;
    ptr += sz4;
  }
  return arr;
}
References test_new-features::i.