iPIC3DxPEACE: fibo.mod_get.fibo_get Class Reference
fibo.mod_get.fibo_get Class Reference
Public Member Functions
def get_time_exit (self, tar_segs, tar_time, criteria='closer', silent=True)
def get_data (self, tar_var)
def get_pnts (self, tar_var)
def get_time_exit (self, tar_segs, tar_time, criteria='closer', silent=True)
def get_data (self, tar_var)
def get_pnts (self, tar_var)
Detailed Description
Definition at line 15 of file mod_get.py.
Member Function Documentation
get_data() [1/2]
def fibo.mod_get.fibo_get.get_data (self, tar_var)
Gives you the data array, overrunning fibo privileged data storage ...
Parameters :
  - tar_var   [str OR np.ndarray OR None]   name in list(fibo.data) OR (nx,ny,nz) array
Returns :
  - data      [fibo.data]
Definition at line 59 of file mod_get.py.
      tar_var):
    """
    Gives you the data array, overrunning fibo privileged data storage ...
    Parameters :
      - tar_var   [str OR np.ndarray OR None]   name in list(fibo.data) OR (nx,ny,nz) array
    Returns :
      - data      [fibo.data]
    """
    if   isinstance(tar_var, str) : return self.data[tar_var]
    elif isinstance(tar_var, np.ndarray) : return tar_var
    else :
      print ('??WTW??')
      return None
References fibo.fibo.data.
Referenced by fibo.mod_calc.fibo_calc.calc_cross(), fibo.mod_calc.fibo_calc.calc_divid(), fibo.mod_calc.fibo_calc.calc_gradx(), fibo.mod_calc.fibo_calc.calc_grady(), fibo.mod_calc.fibo_calc.calc_gradz(), fibo.mod_calc.fibo_calc.calc_irr_sol(), fibo.mod_calc.fibo_calc.calc_par_per(), fibo.mod_calc.fibo_calc.calc_project(), fibo.mod_calc.fibo_calc.calc_scalr(), fibo.mod_calc.fibo_calc.calc_slided(), fibo.mod_calc.fibo_calc.calc_spots(), fibo.mod_calc.fibo_calc.calc_temp(), fibo.mod_comp.fibo_comp.comp_region_number(), fibo.mod_comp.fibo_comp.comp_shell_pop(), fibo.mod_comp.fibo_comp.comp_spot_number(), fibo.mod_draw.fibo_draw.draw_contour(), fibo.mod_extract.fibo_extract.extract_every(), fibo.mod_extract.fibo_extract.extract_grid(), fibo.mod_extract.fibo_extract.extract_interpol_fourier(), fibo.mod_extract.fibo_extract.extract_line(), fibo.mod_extract.fibo_extract.extract_range(), fibo.mod_find.fibo_find.find_critical_delaunay_2d(), fibo.mod_find.fibo_find.find_critical_squarely_2d(), fibo.mod_find.fibo_find.find_critical_starlike_2d(), fibo.mod_extra.fibo_extra.frame_MVA(), fibo.mod_extra.fibo_extra.make_spect(), fibo.mod_print.fibo_print.print_vtk_scal(), fibo.mod_print.fibo_print.print_vtk_vect(), and fibo.mod_extra.fibo_extra.stat_minimal().
get_data() [2/2]
def fibo.mod_get.fibo_get.get_data (self, tar_var)
Gives you the data array, overrunning fibo privileged data storage ...
Parameters :
  - tar_var   [str OR np.ndarray OR None]   name in list(fibo.data) OR (nx,ny,nz) array
Returns :
  - data      [fibo.data]
Definition at line 59 of file mod_get.py.
      tar_var):
    """
    Gives you the data array, overrunning fibo privileged data storage ...
    Parameters :
      - tar_var   [str OR np.ndarray OR None]   name in list(fibo.data) OR (nx,ny,nz) array
    Returns :
      - data      [fibo.data]
    """
    if   isinstance(tar_var, str) : return self.data[tar_var]
    elif isinstance(tar_var, np.ndarray) : return tar_var
    else :
      print ('??WTW??')
      return None
References fibo.fibo.data.
Referenced by fibo.mod_calc.fibo_calc.calc_cross(), fibo.mod_calc.fibo_calc.calc_divid(), fibo.mod_calc.fibo_calc.calc_gradx(), fibo.mod_calc.fibo_calc.calc_grady(), fibo.mod_calc.fibo_calc.calc_gradz(), fibo.mod_calc.fibo_calc.calc_irr_sol(), fibo.mod_calc.fibo_calc.calc_par_per(), fibo.mod_calc.fibo_calc.calc_project(), fibo.mod_calc.fibo_calc.calc_scalr(), fibo.mod_calc.fibo_calc.calc_slided(), fibo.mod_calc.fibo_calc.calc_spots(), fibo.mod_calc.fibo_calc.calc_temp(), fibo.mod_comp.fibo_comp.comp_region_number(), fibo.mod_comp.fibo_comp.comp_shell_pop(), fibo.mod_comp.fibo_comp.comp_spot_number(), fibo.mod_draw.fibo_draw.draw_contour(), fibo.mod_extract.fibo_extract.extract_every(), fibo.mod_extract.fibo_extract.extract_grid(), fibo.mod_extract.fibo_extract.extract_interpol_fourier(), fibo.mod_extract.fibo_extract.extract_line(), fibo.mod_extract.fibo_extract.extract_range(), fibo.mod_find.fibo_find.find_critical_delaunay_2d(), fibo.mod_find.fibo_find.find_critical_squarely_2d(), fibo.mod_find.fibo_find.find_critical_starlike_2d(), fibo.mod_extra.fibo_extra.frame_MVA(), fibo.mod_extra.fibo_extra.make_spect(), fibo.mod_print.fibo_print.print_vtk_scal(), fibo.mod_print.fibo_print.print_vtk_vect(), and fibo.mod_extra.fibo_extra.stat_minimal().
get_pnts() [1/2]
def fibo.mod_get.fibo_get.get_pnts (self, tar_var)
Gives you the data array, overrunning fibo privileged data storage ...
Parameters :
  - tar_var   [str OR np.ndarray OR None]   name in list(fibo.pnts) OR (3,nn) array
Returns :
  - data      [fibo.pnts]
Definition at line 79 of file mod_get.py.
      tar_var):
    """
    Gives you the data array, overrunning fibo privileged data storage ...
    Parameters :
      - tar_var   [str OR np.ndarray OR None]   name in list(fibo.pnts) OR (3,nn) array
    Returns :
      - data      [fibo.pnts]
    """
    if   isinstance(tar_var, str) : return self.pnts[tar_var]
    elif isinstance(tar_var, np.ndarray) : return tar_var
    else :
      print ('??WTW??')
      return None
References fibo.fibo.pnts.
Referenced by fibo.mod_comp.fibo_comp.comp_clusters(), fibo.mod_comp.fibo_comp.comp_distances(), fibo.mod_find.fibo_find.find_common(), fibo.mod_find.fibo_find.find_middle_pnts(), fibo.mod_find.fibo_find.find_range(), and fibo.mod_extra.fibo_extra.stat_minimal().
get_pnts() [2/2]
def fibo.mod_get.fibo_get.get_pnts (self, tar_var)
Gives you the data array, overrunning fibo privileged data storage ...
Parameters :
  - tar_var   [str OR np.ndarray OR None]   name in list(fibo.pnts) OR (3,nn) array
Returns :
  - data      [fibo.pnts]
Definition at line 79 of file mod_get.py.
      tar_var):
    """
    Gives you the data array, overrunning fibo privileged data storage ...
    Parameters :
      - tar_var   [str OR np.ndarray OR None]   name in list(fibo.pnts) OR (3,nn) array
    Returns :
      - data      [fibo.pnts]
    """
    if   isinstance(tar_var, str) : return self.pnts[tar_var]
    elif isinstance(tar_var, np.ndarray) : return tar_var
    else :
      print ('??WTW??')
      return None
References fibo.fibo.pnts.
Referenced by fibo.mod_comp.fibo_comp.comp_clusters(), fibo.mod_comp.fibo_comp.comp_distances(), fibo.mod_find.fibo_find.find_common(), fibo.mod_find.fibo_find.find_middle_pnts(), fibo.mod_find.fibo_find.find_range(), and fibo.mod_extra.fibo_extra.stat_minimal().
get_time_exit() [1/2]
def fibo.mod_get.fibo_get.get_time_exit (self, tar_segs, tar_time, criteria = 'closer', silent = True)
Gives you the segment and exact exit number to look at ...
Parameters :
  - tar_segs                [loader.segs] time segments
  - tar_time                [float] time you want to be
  - criteria = 'closer'     ['after','before','closer'] how to choose your time exit!
  - Returns :
  - to_load                 [str,int,float] seg to load, exit number, time difference
Definition at line 20 of file mod_get.py.
      silent=True):
    """
    Gives you the segment and exact exit number to look at ...
    Parameters :
      - tar_segs                [loader.segs] time segments
      - tar_time                [float] time you want to be
      - criteria = 'closer'     ['after','before','closer'] how to choose your time exit!
      - Returns :
      - to_load                 [str,int,float] seg to load, exit number, time difference
    """
    to_load = [' ',0,float("inf")]
    for seg in tar_segs.keys() :
      for exit_num in range(len(tar_segs[seg])):
        time_diff = float(tar_segs[seg][exit_num]) - tar_time
        if criteria == 'closer' : time_diff = np.absolute(time_diff)
        if criteria == 'before' : time_diff = -time_diff
        if (time_diff >= 0. and time_diff < to_load[2]):
          to_load[0] = seg
          to_load[1] = exit_num
          to_load[2] = time_diff
    if not silent:
      print('fibo_get_time_exit()>tar_time    :',tar_time)
      print('fibo_get_time_exit()>criteria    :',criteria)
      print('fibo_get_time_exit() return -->   ',to_load)
    return to_load
References plot2_paper_df.range.
get_time_exit() [2/2]
def fibo.mod_get.fibo_get.get_time_exit (self, tar_segs, tar_time, criteria = 'closer', silent = True)
Gives you the segment and exact exit number to look at ...
Parameters :
  - tar_segs                [loader.segs] time segments
  - tar_time                [float] time you want to be
  - criteria = 'closer'     ['after','before','closer'] how to choose your time exit!
  - Returns :
  - to_load                 [str,int,float] seg to load, exit number, time difference
Definition at line 20 of file mod_get.py.
      silent=True):
    """
    Gives you the segment and exact exit number to look at ...
    Parameters :
      - tar_segs                [loader.segs] time segments
      - tar_time                [float] time you want to be
      - criteria = 'closer'     ['after','before','closer'] how to choose your time exit!
      - Returns :
      - to_load                 [str,int,float] seg to load, exit number, time difference
    """
    to_load = [' ',0,float("inf")]
    for seg in tar_segs.keys() :
      for exit_num in range(len(tar_segs[seg])):
        time_diff = float(tar_segs[seg][exit_num]) - tar_time
        if criteria == 'closer' : time_diff = np.absolute(time_diff)
        if criteria == 'before' : time_diff = -time_diff
        if (time_diff >= 0. and time_diff < to_load[2]):
          to_load[0] = seg
          to_load[1] = exit_num
          to_load[2] = time_diff
    if not silent:
      print('fibo_get_time_exit()>tar_time    :',tar_time)
      print('fibo_get_time_exit()>criteria    :',criteria)
      print('fibo_get_time_exit() return -->   ',to_load)
    return to_load
References plot2_paper_df.range.
The documentation for this class was generated from the following files:
post-process/fibo/mod_get.py
post-process/post-process/fibo/mod_get.py