iPIC3DxPEACE: PSKOutput3D/test_pskoutput.cc File Reference
test_pskoutput.cc File Reference
#include <iostream>
#include <string>
#include "PSKOutput.h"
#include "PSKhdf5adaptor.h"
Classes
class myOutputAgent< Toa >
Functions
main ()
Function Documentation
main()
main ()
Definition at line 52 of file test_pskoutput.cc.
      {
// create the output manager which will keep track of different
//   output agents
  PSK::OutputManager< PSK::OutputAdaptor > output_mgr;
// make two instances of class myOutputAgent, one which uses
//   the HDF5 output adaptor, and another which uses a stream to std::cout
  myOutputAgent< PSK::HDF5OutputAdaptor > my_output_agent;
  myOutputAgent< PSK::coutOutputAdaptor > my_cout_output_agent;
// Add the HDF5 output agent to the Output Manager's list
  output_mgr.push_back( &my_output_agent );
// do the same again for the cout output agent
  output_mgr.push_back( &my_cout_output_agent );
// open the hdf5 file
  my_output_agent.open( "agent.hdf");
// no need to open the cout output agent
// run the actions ...
  output_mgr.output( "Stage 1" );
  output_mgr.output( "Stage 2" );
// close the hdf5 file
  my_output_agent.close();
}
References PSK::OutputAgent< Toa >::close(), PSK::OutputAgent< Toa >::open(), PSK::OutputManager< Toa >::output(), and PSK::OutputManager< Toa >::push_back().