iPIC3DxPEACE: post-process/include/ipicmath.h File Reference
ipicmath.h File Reference
#include "assert.h"
#include "math.h"
#include "stdlib.h"
Functions
int pow2roundup (int x)
int pow2rounddown (int x)
int ceiling_of_ratio (int n, int m)
int roundup_to_multiple (int n, int m)
double sample_clopen_u_double ()
static double sample_open_u_double ()
double sample_u_double ()
void sample_standard_maxwellian (double &u)
void sample_standard_maxwellian (double &u, double &v)
void sample_standard_maxwellian (double &u, double &v, double &w)
void sample_maxwellian (double &u, double ut)
void sample_maxwellian (double &u, double &v, double &w, double ut, double vt, double wt)
void sample_maxwellian (double &u, double &v, double &w, double ut, double vt, double wt, double u0, double v0, double w0)
double modulo (double x, double L, double Linv)
RIFAI QUESTA PARTE questo e' la tomba delle performance.
Function Documentation
ceiling_of_ratio()
int ceiling_of_ratio (int n, int m) inline
Definition at line 64 of file ipicmath.h.
{
  // probably this way is cheapest
  return ((n-1)/m+1);
  //return (n+m-1)/m;
  //const int out = ceil(n/double(m));
  //return out;
}
modulo()
double modulo (double x, double L, double Linv) inline
RIFAI QUESTA PARTE questo e' la tomba delle performance.
Definition at line 169 of file ipicmath.h.
{
  return x - floor(x * Linv) * L;
}
References plot_Jpar-planet::x.
pow2rounddown()
int pow2rounddown (int x) inline
Definition at line 45 of file ipicmath.h.
{
    assert(x>=0);
    //if (x < 0)
    //    return 0;
    // set all bits below highest bit
    x |= x >> 1;
    x |= x >> 2;
    x |= x >> 4;
    x |= x >> 8;
    x |= x >> 16;
    // set the bit higher than the highest bit
    x++;
    // shift it down and return it
    return (x >> 1);
}
References plot_Jpar-planet::x.
pow2roundup()
int pow2roundup (int x) inline
Definition at line 29 of file ipicmath.h.
{
    assert(x>=0);
    //if (x < 0)
    //    return 0;
    --x;
    x |= x >> 1;
    x |= x >> 2;
    x |= x >> 4;
    x |= x >> 8;
    x |= x >> 16;
    return x+1;
}
References plot_Jpar-planet::x.
roundup_to_multiple()
int roundup_to_multiple (int n, int m) inline
Definition at line 74 of file ipicmath.h.
{
  //return ((n-1)/m+1)*m;
  return (n+m-1)/m*m;
}
sample_clopen_u_double()
double sample_clopen_u_double () inline
Definition at line 81 of file ipicmath.h.
{
  // old way (retained for sake of bit-wise code agreement)
  const double harvest = rand() / (double) RAND_MAX;
  return 1.0 - .999999 * harvest;
  // better way
  const double max_inv = 1./(double(RAND_MAX)+1);
  return (double(rand())+1)*max_inv;
}
sample_maxwellian() [1/3]
void sample_maxwellian (double & u, double & v, double & w, double ut, double vt, double wt) inline
Definition at line 139 of file ipicmath.h.
{
  sample_standard_maxwellian(u,v,w);
  u *= ut;
  v *= vt;
  w *= wt;
}
References sample_standard_maxwellian(), plot1_paper-2_precipitation::u, plot1_paper-2_precipitation::v, and plot1_paper-2_precipitation::w.
sample_maxwellian() [2/3]
void sample_maxwellian (double & u, double & v, double & w, double ut, double vt, double wt, double u0, double v0, double w0) inline
Definition at line 148 of file ipicmath.h.
{
  sample_standard_maxwellian(u,v,w);
  u = u0 + ut*u;
  v = v0 + vt*v;
  w = w0 + wt*w;
}
References sample_standard_maxwellian(), plot1_paper-2_precipitation::u, plot1_paper-2_precipitation::v, and plot1_paper-2_precipitation::w.
sample_maxwellian() [3/3]
void sample_maxwellian (double & u, double ut) inline
Definition at line 133 of file ipicmath.h.
{
  sample_standard_maxwellian(u);
  u *= ut;
}
References sample_standard_maxwellian(), and plot1_paper-2_precipitation::u.
sample_open_u_double()
static double sample_open_u_double () inline static
Definition at line 92 of file ipicmath.h.
{
  const double max_inv = 1./(double(RAND_MAX)+2);
  return (double(rand())+1)*max_inv;
}
sample_standard_maxwellian() [1/3]
void sample_standard_maxwellian (double & u) inline
Definition at line 108 of file ipicmath.h.
{
  // we sample a single component by pretending that it
  // is part of a two-dimensional joint distribution.
  const double prob = sqrt(-2.0 * log(sample_clopen_u_double()));
  const double theta = 2.0 * M_PI * sample_u_double();
  u = prob * cos(theta);
}
References sample_clopen_u_double(), sample_u_double(), plot1_paper_nBJ::theta, and plot1_paper-2_precipitation::u.
sample_standard_maxwellian() [2/3]
void sample_standard_maxwellian (double & u, double & v) inline
Definition at line 117 of file ipicmath.h.
{
  // the distribution of the magnitude of (u,v)
  // can be integrated analytically
  const double prob = sqrt(-2.0 * log(sample_clopen_u_double()));
  const double theta = 2.0 * M_PI * sample_u_double();
  u = prob * cos(theta);
  v = prob * sin(theta);
}
References sample_clopen_u_double(), sample_u_double(), plot1_paper_nBJ::theta, plot1_paper-2_precipitation::u, and plot1_paper-2_precipitation::v.
sample_standard_maxwellian() [3/3]
void sample_standard_maxwellian (double & u, double & v, double & w) inline
Definition at line 127 of file ipicmath.h.
{
  sample_standard_maxwellian(u,v);
  sample_standard_maxwellian(w);
}
References sample_standard_maxwellian(), plot1_paper-2_precipitation::u, plot1_paper-2_precipitation::v, and plot1_paper-2_precipitation::w.
sample_u_double()
double sample_u_double () inline
Definition at line 99 of file ipicmath.h.
{
  // old way
  return rand()/double(RAND_MAX);
  // faster way
  const double max_inv = 1./(double(RAND_MAX));
  return double(rand())*max_inv;
}