iPIC3DxPEACE: iPIC3D.cpp File Reference
iPIC3D.cpp File Reference
#include "MPIdata.h"
#include "iPic3D.h"
#include "debug.h"
#include "TimeTasks.h"
#include <stdio.h>
#include <sys/time.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 31 of file iPIC3D.cpp.
{
 MPIdata::init(&argc, &argv);
 {
  iPic3D::c_Solver KCode;
  KCode.Init(argc, argv);
  timeTasks.resetCycle();
  KCode.CalculateMoments();
  // start measuring time
  //struct timeval begin, end, t0_in, t1_in;
  //gettimeofday(&begin, 0);
  for (int i = KCode.FirstCycle(); i < KCode.LastCycle(); i++) {
    if (KCode.get_myrank() == 0)
      printf(" ======= Cycle %d ======= \n",i);
    //gettimeofday(&t0_in, 0);
    timeTasks.resetCycle();
    KCode.CalculateField(i);
    KCode.ParticlesMover(i);
    KCode.CalculateB();
    KCode.CalculateMoments();
    KCode.WriteOutput(i);
    // print out total time for all tasks
    timeTasks.print_cycle_times(i);
    //gettimeofday(&t1_in, 0);
    /*if (KCode.get_myrank() == 0){
      long seconds = t1_in.tv_sec - t0_in.tv_sec;
      long microseconds = t1_in.tv_usec - t0_in.tv_usec;
      double elapsed = seconds + microseconds*1e-6;
      printf("Time rank%i measured: %.5f seconds.\n", KCode.get_myrank(), elapsed);
    }*/
  }
  // Stop measuring time and calculate the elapsed time
  //gettimeofday(&end, 0);
  //long seconds = end.tv_sec - begin.tv_sec;
  //long microseconds = end.tv_usec - begin.tv_usec;
  //double elapsed = seconds + microseconds*1e-6;
  //printf("Time rank%i measured: %.5f seconds.\n", KCode.get_myrank(), elapsed);
  KCode.Finalize();
 }
 // close MPI
 MPIdata::instance().finalize_mpi();
 return 0;
}
References iPic3D::c_Solver::CalculateB(), iPic3D::c_Solver::CalculateField(), iPic3D::c_Solver::CalculateMoments(), iPic3D::c_Solver::Finalize(), MPIdata::finalize_mpi(), iPic3D::c_Solver::FirstCycle(), iPic3D::c_Solver::get_myrank(), test_new-features::i, MPIdata::init(), iPic3D::c_Solver::Init(), MPIdata::instance(), iPic3D::c_Solver::LastCycle(), iPic3D::c_Solver::ParticlesMover(), TimeTasks::print_cycle_times(), TimeTasks::resetCycle(), timeTasks, and iPic3D::c_Solver::WriteOutput().