iPIC3DxPEACE: print_global_ipic Namespace Reference
print_global_ipic Namespace Reference
Functions
def divergence (vect, resx, resy, resz)
def rotore (vect, resx, resy, resz)
Variables
string file_path = '/ccc/scratch/cont005/gen12622/lavorenf/Mercury_SaeInit/PR0/run0/data/'
string simu = 'Dipole3D'
x = np.linspace(0,10.,256)
y = np.linspace(0,8.,208)
z = y
int start = 1000
int end = 3000
int step = 200
rhoe_vtk = open_vtk_scal(file_path+simu+'_rhoe0_'+str(cycle)+'.vtk')
rhoi_vtk = open_vtk_scal(file_path+simu+'_rhoi1_'+str(cycle)+'.vtk')
Je_vtk = open_vtk_vect(file_path+simu+'_Je_'+str(cycle)+'.vtk')
Ji_vtk = open_vtk_vect(file_path+simu+'_Ji_'+str(cycle)+'.vtk')
B_vtk = open_vtk_vect(file_path+simu+'_B_'+str(cycle)+'.vtk')
E_vtk = open_vtk_vect(file_path+simu+'_E_'+str(cycle)+'.vtk')
rhoe = convert_vtk_scal(rhoe_vtk)
rhoi = convert_vtk_scal(rhoi_vtk)
Je = convert_vtk_vect(Je_vtk,'Je')
Ji = convert_vtk_vect(Ji_vtk,'Ji')
B = convert_vtk_vect(B_vtk,'B')
E = convert_vtk_vect(E_vtk,'E')
TOTrho = rhoi+rhoe
TOTJ = Ji+Je
def divB = divergence(B,1./x[1],1./y[1],1./z[1])
def rotB = rotore(B,1./x[1],1./y[1],1./z[1])
def rotE = rotore(E,1./x[1],1./y[1],1./z[1])
def divE = divergence(E,1./x[1],1./y[1],1./z[1])
Function Documentation
divergence()
def print_global_ipic.divergence (vect, resx, resy, resz)
Definition at line 19 of file print_global_ipic.py.
def divergence(vect,resx,resy,resz):
        nx,ny,nz = np.shape(vect[0][...])
        div = 0.5*resx*(np.roll(vect[0][...],-1,axis=0)-np.roll(vect[0][...],+1,axis=0))+0.5*resy*(np.roll(vect[1][...],-1,axis=1)-np.roll(vect[1][...],+1,axis=1))+0.5*resz*(np.roll(vect[2][...],-1,axis=2)-np.roll(vect[2][...],+1,axis=2))
        div[0,:,:]=0.
        div[:,0,:]=0.
        div[:,:,0]=0.
        div[nx-1,:,:]=0.
        div[:,ny-1,:]=0.
        div[:,:,nz-1]=0.
        return div
rotore()
def print_global_ipic.rotore (vect, resx, resy, resz)
Definition at line 30 of file print_global_ipic.py.
def rotore(vect,resx,resy,resz):
        nx,ny,nz = np.shape(vect[0][...])
        rot_x = 0.5*resy*(np.roll(vect[2][...],-1,axis=1)-np.roll(vect[2][...],+1,axis=1)) - 0.5*resz*(np.roll(vect[1][...],-1,axis=2)-np.roll(vect[1][...],+1,axis=2))
        rot_y =-0.5*resx*(np.roll(vect[2][...],-1,axis=0)-np.roll(vect[2][...],+1,axis=0)) + 0.5*resz*(np.roll(vect[0][...],-1,axis=2)-np.roll(vect[0][...],+1,axis=2))
        rot_z = 0.5*resx*(np.roll(vect[1][...],-1,axis=0)-np.roll(vect[1][...],+1,axis=0)) - 0.5*resy*(np.roll(vect[0][...],-1,axis=1)-np.roll(vect[0][...],+1,axis=1))
        rot_x[0,:,:]=0.
        rot_x[:,0,:]=0.
        rot_x[:,:,0]=0.
        rot_x[nx-1,:,:]=0.
        rot_x[:,ny-1,:]=0.
        rot_x[:,:,nz-1]=0.
        rot_y[0,:,:]=0.
        rot_y[:,0,:]=0.
        rot_y[:,:,0]=0.
        rot_y[nx-1,:,:]=0.
        rot_y[:,ny-1,:]=0.
        rot_y[:,:,nz-1]=0.
        rot_z[0,:,:]=0.
        rot_z[:,0,:]=0.
        rot_z[:,:,0]=0.
        rot_z[nx-1,:,:]=0.
        rot_z[:,ny-1,:]=0.
        rot_z[:,:,nz-1]=0.
        return np.array([rot_x,rot_y,rot_z])
# C'est parti!!!
cycle=start
References plot2_paper_df.range.
Variable Documentation
B
print_global_ipic.B = convert_vtk_vect(B_vtk,'B')
Definition at line 74 of file print_global_ipic.py.
Referenced by EMfields3D.initEM_rotate(), Particles3D.mover_PC_AoS_vec(), and Particles3D.mover_PC_AoS_vec_intr().
B_vtk
print_global_ipic.B_vtk = open_vtk_vect(file_path+simu+'_B_'+str(cycle)+'.vtk')
Definition at line 67 of file print_global_ipic.py.
divB
def print_global_ipic.divB = divergence(B,1./x[1],1./y[1],1./z[1])
Definition at line 86 of file print_global_ipic.py.
Referenced by EMfields3D.calculateB().
divE
def print_global_ipic.divE = divergence(E,1./x[1],1./y[1],1./z[1])
Definition at line 98 of file print_global_ipic.py.
Referenced by EMfields3D.calculateE().
E
print_global_ipic.E = convert_vtk_vect(E_vtk,'E')
Definition at line 75 of file print_global_ipic.py.
Referenced by CG(), Particles3D.mover_PC_AoS(), Particles3D.mover_PC_AoS_Relativistic(), Particles3D.mover_PC_AoS_vec(), Particles3D.mover_PC_AoS_vec_intr(), and WriteFieldsVTK().
E_vtk
print_global_ipic.E_vtk = open_vtk_vect(file_path+simu+'_E_'+str(cycle)+'.vtk')
Definition at line 68 of file print_global_ipic.py.
end
int print_global_ipic.end = 3000
Definition at line 15 of file print_global_ipic.py.
Referenced by main().
file_path
string print_global_ipic.file_path = '/ccc/scratch/cont005/gen12622/lavorenf/Mercury_SaeInit/PR0/run0/data/'
Definition at line 6 of file print_global_ipic.py.
Je
print_global_ipic.Je = convert_vtk_vect(Je_vtk,'Je')
Definition at line 72 of file print_global_ipic.py.
Je_vtk
print_global_ipic.Je_vtk = open_vtk_vect(file_path+simu+'_Je_'+str(cycle)+'.vtk')
Definition at line 65 of file print_global_ipic.py.
Ji
print_global_ipic.Ji = convert_vtk_vect(Ji_vtk,'Ji')
Definition at line 73 of file print_global_ipic.py.
Ji_vtk
print_global_ipic.Ji_vtk = open_vtk_vect(file_path+simu+'_Ji_'+str(cycle)+'.vtk')
Definition at line 66 of file print_global_ipic.py.
rhoe
print_global_ipic.rhoe = convert_vtk_scal(rhoe_vtk)
Definition at line 70 of file print_global_ipic.py.
rhoe_vtk
print_global_ipic.rhoe_vtk = open_vtk_scal(file_path+simu+'_rhoe0_'+str(cycle)+'.vtk')
Definition at line 63 of file print_global_ipic.py.
rhoi
print_global_ipic.rhoi = convert_vtk_scal(rhoi_vtk)
Definition at line 71 of file print_global_ipic.py.
rhoi_vtk
print_global_ipic.rhoi_vtk = open_vtk_scal(file_path+simu+'_rhoi1_'+str(cycle)+'.vtk')
Definition at line 64 of file print_global_ipic.py.
rotB
def print_global_ipic.rotB = rotore(B,1./x[1],1./y[1],1./z[1])
Definition at line 90 of file print_global_ipic.py.
rotE
def print_global_ipic.rotE = rotore(E,1./x[1],1./y[1],1./z[1])
Definition at line 94 of file print_global_ipic.py.
simu
string print_global_ipic.simu = 'Dipole3D'
Definition at line 8 of file print_global_ipic.py.
start
int print_global_ipic.start = 1000
Definition at line 14 of file print_global_ipic.py.
Referenced by Particles3Dcomm.apply_Xleft_BC(), Particles3Dcomm.apply_Xrght_BC(), Particles3Dcomm.apply_Yleft_BC(), Particles3Dcomm.apply_Yrght_BC(), Particles3Dcomm.apply_Zleft_BC(), Particles3Dcomm.apply_Zrght_BC(), EMfields3D.EMfields3D(), main(), and print_pcls().
step
int print_global_ipic.step = 200
Definition at line 16 of file print_global_ipic.py.
Referenced by main().
TOTJ
print_global_ipic.TOTJ = Ji+Je
Definition at line 82 of file print_global_ipic.py.
TOTrho
print_global_ipic.TOTrho = rhoi+rhoe
Definition at line 78 of file print_global_ipic.py.
x
print_global_ipic.x = np.linspace(0,10.,256)
Definition at line 10 of file print_global_ipic.py.
y
print_global_ipic.y = np.linspace(0,8.,208)
Definition at line 11 of file print_global_ipic.py.
z
print_global_ipic.z = y
Definition at line 12 of file print_global_ipic.py.