iPIC3DxPEACE: plot1_paper-2_cusps Namespace Reference
plot1_paper-2_cusps Namespace Reference
Functions
def integrator (r, ds)
Variables
data_address = sys.argv[1]
string name_simu = 'PR1-plusBz'
int cycle = 6000
float radius = 5.51
int Nbinx = 200
int Nbiny = 101
float ds = 0.2
int Nmax = 500
from_VTK = fb.from_VTK(data_address)
silent
x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
xc = from_VTK.meta['xc']
yc = from_VTK.meta['yc']
zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
dx = from_VTK.meta['dx']
dy = from_VTK.meta['dy']
dz = from_VTK.meta['dz']
Bx
By
Bz
fibo_obj
None
tar_var
fx = RegularGridInterpolator((x,y,z), Bx)
fy = RegularGridInterpolator((x,y,z), By)
fz = RegularGridInterpolator((x,y,z), Bz)
out = open('texts/output_cusps_'+name_simu+'_%i.txt'%cycle,'w')
fig = plt.figure(1)
ax = Axes3D(fig)
int phi = float(ipx)/float(Nbinx)*2.*np.pi
theta = float(ipy)/float(Nbiny)*np.pi
float rho = radius*np.sin(theta)
float x00 = xc+rho*np.cos(phi)
float y00 = yc+rho*np.sin(phi)
float z00 = zc+radius*np.cos(theta)
color
marker
fontsize
format
Function Documentation
integrator()
def plot1_paper-2_cusps.integrator (r, ds)
Definition at line 46 of file plot1_paper-2_cusps.py.
def integrator(r,ds):
    # void fields to be filled
    Bline = np.ones((Nbinx,Nbiny,Nmax,2))
    traj = np.ones((3,Nbinx,Nbiny,Nmax,2))
    ibreak = np.ones((Nbinx,Nbiny,2),dtype=int)*Nmax
    # loop on points (along phi)
    for ipx in range(0,Nbinx):
        # loop latitude (theta)
        for ipy in range(0,Nbiny):
            phi=float(ipx)/float(Nbinx)*2.*np.pi
            theta=float(ipy)/float(Nbiny)*np.pi
            rho = radius*np.sin(theta)
            x00 = xc+rho*np.cos(phi)
            y00 = yc+rho*np.sin(phi)
            z00 = zc+radius*np.cos(theta)
            # two loops forward and backward
            for il in range(2):
                # integrator field-line
                for n in range(0,Nmax):
                    if n==0:
                        x0=x00
                        y0=y00
                        z0=z00
                    point = np.array([[x0,y0,z0],[0,0,0]])
                    Bxval = fx(point)[0]
                    Byval = fy(point)[0]
                    Bzval = fz(point)[0]
                    Bval = np.sqrt(Bxval**2+Byval**2+Bzval**2)
                    Bline[ipx,ipy,n,il]=Bval
                    traj[0][ipx,ipy,n,il]=x0
                    traj[1][ipx,ipy,n,il]=y0
                    traj[2][ipx,ipy,n,il]=z0
                    x0 += Bxval/Bval*ds
                    y0 += Byval/Bval*ds
                    z0 += Bzval/Bval*ds
                    if np.sqrt((x0-xc)**2+(y0-yc)**2+(z0-zc)**2)<from_VTK.meta['R']:
                        print('Point (phi,theta)=(%.2f,%.2f) DONE --> CLOSED'%(phi,theta))
                        ibreak[ipx,ipy,il]=n
                        break
                    elif (x0>np.max(x) or x0<0 or y0>np.max(y) or y0<0 or z0>np.max(z) or z0<0):
                        print('Point (phi,theta)=(%.2f,%.2f) DONE --> OPEN'%(phi,theta))
                        ibreak[ipx,ipy,il]=-n
                        break
                ds=-ds
                print('Point (phi,theta)=(%.2f,%.2f) DONE --> CYCLE NMAX'%(phi,theta))
    return Bline, traj, ibreak
Bline,traj,ibreak = integrator(radius,ds)
# print in txt file
References fx, fy, fz, integrator(), and plot2_paper_df.range.
Referenced by integrator().
Variable Documentation
ax
plot1_paper-2_cusps.ax = Axes3D(fig)
Definition at line 116 of file plot1_paper-2_cusps.py.
Bx
plot1_paper-2_cusps.Bx
Definition at line 38 of file plot1_paper-2_cusps.py.
By
plot1_paper-2_cusps.By
Definition at line 38 of file plot1_paper-2_cusps.py.
Bz
plot1_paper-2_cusps.Bz
Definition at line 38 of file plot1_paper-2_cusps.py.
color
plot1_paper-2_cusps.color
Definition at line 127 of file plot1_paper-2_cusps.py.
cycle
plot1_paper-2_cusps.cycle = 6000
Definition at line 17 of file plot1_paper-2_cusps.py.
data_address
plot1_paper-2_cusps.data_address = sys.argv[1]
Definition at line 15 of file plot1_paper-2_cusps.py.
ds
float plot1_paper-2_cusps.ds = 0.2
Definition at line 21 of file plot1_paper-2_cusps.py.
dx
plot1_paper-2_cusps.dx = from_VTK.meta['dx']
Definition at line 33 of file plot1_paper-2_cusps.py.
dy
plot1_paper-2_cusps.dy = from_VTK.meta['dy']
Definition at line 34 of file plot1_paper-2_cusps.py.
dz
plot1_paper-2_cusps.dz = from_VTK.meta['dz']
Definition at line 35 of file plot1_paper-2_cusps.py.
fibo_obj
plot1_paper-2_cusps.fibo_obj
Definition at line 38 of file plot1_paper-2_cusps.py.
fig
plot1_paper-2_cusps.fig = plt.figure(1)
Definition at line 115 of file plot1_paper-2_cusps.py.
fontsize
plot1_paper-2_cusps.fontsize
Definition at line 142 of file plot1_paper-2_cusps.py.
format
plot1_paper-2_cusps.format
Definition at line 148 of file plot1_paper-2_cusps.py.
from_VTK
plot1_paper-2_cusps.from_VTK = fb.from_VTK(data_address)
Definition at line 25 of file plot1_paper-2_cusps.py.
fx
plot1_paper-2_cusps.fx = RegularGridInterpolator((x,y,z), Bx)
Definition at line 41 of file plot1_paper-2_cusps.py.
Referenced by integrator().
fy
plot1_paper-2_cusps.fy = RegularGridInterpolator((x,y,z), By)
Definition at line 42 of file plot1_paper-2_cusps.py.
Referenced by integrator().
fz
plot1_paper-2_cusps.fz = RegularGridInterpolator((x,y,z), Bz)
Definition at line 43 of file plot1_paper-2_cusps.py.
Referenced by integrator().
marker
plot1_paper-2_cusps.marker
Definition at line 127 of file plot1_paper-2_cusps.py.
name_simu
string plot1_paper-2_cusps.name_simu = 'PR1-plusBz'
Definition at line 16 of file plot1_paper-2_cusps.py.
Nbinx
int plot1_paper-2_cusps.Nbinx = 200
Definition at line 19 of file plot1_paper-2_cusps.py.
Nbiny
int plot1_paper-2_cusps.Nbiny = 101
Definition at line 20 of file plot1_paper-2_cusps.py.
Nmax
int plot1_paper-2_cusps.Nmax = 500
Definition at line 22 of file plot1_paper-2_cusps.py.
None
plot1_paper-2_cusps.None
Definition at line 38 of file plot1_paper-2_cusps.py.
out
plot1_paper-2_cusps.out = open('texts/output_cusps_'+name_simu+'_%i.txt'%cycle,'w')
Definition at line 111 of file plot1_paper-2_cusps.py.
phi
int plot1_paper-2_cusps.phi = float(ipx)/float(Nbinx)*2.*np.pi
Definition at line 119 of file plot1_paper-2_cusps.py.
radius
float plot1_paper-2_cusps.radius = 5.51
Definition at line 18 of file plot1_paper-2_cusps.py.
rho
float plot1_paper-2_cusps.rho = radius*np.sin(theta)
Definition at line 121 of file plot1_paper-2_cusps.py.
silent
plot1_paper-2_cusps.silent
Definition at line 26 of file plot1_paper-2_cusps.py.
tar_var
plot1_paper-2_cusps.tar_var
Definition at line 38 of file plot1_paper-2_cusps.py.
theta
plot1_paper-2_cusps.theta = float(ipy)/float(Nbiny)*np.pi
Definition at line 120 of file plot1_paper-2_cusps.py.
x
plot1_paper-2_cusps.x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
Definition at line 27 of file plot1_paper-2_cusps.py.
x00
plot1_paper-2_cusps.x00 = xc+rho*np.cos(phi)
Definition at line 122 of file plot1_paper-2_cusps.py.
xc
plot1_paper-2_cusps.xc = from_VTK.meta['xc']
Definition at line 30 of file plot1_paper-2_cusps.py.
y
plot1_paper-2_cusps.y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
Definition at line 28 of file plot1_paper-2_cusps.py.
y00
plot1_paper-2_cusps.y00 = yc+rho*np.sin(phi)
Definition at line 123 of file plot1_paper-2_cusps.py.
yc
plot1_paper-2_cusps.yc = from_VTK.meta['yc']
Definition at line 31 of file plot1_paper-2_cusps.py.
z
plot1_paper-2_cusps.z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
Definition at line 29 of file plot1_paper-2_cusps.py.
z00
plot1_paper-2_cusps.z00 = zc+radius*np.cos(theta)
Definition at line 124 of file plot1_paper-2_cusps.py.
zc
plot1_paper-2_cusps.zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
Definition at line 32 of file plot1_paper-2_cusps.py.