iPIC3DxPEACE: include/asserts.h File Reference
asserts.h File Reference
#include <cstdlib>
#include <cstdio>
Macros
#define MAX_ASSERT_LEVEL 2
#define dassert_fileLine(e, file, line, func)
#define USE_GCC_OPTIMIZATION
#define dassert_(e) (__builtin_expect(!(e), 0) ? dassert_fileLine (#e, __FILE__, __LINE__, __func__) : (void)0)
#define assert1 dassert_
#define assert_printf1 dassert_printf
#define assert2 dassert_
#define assert_printf2 dassert_printf
#define assert_printf dassert_printf
#define assert3(e)
#define assert_printf3(args...)
#define declare_assert_errmsg(t1, t2)
#define builtin_expect(a, b) __builtin_expect(a,b)
#define assert_not_almost_eq(lhs, rhs, tol)
#define assert_almost_eq(lhs, rhs, tol)
#define assert_divides(lhs, rhs)
#define assert_streq(lhs, rhs)
#define assert_op(op, lhs, rhs)
#define assert_isfinite(a)
#define report_nan(a)
#define assert_isnum(a)
#define assert_eq(a, b) assert_op(==,a,b);
#define assert_ne(a, b) assert_op(!=,a,b);
#define assert_gt(a, b) assert_op(>,a,b);
#define assert_lt(a, b) assert_op(<,a,b);
#define assert_ge(a, b) assert_op(>=,a,b);
#define assert_le(a, b) assert_op(<=,a,b);
Functions
void eprintf_fileLine (FILE *fptr, const char *type, const char *func, const char *file, int line_number, const char *format,...)
declare_assert_errmsg (double, double)
declare_assert_errmsg (size_t, size_t)
declare_assert_errmsg (int, size_t)
declare_assert_errmsg (size_t, int)
declare_assert_errmsg (int, int)
declare_assert_errmsg (long long, long long)
declare_assert_errmsg (const char *, const char *)
int fcmp (double x1, double x2, double epsilon)
Macro Definition Documentation
assert1
#define assert1 dassert_
Definition at line 93 of file asserts.h.
assert2
#define assert2 dassert_
Definition at line 100 of file asserts.h.
assert3
#define assert3 (e)
Definition at line 114 of file asserts.h.
assert_almost_eq
#define assert_almost_eq (lhs, rhs, tol)
Value:
  (builtin_expect(fcmp(lhs, rhs, tol),0) \
   ? assert_error(__FILE__, __LINE__, __func__, " =~= ", #lhs, #rhs, lhs, rhs) \
   : (void)0)
Definition at line 152 of file asserts.h.
assert_divides
#define assert_divides (lhs, rhs)
Value:
  (builtin_expect(rhs%lhs,0) \
   ? assert_error(__FILE__, __LINE__, __func__, "(divides)", #lhs, #rhs, lhs, rhs) \
   : (void)0)
Definition at line 160 of file asserts.h.
assert_eq
#define assert_eq (a, b) assert_op(==,a,b);
Definition at line 186 of file asserts.h.
assert_ge
#define assert_ge (a, b) assert_op(>=,a,b);
Definition at line 190 of file asserts.h.
assert_gt
#define assert_gt (a, b) assert_op(>,a,b);
Definition at line 188 of file asserts.h.
assert_isfinite
#define assert_isfinite (a)
Value:
  (builtin_expect(!(a>=-DBL_MAX && a<=DBL_MAX),0) ? \
   (void)(printf("ERROR: file %s, line %d, function %s:\n\t: %s = %24.16e " \
       "is not finite\n", __FILE__, __LINE__, __func__,#a,a),abort()) : (void) 0)
Definition at line 173 of file asserts.h.
assert_isnum
#define assert_isnum (a)
Value:
  (builtin_expect(!(a==a),0) ? \
   (void)(printf("ERROR: file %s, line %d, function %s:\n\t: %s = %24.16e " \
       "is nan\n", __FILE__, __LINE__, __func__,#a,a),abort()) : (void) 0)
Definition at line 182 of file asserts.h.
assert_le
#define assert_le (a, b) assert_op(<=,a,b);
Definition at line 191 of file asserts.h.
assert_lt
#define assert_lt (a, b) assert_op(<,a,b);
Definition at line 189 of file asserts.h.
assert_ne
#define assert_ne (a, b) assert_op(!=,a,b);
Definition at line 187 of file asserts.h.
assert_not_almost_eq
#define assert_not_almost_eq (lhs, rhs, tol)
Value:
  (fcmp(lhs, rhs, tol) \
   ? (void)0 \
   : assert_error(__FILE__, __LINE__, __func__, " !=~= ", #lhs, #rhs, lhs, rhs))
Definition at line 148 of file asserts.h.
assert_op
#define assert_op (op, lhs, rhs)
Value:
  (builtin_expect(!(lhs op rhs),0) \
   ? assert_error(__FILE__, __LINE__, __func__, #op, #lhs, #rhs, lhs, rhs) \
   : (void)0)
Definition at line 168 of file asserts.h.
assert_printf
#define assert_printf dassert_printf
Definition at line 103 of file asserts.h.
assert_printf1
#define assert_printf1 dassert_printf
Definition at line 94 of file asserts.h.
assert_printf2
#define assert_printf2 dassert_printf
Definition at line 102 of file asserts.h.
assert_printf3
#define assert_printf3 (args...)
Definition at line 115 of file asserts.h.
assert_streq
#define assert_streq (lhs, rhs)
Value:
  (builtin_expect(strcmp(lhs,rhs),0) \
   ? assert_error(__FILE__, __LINE__, __func__, "==", #lhs, #rhs, lhs, rhs) \
   : (void)0)
Definition at line 164 of file asserts.h.
builtin_expect
#define builtin_expect (a, b) __builtin_expect(a,b)
Definition at line 145 of file asserts.h.
dassert_
#define dassert_ (e) (__builtin_expect(!(e), 0) ? dassert_fileLine (#e, __FILE__, __LINE__, __func__) : (void)0)
Definition at line 86 of file asserts.h.
dassert_fileLine
#define dassert_fileLine (e, file, line, func)
Value:
  (void)(eprintf_fileLine(stdout,"ERROR", func, file, line, \
           "\n\tfailed assertion: (%s)", e), abort())
Definition at line 64 of file asserts.h.
declare_assert_errmsg
#define declare_assert_errmsg (t1, t2)
Value:
  void assert_error(const char* file, int line, const char* func, \
      const char* op, const char* lhs_str, const char* rhs_str, \
      t1 lhs, t2 rhs);
Definition at line 124 of file asserts.h.
MAX_ASSERT_LEVEL
#define MAX_ASSERT_LEVEL 2
Definition at line 33 of file asserts.h.
report_nan
#define report_nan (a)
Value:
  (builtin_expect(!(a==a),0) ? \
   (printf("error: file %s, line %d, function %s:\n\t: %s = %24.16e " \
           "is nan\n", __FILE__, __LINE__, __func__,#a,a),1) : 0)
Definition at line 178 of file asserts.h.
USE_GCC_OPTIMIZATION
#define USE_GCC_OPTIMIZATION
Definition at line 71 of file asserts.h.
Function Documentation
declare_assert_errmsg() [1/7]
declare_assert_errmsg (const char * , const char *)
declare_assert_errmsg() [2/7]
declare_assert_errmsg (double , double)
declare_assert_errmsg() [3/7]
declare_assert_errmsg (int , int)
declare_assert_errmsg() [4/7]
declare_assert_errmsg (int , size_t)
declare_assert_errmsg() [5/7]
declare_assert_errmsg (long long , long long)
declare_assert_errmsg() [6/7]
declare_assert_errmsg (size_t , int)
declare_assert_errmsg() [7/7]
declare_assert_errmsg (size_t , size_t)
eprintf_fileLine()
void eprintf_fileLine (FILE * fptr, const char * type, const char * func, const char * file, int line_number, const char * format, ...)
a more verbose version of fprintf_fileLine for use in warnings and error messages
Definition at line 79 of file errors.cpp.
{
  // writing directly to fptr would avoid limiting the length
  // of the output string, but by first writing to a string
  // we achieve thread safety.
  //
  // write the message to a string.
  //
  const int maxchars = 1024;
  char error_msg[maxchars+2];
  // identify the process and thread
  char process_thread_str[50];
  #ifndef NO_MPI
    #ifdef _OPENMP
      snprintf(process_thread_str, 50, ", process %d, thread %d",
        MPIdata::get_rank(), omp_get_thread_num());
    #else
      snprintf(process_thread_str, 50, ", process %d",
        MPIdata::get_rank());
    #endif
  #else
    #ifdef _OPENMP
      snprintf(process_thread_str, 50, ", thread %d",
        omp_get_thread_num());
    #else
      sprintf(process_thread_str, "");
    #endif
  #endif
  char *sptr = error_msg;
  int chars_so_far=0;
  va_list args;
  va_start(args, format);
  chars_so_far = snprintf(sptr, maxchars,
    "%s in method %s(), file %s, line %d%s:\n\t",
    type,
    func, file, // my_basename(file),
    line_number, process_thread_str);
  /* print out remainder of message */
  chars_so_far += vsnprintf(sptr+chars_so_far, maxchars-chars_so_far, format, args);
  va_end(args);
  sprintf(sptr+chars_so_far, "\n");
  // print the message
  fflush(fptr);
    // #pragma omp critical // need this?
  { fprintf(fptr,"%s",error_msg); }
  fflush(fptr);
  abort();
References print_planet_main::args, plot1_paper_nBJ::format, MPIdata::get_rank(), and omp_get_thread_num().
Referenced by assert_error().
fcmp()
int fcmp (double x1, double x2, double epsilon)
Definition at line 137 of file asserts.cpp.
{
  double diff = x1-x2;
  if(diff>epsilon) return 1;
  if(diff<-epsilon) return -1;
  return 0;
  // the code below was failing for some reason. -eaj
  int exponent;
  double delta;
  double difference;
  /* Get exponent(max(fabs(x1), fabs(x2))) and store it in exponent. */
  /* If neither x1 nor x2 is 0, */
  /* this is equivalent to max(exponent(x1), exponent(x2)). */
  /* If either x1 or x2 is 0, its exponent returned by frexp would be 0, */
  /* which is much larger than the exponents of numbers close to 0 in */
  /* magnitude. But the exponent of 0 should be less than any number */
  /* whose magnitude is greater than 0. */
  /* So we only want to set exponent to 0 if both x1 and */
  /* x2 are 0. Hence, the following works for all x1 and x2. */
  frexp(fabs(x1) > fabs(x2) ? x1 : x2, &exponent);
  /* Do the comparison. */
  /* delta = epsilon * pow(2, exponent) */
  /* Form a neighborhood around x2 of size delta in either direction. */
  /* If x1 is within this delta neighborhood of x2, x1 == x2. */
  /* Otherwise x1 > x2 or x1 < x2, depending on which side of */
  /* the neighborhood x1 is on. */
  delta = ldexp(epsilon, exponent);
  difference = x1 - x2;
  if (difference > delta)
    return 1; /* x1 > x2 */
  else if (difference < -delta)
    return -1;  /* x1 < x2 */
  else /* -delta <= difference <= delta */
    return 0;  /* x1 == x2 */
}