iPIC3DxPEACE: post-process/post-process/include/Basic.h File Reference
Basic.h File Reference
#include "arraysfwd.h"
#include <math.h>
Functions
double extrapolate (double f[7], double weig[3], int dir[6])
Basic operations defined.
double dotP (const double *vect1, const double *vect2, int n, MPI_Comm *comm)
method to calculate the parallel dot product with vect1, vect2 having the ghost cells
double dot (const double *vect1, const double *vect2, int n)
method to calculate dot product
double norm2 (const double *const *vect, int nx, int ny)
method to calculate the square norm of a vector
double norm2 (const arr3_double vect, int nx, int ny)
method to calculate the square norm of a vector
double norm2 (const double *vect, int nx)
method to calculate the square norm of a vector
double normP (const double *vect, int n, MPI_Comm *comm)
method to calculate the parallel dot product
void sub (double *res, const double *vect1, const double *vect2, int n)
method to calculate the difference of two vectors
void sum (double *vect1, const double *vect2, int n)
method to calculate the sum of two vectors vector1 = vector1 + vector2
void sum (arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to calculate the sum of two vectors vector1 = vector1 + vector2
void sum (arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate the sum of two vectors vector1 = vector1 + vector2
void sum (arr3_double vect1, const arr4_double vect2, int nx, int ny, int nz, int ns)
method to calculate the sum of two vectors vector1 = vector1 + vector2
void sum (arr3_double vect1, const arr4_double vect2, int nx, int ny, int ns)
method to calculate the sum of two vectors vector1 = vector1 + vector2
void sub (arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to calculate the subtraction of two vectors vector1 = vector1 - vector2
void sub (arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate the subtraction of two vectors vector1 = vector1 - vector2
void sum4 (arr3_double vect1, double alfa, const arr3_double vect2, double beta, const arr3_double vect3, double gamma, const arr3_double vect4, double delta, const arr3_double vect5, int nx, int ny, int nz)
method to sum 4 vectors vector1 = alfa*vector1 + beta*vector2 + gamma*vector3 + delta*vector4
void scale (double *vect, double alfa, int n)
method to calculate the scalar-vector product
void scale (arr3_double vect, double alfa, int nx, int ny)
method to calculate the scalar-vector product
void scale (arr3_double vect, double alfa, int nx, int ny, int nz)
method to calculate the scalar-vector product
void scale (arr3_double vect1, const arr3_double vect2, double alfa, int nx, int ny, int nz)
‍** method to calculate the scalar product *‍/
void scale (arr3_double vect1, const arr3_double vect2, double alfa, int nx, int ny)
method to calculate the scalar-vector product
void scale (double *vect1, const double *vect2, double alfa, int n)
method to calculate the scalar-vector product
void addscale (double alfa, arr3_double vect1, arr3_double vect2, const arr3_double vect3, int nx, int ny, int nz)
method to calculate vector1 = vector1 + alfa*vector2
void addscale (double alfa, arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
void addscale (double alfa, double vect1[][2][2], double vect2[][2][2], int nx, int ny, int nz)
add scale for weights
void addscale (double alfa, arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate vector1 = vector1 + alfa*vector2
void addscale (double alfa, double *vect1, const double *vect2, int n)
method to calculate vector1 = vector1 + alfa*vector2
void addscale (double alfa, double beta, double *vect1, const double *vect2, int n)
method to calculate vector1 = beta*vector1 + alfa*vector2
void addscale (double alfa, double beta, arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to calculate vector1 = beta*vector1 + alfa*vector2
void addscale (double alfa, double beta, arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate vector1 = beta*vector1 + alfa*vector2
void sumscalprod (double ***vect1, double alfa, double ***vect2, double ***vect3, int nx, int ny, int nz)
method to calculate v1 = v1 + alpha * v2 * v3
void scaleandsum (arr3_double vect1, double alfa, double beta, const arr3_double vect2, const arr3_double vect3, int nx, int ny, int nz)
method to calculate vector1 = alfa*vector2 + beta*vector3
void scaleandsum (arr3_double vect1, double alfa, double beta, const arr4_double vect2, const arr3_double vect3, int ns, int nx, int ny, int nz)
method to calculate vector1 = alfa*vector2 + beta*vector3 with vector2 depending on species
void prod (arr3_double vect1, double alfa, const arr4_double vect2, int ns, const arr3_double vect3, int nx, int ny, int nz)
method to calculate vector1 = alfa*vector2*vector3 with vector2 depending on species
void div (arr3_double vect1, double alfa, const arr3_double vect2, int nx, int ny, int nz)
method to calculate vect1 = vect2/alfa
void prod6 (arr3_double vect1, const arr3_double vect2, const arr3_double vect3, const arr3_double vect4, const arr3_double vect5, const arr3_double vect6, const arr3_double vect7, int nx, int ny, int nz)
void proddiv (arr3_double vect1, const arr3_double vect2, double alfa, const arr3_double vect3, const arr3_double vect4, const arr3_double vect5, const arr3_double vect6, double beta, const arr3_double vect7, const arr3_double vect8, double gamma, const arr3_double vect9, int nx, int ny, int nz)
method used for calculating PI
void neg (arr3_double vect, int nx, int ny, int nz)
method to calculate the opposite of a vector
void neg (arr3_double vect, int nx, int ny)
method to calculate the opposite of a vector
void neg (arr3_double vect, int nx)
method to calculate the opposite of a vector
void neg (double *vect, int n)
method to calculate the opposite of a vector
void eq (arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to set equal two vectors
void eq (arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to set equal two vectors
void eq (arr4_double vect1, const arr3_double vect2, int nx, int ny, int is)
method to set equal two vectors
void eq (arr4_double vect1, const arr3_double vect2, int nx, int ny, int nz, int is)
method to set equal two vectors
void eq (double *vect1, double *vect2, int n)
void eqValue (double value, arr3_double vect, int nx, int ny, int nz)
method to set a vector to a Value
void eqValue (double value, arr3_double vect, int nx, int ny)
method to set a vector to a Value
void eqValue (double value, arr3_double vect, int nx)
method to set a vector to a Value
void eqValue (double value, double *vect, int n)
method to set a vector to a Value
void putColumn (double **Matrix, double *vect, int column, int n)
method to put a column in a matrix 2D
void getColumn (double *vect, double **Matrix, int column, int n)
method to get a column in a matrix 2D
void getRidGhost (double **out, double **in, int nx, int ny)
method to get rid of the ghost cells
double eps ()
method to calculate the epsilon machine
void cross_product (double a1, double a2, double a3, double b1, double b2, double b3, double *c)
method to calculate cross product of two vectors C= A x B
void loopX (double *b, double z, double x, double y, double a, double zc, double xc, double yc, double m)
void loopY (double *b, double y, double z, double x, double a, double yc, double zc, double xc, double m)
void loopZ (double *b, double x, double y, double z, double a, double xc, double yc, double zc, double m)
Function Documentation
addscale() [1/8]
void addscale (double alfa, arr3_double vect1, arr3_double vect2, const arr3_double vect3, int nx, int ny, int nz)
method to calculate vector1 = vector1 + alfa*vector2
Definition at line 234 of file Basic.cpp.
{
          for (int i = 0; i < nx; i++)
            for (int j = 0; j < ny; j++)
              for (int k = 0; k < nz; k++)
                vect3.fetch(i,j,k) = vect1.get(i,j,k) + alfa * vect2.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
addscale() [2/8]
void addscale (double alfa, arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate vector1 = vector1 + alfa*vector2
Definition at line 255 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(i,j,0) += alfa * vect2.get(i,j,0);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
addscale() [3/8]
void addscale (double alfa, arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
Definition at line 240 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = vect1.get(i,j,k) + alfa * vect2.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
addscale() [4/8]
void addscale (double alfa, double * vect1, const double * vect2, int n)
method to calculate vector1 = vector1 + alfa*vector2
Definition at line 261 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    vect1[i] += alfa * vect2[i];
}
References test_new-features::i.
addscale() [5/8]
void addscale (double alfa, double beta, arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate vector1 = beta*vector1 + alfa*vector2
Definition at line 283 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(i,j,0) = beta * vect1.get(i,j,0) + alfa * vect2.get(i,j,0);
}
References plot3_paper-2_cross-sec::beta, iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
addscale() [6/8]
void addscale (double alfa, double beta, arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to calculate vector1 = beta*vector1 + alfa*vector2
Definition at line 273 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++) {
        vect1.fetch(i,j,k) = beta * vect1.get(i,j,k) + alfa * vect2.get(i,j,k);
      }
}
References plot3_paper-2_cross-sec::beta, iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
addscale() [7/8]
void addscale (double alfa, double beta, double * vect1, const double * vect2, int n)
method to calculate vector1 = beta*vector1 + alfa*vector2
Definition at line 267 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    vect1[i] = vect1[i] * beta + alfa * vect2[i];
}
References plot3_paper-2_cross-sec::beta, and test_new-features::i.
addscale() [8/8]
void addscale (double alfa, double vect1[][2][2], double vect2[][2][2], int nx, int ny, int nz)
add scale for weights
Definition at line 247 of file Basic.cpp.
{
  for (int i = 0; i < nx; i++)
    for (int j = 0; j < ny; j++)
      for (int k = 0; k < nz; k++)
        vect1[i][j][k] = vect1[i][j][k] + alfa * vect2[i][j][k];
}
References test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
cross_product()
void cross_product (double a1, double a2, double a3, double b1, double b2, double b3, double * c) inline
method to calculate cross product of two vectors C= A x B
Definition at line 191 of file Basic.h.
{
  c[0] = a2 * b3 - a3 * b2;
  c[1] = a3 * b1 - a1 * b3;
  c[2] = a1 * b2 - a2 * b1;
}
References plot2_paper_df::c.
div()
void div (arr3_double vect1, double alfa, const arr3_double vect2, int nx, int ny, int nz)
method to calculate vect1 = vect2/alfa
Definition at line 321 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = vect2.get(i,j,k) / alfa;
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
dot()
double dot (const double * vect1, const double * vect2, int n)
method to calculate dot product
Definition at line 60 of file Basic.cpp.
{
  double result = 0;
  for (int i = 0; i < n; i++)
    result += vect1[i] * vect2[i];
  return (result);
}
References test_new-features::i.
dotP()
double dotP (const double * vect1, const double * vect2, int n, MPI_Comm * comm)
method to calculate the parallel dot product with vect1, vect2 having the ghost cells
Definition at line 50 of file Basic.cpp.
{
  double result = 0;
  double local_result = 0;
  for (register int i = 0; i < n; i++)
    local_result += vect1[i] * vect2[i];
  MPI_Allreduce(&local_result, &result, 1, MPI_DOUBLE, MPI_SUM, *comm);
  return (result);
}
References test_new-features::i.
eps()
double eps () inline
method to calculate the epsilon machine
Definition at line 173 of file Basic.h.
                    {
  double eps;
  int i = 1;
  double num = 1;
  double newsum = 1;
  double oldsum = 1;
  while (true) {
    num = num / (2 * i);
    newsum += num;
    if (newsum == oldsum)
      break;
    oldsum = newsum;
    i++;
  }
  eps = num * 2;
  return (eps);
}
References eps(), and test_new-features::i.
eq() [1/5]
void eq (arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to set equal two vectors
Definition at line 379 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(i,j,0) = vect2.get(i,j,0);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
eq() [2/5]
void eq (arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to set equal two vectors
Definition at line 371 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = vect2.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
eq() [3/5]
void eq (arr4_double vect1, const arr3_double vect2, int nx, int ny, int is)
method to set equal two vectors
Definition at line 387 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(is,i,j,0) = vect2.get(i,j,0);
}
References iPic3D::array_ref4< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
eq() [4/5]
void eq (arr4_double vect1, const arr3_double vect2, int nx, int ny, int nz, int is)
method to set equal two vectors
Definition at line 394 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(is,i,j,k) = vect2.get(i,j,k);
}
References iPic3D::array_ref4< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
eq() [5/5]
void eq (double * vect1, double * vect2, int n) inline
Definition at line 151 of file Basic.h.
{
  for (register int i = 0; i < n; i++)
    vect1[i] = vect2[i];
}
References test_new-features::i.
eqValue() [1/4]
void eqValue (double value, arr3_double vect, int nx)
method to set a vector to a Value
Definition at line 425 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    vect.fetch(i,0,0) = value;
}
References iPic3D::array_ref3< type >::fetch(), test_new-features::i, and test_to2D::nx.
eqValue() [2/4]
void eqValue (double value, arr3_double vect, int nx, int ny)
method to set a vector to a Value
Definition at line 418 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect.fetch(i,j,0) = value;
}
References iPic3D::array_ref3< type >::fetch(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
eqValue() [3/4]
void eqValue (double value, arr3_double vect, int nx, int ny, int nz)
method to set a vector to a Value
Definition at line 403 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect.fetch(i,j,k) = value;
}
References iPic3D::array_ref3< type >::fetch(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
eqValue() [4/4]
void eqValue (double value, double * vect, int n)
method to set a vector to a Value
Definition at line 431 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    vect[i] = value;
}
References test_new-features::i.
extrapolate()
double extrapolate (double f[7], double weig[3], int dir[6])
Basic operations defined.
This library provides methods to calculate:
dot product of two vectors
square norm of a vector
norm of a vector
difference of two vector
scalar-vector product
vector1 = vector1 + alfa*vector2
vector1 = beta*vector1 + alfa*vector2
opposite of a vector
Date
Fri Jun 4 2007
Author
Stefano Markidis, Giovanni Lapenta
Version
2.0 method to calculate extrapolation of 6 neighbours cells values to the outermost cell
Basic operations defined.
Definition at line 30 of file Basic.cpp.
{
  double dxf, dyf, dzf,den,result;
  double f_closer=0.0;
  int ndir[6];
  for (int i=0; i<6; i++){
    ndir[i]=1-dir[i];
    //f_closer+=(dir[i]*f[i+1]);
    f_closer+=f[i+1];
  }
  f_closer = f_closer/6.;
  //dxf = (f[1]*ndir[0]-f[2]*ndir[1])*weig[0];
  //dyf = (f[3]*ndir[2]-f[4]*ndir[3])*weig[1];
  //dzf = (f[5]*ndir[4]-f[6]*ndir[5])*weig[2];
  //den = 1.0+weig[0]*dir[0]-weig[0]*dir[1]+weig[1]*dir[2]-weig[1]*dir[3]+weig[2]*dir[4]-weig[2]*dir[5];
  //result = (f[0]+dxf+dyf+dxf)/den;
  result = f_closer;
  return result;
}
References test_new-features::i.
getColumn()
void getColumn (double * vect, double ** Matrix, int column, int n)
method to get a column in a matrix 2D
Definition at line 442 of file Basic.cpp.
{
  for (int i = 0; i < n; i++)
    vect[i] = Matrix[i][column];
}
References test_new-features::i.
getRidGhost()
void getRidGhost (double ** out, double ** in, int nx, int ny) inline
method to get rid of the ghost cells
Definition at line 447 of file Basic.cpp.
{
  for (register int i = 1; i < nx - 1; i++)
    for (register int j = 1; j < ny - 1; j++)
      out[i - 1][j - 1] = in[i][j];
}
References test_new-features::i, test_to2D::nx, test_to2D::ny, and plot_Jpar-planet::out.
loopX()
void loopX (double * b, double z, double x, double y, double a, double zc, double xc, double yc, double m)
Definition at line 453 of file Basic.cpp.
{
  double r = sqrt((x-xc)*(x-xc)+(y-yc)*(y-yc)+(z-zc)*(z-zc));
  double theta = acos((z-zc+1e-10)/(r+1e-10));
  double phi = atan2(y-yc,x-xc);
  //double Rho = r * sin(theta);
  double Rho = sqrt((x-xc)*(x-xc)+(y-yc)*(y-yc));
  double Alpha = Rho/a;
  double Beta = (z-zc)/a;
  double Gamma = (z-zc+1e-10)/(Rho+1e-10);
  double Q = ((1 + Alpha)*(1 + Alpha) + Beta*Beta);
  double k = sqrt(4*Alpha/Q);
  double B0 = m / (2*a); //m * (C_LIGHT * MU0)/(2*a*a*a*M_PI);
  int err = 0;
  double Bz = B0*(EllipticE(k,err)*(1-Alpha*Alpha-Beta*Beta)/(Q-4*Alpha)+EllipticF(k,err))/(M_PI*sqrt(Q));
  double BRho = B0*Gamma*(EllipticE(k,err)*(1+Alpha*Alpha+Beta*Beta)/(Q-4*Alpha)-EllipticF(k,err))/(M_PI*sqrt(Q));
  if (err)
    eprintf("Err came back :%d", err);
  if ( isnan(BRho) )
    BRho = 0;
  if ( isnan(Bz) )
    Bz = 0;
  double Bx = BRho * cos(phi);
  double By = BRho * sin(phi);
  //for debugging
  /*cout << "\n\nAt (" << x << "," << y << "," << z << "), the field is :" << endl;
    cout << "Bx: " << Bx << " T" << endl;
    cout << "By: " << By << " T" << endl;
    cout << "Bz: " << Bz << " T" << endl;
    cout << "BRho: " << BRho << " T" << endl;*/
  b[1] = Bx;
  b[2] = By;
  b[0] = Bz;
}
References plot4_Blines::Bx, plot4_Blines::By, plot4_Blines::Bz, EllipticE, EllipticF, eprintf, plot5_paper_in-situ-data1::phi, plot1_paper_nBJ::theta, plot_Jpar-planet::x, plot_Jpar-planet::xc, plot_Jpar-planet::y, plot_Jpar-planet::yc, plot_Jpar-planet::z, and plot_Jpar-planet::zc.
loopY()
void loopY (double * b, double y, double z, double x, double a, double yc, double zc, double xc, double m)
Definition at line 497 of file Basic.cpp.
{
  double r = sqrt((x-xc)*(x-xc)+(y-yc)*(y-yc)+(z-zc)*(z-zc));
  double theta = acos((z-zc+1e-10)/(r+1e-10));
  double phi = atan2(y-yc,x-xc);
  //double Rho = r * sin(theta);
  double Rho = sqrt((x-xc)*(x-xc)+(y-yc)*(y-yc));
  double Alpha = Rho/a;
  double Beta = (z-zc)/a;
  double Gamma = (z-zc+1e-10)/(Rho+1e-10);
  double Q = ((1 + Alpha)*(1 + Alpha) + Beta*Beta);
  double k = sqrt(4*Alpha/Q);
  double B0 = m / (2*a); //m * (C_LIGHT * MU0)/(2*a*a*a*M_PI);
  int err = 0;
  double Bz = B0*(EllipticE(k,err)*(1-Alpha*Alpha-Beta*Beta)/(Q-4*Alpha)+EllipticF(k,err))/(M_PI*sqrt(Q));
  double BRho = B0*Gamma*(EllipticE(k,err)*(1+Alpha*Alpha+Beta*Beta)/(Q-4*Alpha)-EllipticF(k,err))/(M_PI*sqrt(Q));
  if (err)
    eprintf("Err came back :%d", err);
  if ( isnan(BRho) )
    BRho = 0;
  if ( isnan(Bz) )
    Bz = 0;
  double Bx = BRho * cos(phi);
  double By = BRho * sin(phi);
  //for debugging
  /*cout << "\n\nAt (" << x << "," << y << "," << z << "), the field is :" << endl;
    cout << "Bx: " << Bx << " T" << endl;
    cout << "By: " << By << " T" << endl;
    cout << "Bz: " << Bz << " T" << endl;
    cout << "BRho: " << BRho << " T" << endl;*/
  b[2] = Bx;
  b[0] = By;
  b[1] = Bz;
}
References plot4_Blines::Bx, plot4_Blines::By, plot4_Blines::Bz, EllipticE, EllipticF, eprintf, plot5_paper_in-situ-data1::phi, plot1_paper_nBJ::theta, plot_Jpar-planet::x, plot_Jpar-planet::xc, plot_Jpar-planet::y, plot_Jpar-planet::yc, plot_Jpar-planet::z, and plot_Jpar-planet::zc.
loopZ()
void loopZ (double * b, double x, double y, double z, double a, double xc, double yc, double zc, double m)
Definition at line 541 of file Basic.cpp.
{
  double r = sqrt((x-xc)*(x-xc)+(y-yc)*(y-yc)+(z-zc)*(z-zc));
  double theta = acos((z-zc+1e-10)/(r+1e-10));
  double phi = atan2(y-yc,x-xc);
  double Rho = sqrt((x-xc)*(x-xc)+(y-yc)*(y-yc));
  double Alpha = Rho/a;
  double Beta = (z-zc)/a;
  double Gamma = (z-zc+1e-10)/(Rho+1e-10);
  double Q = ((1 + Alpha)*(1 + Alpha) + Beta*Beta);
  double k = sqrt(4*Alpha/Q);
  double B0 = m / (2*a); //m * (C_LIGHT * MU0)/(2*a*a*a*M_PI);
  int err = 0;
  double Bz = B0*(EllipticE(k,err)*(1-Alpha*Alpha-Beta*Beta)/(Q-4*Alpha)+EllipticF(k,err))/(M_PI*sqrt(Q));
  double BRho = B0*Gamma*(EllipticE(k,err)*(1+Alpha*Alpha+Beta*Beta)/(Q-4*Alpha)-EllipticF(k,err))/(M_PI*sqrt(Q));
  if (err)
    eprintf("Err came back :%d", err);
  if ( isnan(BRho) )
    BRho = 0;
  if ( isnan(Bz) )
    Bz = 0;
  double Bx = BRho * cos(phi);
  double By = BRho * sin(phi);
  b[0] = Bx;
  b[1] = By;
  b[2] = Bz;
}
References plot4_Blines::Bx, plot4_Blines::By, plot4_Blines::Bz, EllipticE, EllipticF, eprintf, plot5_paper_in-situ-data1::phi, plot1_paper_nBJ::theta, plot_Jpar-planet::x, plot_Jpar-planet::xc, plot_Jpar-planet::y, plot_Jpar-planet::yc, plot_Jpar-planet::z, and plot_Jpar-planet::zc.
neg() [1/4]
void neg (arr3_double vect, int nx)
method to calculate the opposite of a vector
Definition at line 359 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    vect.fetch(i,0,0) = -vect.get(i,0,0);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, and test_to2D::nx.
neg() [2/4]
void neg (arr3_double vect, int nx, int ny)
method to calculate the opposite of a vector
Definition at line 353 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect.fetch(i,j,0) = -vect.get(i,j,0);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
neg() [3/4]
void neg (arr3_double vect, int nx, int ny, int nz)
method to calculate the opposite of a vector
Definition at line 345 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect.fetch(i,j,k) = -vect.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
neg() [4/4]
void neg (double * vect, int n)
method to calculate the opposite of a vector
Definition at line 364 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    vect[i] = -vect[i];
}
References test_new-features::i.
norm2() [1/3]
double norm2 (const arr3_double vect, int nx, int ny)
method to calculate the square norm of a vector
Definition at line 75 of file Basic.cpp.
{
  double result = 0;
  for (int i = 0; i < nx; i++)
    for (int j = 0; j < ny; j++)
      result += vect.get(i,j,0) * vect.get(i,j,0);
  return (result);
}
References iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
norm2() [2/3]
double norm2 (const double *const * vect, int nx, int ny)
method to calculate the square norm of a vector
Definition at line 67 of file Basic.cpp.
{
  double result = 0;
  for (int i = 0; i < nx; i++)
    for (int j = 0; j < ny; j++)
      result += vect[i][j] * vect[i][j];
  return (result);
}
References test_new-features::i, test_to2D::nx, and test_to2D::ny.
norm2() [3/3]
double norm2 (const double * vect, int nx)
method to calculate the square norm of a vector
Definition at line 83 of file Basic.cpp.
{
  double result = 0;
  for (int i = 0; i < nx; i++)
    result += vect[i] * vect[i];
  return (result);
}
References test_new-features::i, and test_to2D::nx.
normP()
double normP (const double * vect, int n, MPI_Comm * comm)
method to calculate the parallel dot product
method to calculate the parallel norm of a vector on different processors with the ghost cell method to calculate the parallel norm of a vector on different processors with the gost cell
Definition at line 117 of file Basic.cpp.
{
  double result = 0.0;
  double local_result = 0.0;
  for (register int i = 0; i < n; i++)
    local_result += vect[i] * vect[i];
  MPI_Allreduce(&local_result, &result, 1, MPI_DOUBLE, MPI_SUM, *comm);
  return (sqrt(result));
}
References test_new-features::i.
prod()
void prod (arr3_double vect1, double alfa, const arr4_double vect2, int ns, const arr3_double vect3, int nx, int ny, int nz)
method to calculate vector1 = alfa*vector2*vector3 with vector2 depending on species
Definition at line 313 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = alfa * vect2.get(ns,i,j,k) * vect3.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), iPic3D::const_array_ref4< type >::get(), test_new-features::i, ns, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
prod6()
void prod6 (arr3_double vect1, const arr3_double vect2, const arr3_double vect3, const arr3_double vect4, const arr3_double vect5, const arr3_double vect6, const arr3_double vect7, int nx, int ny, int nz)
Definition at line 328 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = vect2.get(i,j,k) * vect3.get(i,j,k) + vect4.get(i,j,k) * vect5.get(i,j,k) + vect6.get(i,j,k) * vect7.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
proddiv()
void proddiv (arr3_double vect1, const arr3_double vect2, double alfa, const arr3_double vect3, const arr3_double vect4, const arr3_double vect5, const arr3_double vect6, double beta, const arr3_double vect7, const arr3_double vect8, double gamma, const arr3_double vect9, int nx, int ny, int nz)
method used for calculating PI
Definition at line 335 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = (vect2.get(i,j,k) + alfa * (vect3.get(i,j,k) * vect4.get(i,j,k) - vect5.get(i,j,k) * vect6.get(i,j,k)) + beta * vect7.get(i,j,k) * vect8.get(i,j,k)) / (1 + gamma * vect9.get(i,j,k));
  // questo mi convince veramente poco!!!!!!!!!!!!!! CAZZO!!!!!!!!!!!!!!!!!!
  // ***vect1++ = (***vect2++ + alfa*((***vect3++)*(***vect4++) - (***vect5++)*(***vect6++)) + beta*(***vect7++)*(***vect8++))/(1+gamma*(***vect9++));
}
References plot3_paper-2_cross-sec::beta, iPic3D::array_ref3< type >::fetch(), plot3_paper-2_cross-sec::gamma, iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
putColumn()
void putColumn (double ** Matrix, double * vect, int column, int n)
method to put a column in a matrix 2D
Definition at line 436 of file Basic.cpp.
{
  for (int i = 0; i < n; i++)
    Matrix[i][column] = vect[i];
}
References test_new-features::i.
scale() [1/6]
void scale (arr3_double vect, double alfa, int nx, int ny)
method to calculate the scalar-vector product
Definition at line 198 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect.fetch(i,j,0) *= alfa;
}
References iPic3D::array_ref3< type >::fetch(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
scale() [2/6]
void scale (arr3_double vect, double alfa, int nx, int ny, int nz)
method to calculate the scalar-vector product
Definition at line 206 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect.fetch(i,j,k) *= alfa;
}
References iPic3D::array_ref3< type >::fetch(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
scale() [3/6]
void scale (arr3_double vect1, const arr3_double vect2, double alfa, int nx, int ny)
method to calculate the scalar-vector product
Definition at line 221 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(i,j,0) = vect2.get(i,j,0) * alfa;
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
scale() [4/6]
void scale (arr3_double vect1, const arr3_double vect2, double alfa, int nx, int ny, int nz)
‍** method to calculate the scalar product *‍/
method to calculate the scalar-vector product
‍** method to calculate the scalar product *‍/
Definition at line 213 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = vect2.get(i,j,k) * alfa;
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
scale() [5/6]
void scale (double * vect, double alfa, int n)
method to calculate the scalar-vector product
Definition at line 192 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    vect[i] *= alfa;
}
References test_new-features::i.
scale() [6/6]
void scale (double * vect1, const double * vect2, double alfa, int n)
method to calculate the scalar-vector product
Definition at line 228 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    vect1[i] = vect2[i] * alfa;
}
References test_new-features::i.
scaleandsum() [1/2]
void scaleandsum (arr3_double vect1, double alfa, double beta, const arr3_double vect2, const arr3_double vect3, int nx, int ny, int nz)
method to calculate vector1 = alfa*vector2 + beta*vector3
Definition at line 299 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = alfa * vect2.get(i,j,k) + beta * vect3.get(i,j,k);
}
References plot3_paper-2_cross-sec::beta, iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
scaleandsum() [2/2]
void scaleandsum (arr3_double vect1, double alfa, double beta, const arr4_double vect2, const arr3_double vect3, int ns, int nx, int ny, int nz)
method to calculate vector1 = alfa*vector2 + beta*vector3 with vector2 depending on species
Definition at line 306 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = alfa * vect2.get(ns,i,j,k) + beta * vect3.get(i,j,k);
}
References plot3_paper-2_cross-sec::beta, iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), iPic3D::const_array_ref4< type >::get(), test_new-features::i, ns, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
sub() [1/3]
void sub (arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate the subtraction of two vectors vector1 = vector1 - vector2
Definition at line 176 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(i,j,0) -= vect2.get(i,j,0);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
sub() [2/3]
void sub (arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to calculate the subtraction of two vectors vector1 = vector1 - vector2
Definition at line 168 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) -= vect2.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
sub() [3/3]
void sub (double * res, const double * vect1, const double * vect2, int n)
method to calculate the difference of two vectors
Definition at line 127 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    res[i] = vect1[i] - vect2[i];
}
References test_new-features::i.
sum() [1/5]
void sum (arr3_double vect1, const arr3_double vect2, int nx, int ny)
method to calculate the sum of two vectors vector1 = vector1 + vector2
Definition at line 147 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(i,j,0) += vect2.get(i,j,0);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, and test_to2D::ny.
sum() [2/5]
void sum (arr3_double vect1, const arr3_double vect2, int nx, int ny, int nz)
method to calculate the sum of two vectors vector1 = vector1 + vector2
Definition at line 139 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) += vect2.get(i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
sum() [3/5]
void sum (arr3_double vect1, const arr4_double vect2, int nx, int ny, int ns)
method to calculate the sum of two vectors vector1 = vector1 + vector2
Definition at line 162 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      vect1.fetch(i,j,0) += vect2.get(ns,i,j,0);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref4< type >::get(), test_new-features::i, ns, test_to2D::nx, and test_to2D::ny.
sum() [4/5]
void sum (arr3_double vect1, const arr4_double vect2, int nx, int ny, int nz, int ns)
method to calculate the sum of two vectors vector1 = vector1 + vector2
Definition at line 154 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) += vect2.get(ns,i,j,k);
}
References iPic3D::array_ref3< type >::fetch(), iPic3D::const_array_ref4< type >::get(), test_new-features::i, ns, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
sum() [5/5]
void sum (double * vect1, const double * vect2, int n)
method to calculate the sum of two vectors vector1 = vector1 + vector2
Definition at line 132 of file Basic.cpp.
{
  for (register int i = 0; i < n; i++)
    vect1[i] += vect2[i];
}
References test_new-features::i.
sum4()
void sum4 (arr3_double vect1, double alfa, const arr3_double vect2, double beta, const arr3_double vect3, double gamma, const arr3_double vect4, double delta, const arr3_double vect5, int nx, int ny, int nz)
method to sum 4 vectors vector1 = alfa*vector1 + beta*vector2 + gamma*vector3 + delta*vector4
Definition at line 184 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1.fetch(i,j,k) = alfa * (vect2.get(i,j,k) + beta * vect3.get(i,j,k) + gamma * vect4.get(i,j,k) + delta * vect5.get(i,j,k));
}
References plot3_paper-2_cross-sec::beta, iPic3D::array_ref3< type >::fetch(), plot3_paper-2_cross-sec::gamma, iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
sumscalprod()
void sumscalprod (double *** vect1, double alfa, double *** vect2, double *** vect3, int nx, int ny, int nz)
method to calculate v1 = v1 + alpha * v2 * v3
Definition at line 291 of file Basic.cpp.
{
  for (register int i = 0; i < nx; i++)
    for (register int j = 0; j < ny; j++)
      for (register int k = 0; k < nz; k++)
        vect1[i][j][k] += alfa * vect2[i][j][k] * vect3[i][j][k];
}
References test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.