iPIC3DxPEACE: include/ompdefs.h File Reference
ompdefs.h File Reference
#include <stdio.h>
#include "asserts.h"
Classes
class Caller_to_SetMaxThreadsForScope
Macros
#define omp_set_num_threads(num_threads)
#define set_max_threads_for_scope(num_threads)
Functions
int omp_get_thread_num ()
int omp_get_max_threads ()
Macro Definition Documentation
omp_set_num_threads
#define omp_set_num_threads (num_threads)
Definition at line 32 of file ompdefs.h.
set_max_threads_for_scope
#define set_max_threads_for_scope (num_threads)
Value:
  Caller_to_SetMaxThreadsForScope \
  instanceOfCaller_to_SetMaxThreadsForScope(num_threads);
Definition at line 52 of file ompdefs.h.
Function Documentation
omp_get_max_threads()
int omp_get_max_threads () inline
Definition at line 31 of file ompdefs.h.
{ return 1;}
Referenced by Caller_to_SetMaxThreadsForScope::Caller_to_SetMaxThreadsForScope(), EMfields3D::EMfields3D(), MPIdata::Print(), doubleIDgenerator::reserve_particles_in_range(), EMfields3D::sumMoments_AoS_intr(), and EMfields3D::sumMomentsOld().
omp_get_thread_num()
int omp_get_thread_num () inline
Definition at line 30 of file ompdefs.h.
{ return 0;}
Referenced by TimeTasks::end_allreduce(), TimeTasks::end_main_task(), TimeTasks::end_sendrecv(), TimeTasks::end_task(), eprintf_fileLine(), fprintf_fileLine(), doubleIDgenerator::generateID(), is_output_thread(), TimeTasks::print_cycle_times(), TimeTasks::start_main_task(), TimeTasks::start_task(), EMfields3D::sumMoments(), EMfields3D::sumMoments_AoS(), EMfields3D::sumMoments_AoS_intr(), EMfields3D::sumMomentsOld(), TimeTasks_caller_to_set_main_task_for_scope::TimeTasks_caller_to_set_main_task_for_scope(), TimeTasks_caller_to_set_task_for_scope::TimeTasks_caller_to_set_task_for_scope(), TimeTasks_caller_to_set_main_task_for_scope::~TimeTasks_caller_to_set_main_task_for_scope(), and TimeTasks_caller_to_set_task_for_scope::~TimeTasks_caller_to_set_task_for_scope().