iPIC3DxPEACE: plot1_paper-2_image Namespace Reference
plot1_paper-2_image Namespace Reference
Functions
def load_cusp (input_file_cusp, proj=None)
Load the cusps ##############################################.
def load_prec (input_file_prec, proj=None)
Load Latitude-LT map from prec.
def plot_data (ax, input_file_prec, input_file_cusp=None, proj=None, xlab=0)
Put plot in given axis #####################################.
def main (input_file_prec, input_file_cusp=None, proj=None)
Main of the code #####################################.
Variables
string precPR0mBzEn_0_100 = 'energy-zero-hundreds-e-negz.csv'
string precPR0pBzEn_0_100 = 'energy-zero-hundreds-e-posz.csv'
string precPR0mBzEn_100_1000 = 'energy-hundreds-thousands-e-negz.csv'
string precPR0pBzEn_100_1000 = 'energy-hundreds-thousands-e-posz.csv'
string precPR0mBzEn_1000_inf = 'energy-thousands-inf-e-negz.csv'
string precPR0pBzEn_1000_inf = 'energy-thousands-inf-e-posz.csv'
string precPR0mBzEn_0_inf = 'energy-zero-inf-e-negz.csv'
string precPR0pBzEn_0_inf = 'energy-zero-inf-e-posz.csv'
list ml = []
list cl = []
string save_name = 'Composite_i_Ener_ALL_5'
string cuspPR0mBz = 'texts/output_cusps_PR0-minusBz_5000.txt'
string cuspPR0pBz = 'texts/output_cusps_PR0-plusBz_6400.txt'
string cuspPR1mBz = 'texts/output_cusps_PR1-minusBz_6500.txt'
string cuspPR1pBz = 'texts/output_cusps_PR1-plusBz_6000.txt'
string precPR0mBzFe = 'texts/output_precipitation_PR0-minusBz_Flux-e.txt'
string precPR0mBz1Fe = 'texts/output_precipitation_PR0-minusBz_0-100s_Flux-e.txt'
string precPR0mBz2Fe = 'texts/output_precipitation_PR0-minusBz_100-1000s_Flux-e.txt'
string precPR0mBz3Fe = 'texts/output_precipitation_PR0-minusBz_1000s-inf_Flux-e.txt'
string precPR0pBzFe = 'texts/output_precipitation_PR0-plusBz_Flux-e.txt'
string precPR0pBz1Fe = 'texts/output_precipitation_PR0-plusBz_0-100s_Flux-e.txt'
string precPR0pBz2Fe = 'texts/output_precipitation_PR0-plusBz_100-1000s_Flux-e.txt'
string precPR0pBz3Fe = 'texts/output_precipitation_PR0-plusBz_1000s-inf_Flux-e.txt'
string precPR1mBzFe = 'texts/output_precipitation_PR1-minusBz_Flux-e.txt'
string precPR1mBz1Fe = 'texts/output_precipitation_PR1-minusBz_0-100s_Flux-e.txt'
string precPR1mBz2Fe = 'texts/output_precipitation_PR1-minusBz_100-1000s_Flux-e.txt'
string precPR1mBz3Fe = 'texts/output_precipitation_PR1-minusBz_1000s-inf_Flux-e.txt'
string precPR1pBzFe = 'texts/output_precipitation_PR1-plusBz_Flux-e.txt'
string precPR1pBz1Fe = 'texts/output_precipitation_PR1-plusBz_0-100s_Flux-e.txt'
string precPR1pBz2Fe = 'texts/output_precipitation_PR1-plusBz_100-1000s_Flux-e.txt'
string precPR1pBz3Fe = 'texts/output_precipitation_PR1-plusBz_1000s-inf_Flux-e.txt'
string precPR1pBzH = 'texts_rates/map_PR1-plusBz_EII-H.txt'
string precPR1mBzH = 'texts_rates/map_PR1-minusBz_EII-H.txt'
string precPR1pBzNa = 'texts_rates/map_PR1-plusBz_EII-Na.txt'
string precPR1mBzNa = 'texts_rates/map_PR1-minusBz_EII-Na.txt'
string precPR1pBzK = 'texts_rates/map_PR1-plusBz_EII-K.txt'
string precPR1mBzK = 'texts_rates/map_PR1-minusBz_EII-K.txt'
string precPR1pBzSi = 'texts_rates/map_PR1-plusBz_EII-Si.txt'
string precPR1mBzSi = 'texts_rates/map_PR1-minusBz_EII-Si.txt'
string precPR1pBzMg = 'texts_rates/map_PR1-plusBz_EII-Mg.txt'
string precPR1mBzMg = 'texts_rates/map_PR1-minusBz_EII-Mg.txt'
string precPR1pBzHe = 'texts_rates/map_PR1-plusBz_EII-He.txt'
string precPR1mBzHe = 'texts_rates/map_PR1-minusBz_EII-He.txt'
string precPR1pBzO = 'texts_rates/map_PR1-plusBz_EII-O.txt'
string precPR1mBzO = 'texts_rates/map_PR1-minusBz_EII-O.txt'
string precPR1pBzCa = 'texts_rates/map_PR1-plusBz_EII-Ca.txt'
string precPR1mBzCa = 'texts_rates/map_PR1-minusBz_EII-Ca.txt'
string precPR1pBzAl = 'texts_rates/map_PR1-plusBz_EII-Al.txt'
string precPR1mBzAl = 'texts_rates/map_PR1-minusBz_EII-Al.txt'
string precPR1pBzMn = 'texts_rates/map_PR1-plusBz_EII-Mn.txt'
string precPR1mBzMn = 'texts_rates/map_PR1-minusBz_EII-Mn.txt'
Function Documentation
load_cusp()
def plot1_paper-2_image.load_cusp (input_file_cusp, proj = None)
Load the cusps ##############################################.
Definition at line 12 of file plot1_paper-2_image.py.
def load_cusp(input_file_cusp,proj=None):
    # load txt file with values cusp thresold
    phi_c,theta_c,comment = np.loadtxt(input_file_cusp,unpack=True,dtype='str')
    lot_cusp = np.array(phi_c,dtype='float')*24./(2*np.pi)
    lat_cusp = 90.-(np.array(theta_c,dtype='float')*180./np.pi)
    x_cusp=[]
    y_cusp=[]
    for i in range(0,len(phi_c)):
        if lot_cusp[i] not in x_cusp:
            if len(lat_cusp[(phi_c==phi_c[i])*(lat_cusp>0)])>0:
                x_cusp.append(lot_cusp[i])
                y_cusp.append(np.min(lat_cusp[(phi_c==phi_c[i])*(lat_cusp>0)]))
            if len(lat_cusp[(phi_c==phi_c[i])*(lat_cusp<0)])>0:
                x_cusp.append(lot_cusp[i])
                y_cusp.append(np.max(lat_cusp[(phi_c==phi_c[i])*(lat_cusp<0)]))
    x_cusp = np.array(x_cusp)
    y_cusp = np.array(y_cusp)
    x_cuspN = x_cusp[np.where(y_cusp>0)]
    y_cuspN = y_cusp[np.where(y_cusp>0)]
    x_cuspS = x_cusp[np.where(y_cusp<0)]
    y_cuspS = y_cusp[np.where(y_cusp<0)]
    # convert to good units for mollweide proj.
    if proj is not None:
        x_cuspN = (x_cuspN-12.)/12.*np.pi
        x_cuspS = (x_cuspS-12.)/12.*np.pi
        y_cuspN = y_cuspN/90.*(np.pi/2.)
        y_cuspS = y_cuspS/90.*(np.pi/2.)
    print('CUSP LOADED -->'+input_file_cusp)
    return [[x_cuspN,y_cuspN],[x_cuspS,y_cuspS]]
References plot2_paper_df.range.
Referenced by plot_data().
load_prec()
def plot1_paper-2_image.load_prec (input_file_prec, proj = None)
Load Latitude-LT map from prec.
file ###########################
Definition at line 51 of file plot1_paper-2_image.py.
def load_prec(input_file_prec,proj=None):
    data_prec = np.loadtxt(input_file_prec[0],delimiter=',')
    # grid coordinates
    lot = np.linspace(-180,180,50)
    #lot = np.linspace(-np.pi,np.pi,50)
    lat = np.linspace(-90,90,25)
    #lat = np.linspace(-np.pi/2,np.pi/2,25)
    # create grid
    Lot,Lat = np.meshgrid(lot,lat)
    # actual data load 1st file
    histo = np.zeros((len(lot),len(lat)))
    for iy,line in enumerate(data_prec):
        if iy>0:
            histo[:,iy-1]=line[:]
    # print status
    print('GRID LatxLT LOADED -->'+input_file_prec[0])
    if len(input_file_prec)>1 :
        print('MAP LatxLT LOADED WITH %i files'%len(input_file_prec))
    if len(input_file_prec)>1 :
        if 'Flux' in input_file_prec[1]:
            histo /= 2.
    return [histo,Lot,Lat]
Referenced by plot_data().
main()
def plot1_paper-2_image.main (input_file_prec, input_file_cusp = None, proj = None)
Main of the code #####################################.
Definition at line 131 of file plot1_paper-2_image.py.
def main(input_file_prec,input_file_cusp=None,proj=None):
    # number of plots
    Nplots = len(input_file_prec)
    if Nplots%2==0 and Nplots<10 :
        Nx = Nplots/2
        Ny = 2
    elif Nplots%2==1 and Nplots<10 :
        Nx = (Nplots+1)/2
        Ny = 2
    elif Nplots>10 :
        Nx = Nplots/3
        Ny = 3
    #extra
    Nx = 4
    Ny = 2
    fig_size = (Nx*6,Ny*4) #8,4 $6,4
    # do the picture
    fig = plt.figure(figsize=fig_size)
    # do the plots
    for ip in range(0,Nplots):
        print('DO PLOTS -->',Ny,Nx,ip+1)
        ax = fig.add_subplot(Ny, Nx, ip+1, projection=proj)
        im,clab,data = plot_data(ax,input_file_prec[ip],input_file_cusp[ip],proj,xlab=ip)
        if proj is not None:
            # add colorbar1 Flux
            if ip==0 :
                cax1 = fig.add_axes([0.3, 0.1, 0.45, 0.016])
                cb1 = fig.colorbar(im, cax=cax1, orientation='horizontal')
                cb1.set_label(clab,rotation=0,fontsize=20)
                cb1.ax.tick_params(labelsize=16)
        else:
            if ip>3:
                ax.set_xlabel('Longitude [deg]',fontsize=16)
            if ip==0 or ip==4:
                ax.set_ylabel('Latitude [deg]',fontsize=16)
            cb1 = fig.colorbar(im, orientation='vertical')
            cb1.set_label(clab,rotation=0,fontsize=16)
            cb1.ax.tick_params(labelsize=16)
            plt.xlim(-180,180)
            plt.ylim(-90,90)
    # add text
    plt.figtext(0.45,0.9,'Northward IMF',fontsize=32)
    plt.figtext(0.45,0.45,'Southward IMF',fontsize=32)
    # save figure and close
    if proj is not None:
        plt.subplots_adjust(top=0.95,bottom=0.1,wspace=0.2, hspace=0.0)
    else:
        plt.subplots_adjust(top=0.87,bottom=0.1,wspace=0.3, hspace=0.4)
    plt.savefig('images/'+save_name+'.png',format='png')
    plt.show()
    plt.close()
# PR0
References plot_data(), and plot2_paper_df.range.
plot_data()
def plot1_paper-2_image.plot_data (ax, input_file_prec, input_file_cusp = None, proj = None, xlab = 0)
Put plot in given axis #####################################.
Definition at line 85 of file plot1_paper-2_image.py.
def plot_data(ax,input_file_prec,input_file_cusp=None,proj=None,xlab=0):
    # open cusp data
    if input_file_cusp is not None:
        cusp = load_cusp(input_file_cusp,proj)
    # open prec map data
    prec = load_prec(input_file_prec,proj)
    # define pars plot for two cases
    if len(input_file_prec)==1:
        if 'flux' in input_file_prec[0]:
            cmm = cm.Reds
            vlim = [6e26,1e30]
            clab = r'#pcls'
        else:
            cmm = cm.coolwarm
            vlim = [2e28,4e33]
            clab = r'$eV$'
    # plot actual data
    im = ax.pcolormesh(prec[1],prec[2],np.transpose(prec[0]),norm=matplotlib.colors.LogNorm(),vmin=vlim[0],vmax=vlim[1],cmap=cmm)
    # define extra fancy plot pars
    if proj is not None:
        plt.yticks([-np.pi/2,-np.pi/3,-np.pi/6,0,np.pi/6,np.pi/3],fontsize=14)
        plt.xticks([-np.pi*0.98,-np.pi*3/4,-np.pi/2,-np.pi/4.,0,np.pi/4,np.pi/2,np.pi*3/4,np.pi*0.98],fontsize=14)
        if not xlab:
            print('ciao')
            #ax.set_xticklabels(['0','3','6','9','12','15','18','21','24'],fontsize=14)
        else:
            ax.set_xticklabels([])
    else:
        plt.yticks(fontsize=14)
        plt.xticks(fontsize=14)
    plt.grid(alpha=0.6)
    return im,clab,prec
References load_cusp(), and load_prec().
Referenced by main().
Variable Documentation
cl
list plot1_paper-2_image.cl = []
Definition at line 213 of file plot1_paper-2_image.py.
cuspPR0mBz
string plot1_paper-2_image.cuspPR0mBz = 'texts/output_cusps_PR0-minusBz_5000.txt'
Definition at line 321 of file plot1_paper-2_image.py.
cuspPR0pBz
string plot1_paper-2_image.cuspPR0pBz = 'texts/output_cusps_PR0-plusBz_6400.txt'
Definition at line 322 of file plot1_paper-2_image.py.
cuspPR1mBz
string plot1_paper-2_image.cuspPR1mBz = 'texts/output_cusps_PR1-minusBz_6500.txt'
Definition at line 323 of file plot1_paper-2_image.py.
cuspPR1pBz
string plot1_paper-2_image.cuspPR1pBz = 'texts/output_cusps_PR1-plusBz_6000.txt'
Definition at line 324 of file plot1_paper-2_image.py.
ml
list plot1_paper-2_image.ml = []
Definition at line 206 of file plot1_paper-2_image.py.
precPR0mBz1Fe
string plot1_paper-2_image.precPR0mBz1Fe = 'texts/output_precipitation_PR0-minusBz_0-100s_Flux-e.txt'
Definition at line 328 of file plot1_paper-2_image.py.
precPR0mBz2Fe
string plot1_paper-2_image.precPR0mBz2Fe = 'texts/output_precipitation_PR0-minusBz_100-1000s_Flux-e.txt'
Definition at line 329 of file plot1_paper-2_image.py.
precPR0mBz3Fe
string plot1_paper-2_image.precPR0mBz3Fe = 'texts/output_precipitation_PR0-minusBz_1000s-inf_Flux-e.txt'
Definition at line 330 of file plot1_paper-2_image.py.
precPR0mBzEn_0_100
string plot1_paper-2_image.precPR0mBzEn_0_100 = 'energy-zero-hundreds-e-negz.csv'
Definition at line 196 of file plot1_paper-2_image.py.
precPR0mBzEn_0_inf
string plot1_paper-2_image.precPR0mBzEn_0_inf = 'energy-zero-inf-e-negz.csv'
Definition at line 202 of file plot1_paper-2_image.py.
precPR0mBzEn_1000_inf
string plot1_paper-2_image.precPR0mBzEn_1000_inf = 'energy-thousands-inf-e-negz.csv'
Definition at line 200 of file plot1_paper-2_image.py.
precPR0mBzEn_100_1000
string plot1_paper-2_image.precPR0mBzEn_100_1000 = 'energy-hundreds-thousands-e-negz.csv'
Definition at line 198 of file plot1_paper-2_image.py.
precPR0mBzFe
string plot1_paper-2_image.precPR0mBzFe = 'texts/output_precipitation_PR0-minusBz_Flux-e.txt'
Definition at line 327 of file plot1_paper-2_image.py.
precPR0pBz1Fe
string plot1_paper-2_image.precPR0pBz1Fe = 'texts/output_precipitation_PR0-plusBz_0-100s_Flux-e.txt'
Definition at line 332 of file plot1_paper-2_image.py.
precPR0pBz2Fe
string plot1_paper-2_image.precPR0pBz2Fe = 'texts/output_precipitation_PR0-plusBz_100-1000s_Flux-e.txt'
Definition at line 333 of file plot1_paper-2_image.py.
precPR0pBz3Fe
string plot1_paper-2_image.precPR0pBz3Fe = 'texts/output_precipitation_PR0-plusBz_1000s-inf_Flux-e.txt'
Definition at line 334 of file plot1_paper-2_image.py.
precPR0pBzEn_0_100
string plot1_paper-2_image.precPR0pBzEn_0_100 = 'energy-zero-hundreds-e-posz.csv'
Definition at line 197 of file plot1_paper-2_image.py.
precPR0pBzEn_0_inf
string plot1_paper-2_image.precPR0pBzEn_0_inf = 'energy-zero-inf-e-posz.csv'
Definition at line 203 of file plot1_paper-2_image.py.
precPR0pBzEn_1000_inf
string plot1_paper-2_image.precPR0pBzEn_1000_inf = 'energy-thousands-inf-e-posz.csv'
Definition at line 201 of file plot1_paper-2_image.py.
precPR0pBzEn_100_1000
string plot1_paper-2_image.precPR0pBzEn_100_1000 = 'energy-hundreds-thousands-e-posz.csv'
Definition at line 199 of file plot1_paper-2_image.py.
precPR0pBzFe
string plot1_paper-2_image.precPR0pBzFe = 'texts/output_precipitation_PR0-plusBz_Flux-e.txt'
Definition at line 331 of file plot1_paper-2_image.py.
precPR1mBz1Fe
string plot1_paper-2_image.precPR1mBz1Fe = 'texts/output_precipitation_PR1-minusBz_0-100s_Flux-e.txt'
Definition at line 337 of file plot1_paper-2_image.py.
precPR1mBz2Fe
string plot1_paper-2_image.precPR1mBz2Fe = 'texts/output_precipitation_PR1-minusBz_100-1000s_Flux-e.txt'
Definition at line 338 of file plot1_paper-2_image.py.
precPR1mBz3Fe
string plot1_paper-2_image.precPR1mBz3Fe = 'texts/output_precipitation_PR1-minusBz_1000s-inf_Flux-e.txt'
Definition at line 339 of file plot1_paper-2_image.py.
precPR1mBzAl
string plot1_paper-2_image.precPR1mBzAl = 'texts_rates/map_PR1-minusBz_EII-Al.txt'
Definition at line 363 of file plot1_paper-2_image.py.
precPR1mBzCa
string plot1_paper-2_image.precPR1mBzCa = 'texts_rates/map_PR1-minusBz_EII-Ca.txt'
Definition at line 361 of file plot1_paper-2_image.py.
precPR1mBzFe
string plot1_paper-2_image.precPR1mBzFe = 'texts/output_precipitation_PR1-minusBz_Flux-e.txt'
Definition at line 336 of file plot1_paper-2_image.py.
precPR1mBzH
string plot1_paper-2_image.precPR1mBzH = 'texts_rates/map_PR1-minusBz_EII-H.txt'
Definition at line 347 of file plot1_paper-2_image.py.
precPR1mBzHe
string plot1_paper-2_image.precPR1mBzHe = 'texts_rates/map_PR1-minusBz_EII-He.txt'
Definition at line 357 of file plot1_paper-2_image.py.
precPR1mBzK
string plot1_paper-2_image.precPR1mBzK = 'texts_rates/map_PR1-minusBz_EII-K.txt'
Definition at line 351 of file plot1_paper-2_image.py.
precPR1mBzMg
string plot1_paper-2_image.precPR1mBzMg = 'texts_rates/map_PR1-minusBz_EII-Mg.txt'
Definition at line 355 of file plot1_paper-2_image.py.
precPR1mBzMn
string plot1_paper-2_image.precPR1mBzMn = 'texts_rates/map_PR1-minusBz_EII-Mn.txt'
Definition at line 365 of file plot1_paper-2_image.py.
precPR1mBzNa
string plot1_paper-2_image.precPR1mBzNa = 'texts_rates/map_PR1-minusBz_EII-Na.txt'
Definition at line 349 of file plot1_paper-2_image.py.
precPR1mBzO
string plot1_paper-2_image.precPR1mBzO = 'texts_rates/map_PR1-minusBz_EII-O.txt'
Definition at line 359 of file plot1_paper-2_image.py.
precPR1mBzSi
string plot1_paper-2_image.precPR1mBzSi = 'texts_rates/map_PR1-minusBz_EII-Si.txt'
Definition at line 353 of file plot1_paper-2_image.py.
precPR1pBz1Fe
string plot1_paper-2_image.precPR1pBz1Fe = 'texts/output_precipitation_PR1-plusBz_0-100s_Flux-e.txt'
Definition at line 341 of file plot1_paper-2_image.py.
precPR1pBz2Fe
string plot1_paper-2_image.precPR1pBz2Fe = 'texts/output_precipitation_PR1-plusBz_100-1000s_Flux-e.txt'
Definition at line 342 of file plot1_paper-2_image.py.
precPR1pBz3Fe
string plot1_paper-2_image.precPR1pBz3Fe = 'texts/output_precipitation_PR1-plusBz_1000s-inf_Flux-e.txt'
Definition at line 343 of file plot1_paper-2_image.py.
precPR1pBzAl
string plot1_paper-2_image.precPR1pBzAl = 'texts_rates/map_PR1-plusBz_EII-Al.txt'
Definition at line 362 of file plot1_paper-2_image.py.
precPR1pBzCa
string plot1_paper-2_image.precPR1pBzCa = 'texts_rates/map_PR1-plusBz_EII-Ca.txt'
Definition at line 360 of file plot1_paper-2_image.py.
precPR1pBzFe
string plot1_paper-2_image.precPR1pBzFe = 'texts/output_precipitation_PR1-plusBz_Flux-e.txt'
Definition at line 340 of file plot1_paper-2_image.py.
precPR1pBzH
string plot1_paper-2_image.precPR1pBzH = 'texts_rates/map_PR1-plusBz_EII-H.txt'
Definition at line 346 of file plot1_paper-2_image.py.
precPR1pBzHe
string plot1_paper-2_image.precPR1pBzHe = 'texts_rates/map_PR1-plusBz_EII-He.txt'
Definition at line 356 of file plot1_paper-2_image.py.
precPR1pBzK
string plot1_paper-2_image.precPR1pBzK = 'texts_rates/map_PR1-plusBz_EII-K.txt'
Definition at line 350 of file plot1_paper-2_image.py.
precPR1pBzMg
string plot1_paper-2_image.precPR1pBzMg = 'texts_rates/map_PR1-plusBz_EII-Mg.txt'
Definition at line 354 of file plot1_paper-2_image.py.
precPR1pBzMn
string plot1_paper-2_image.precPR1pBzMn = 'texts_rates/map_PR1-plusBz_EII-Mn.txt'
Definition at line 364 of file plot1_paper-2_image.py.
precPR1pBzNa
string plot1_paper-2_image.precPR1pBzNa = 'texts_rates/map_PR1-plusBz_EII-Na.txt'
Definition at line 348 of file plot1_paper-2_image.py.
precPR1pBzO
string plot1_paper-2_image.precPR1pBzO = 'texts_rates/map_PR1-plusBz_EII-O.txt'
Definition at line 358 of file plot1_paper-2_image.py.
precPR1pBzSi
string plot1_paper-2_image.precPR1pBzSi = 'texts_rates/map_PR1-plusBz_EII-Si.txt'
Definition at line 352 of file plot1_paper-2_image.py.
save_name
string plot1_paper-2_image.save_name = 'Composite_i_Ener_ALL_5'
Definition at line 217 of file plot1_paper-2_image.py.