iPIC3DxPEACE: plot_Jpar-planet Namespace Reference
plot_Jpar-planet Namespace Reference
Functions
def scalr (a)
Variables
int cycle = 6000
bool compute_Flag = False
bool imaging_Flag = True
data_address = sys.argv[1]
-—path-to-run----------------—
string fibo_name = 'ipic3d'
alldata = fb.fibo(fibo_name)
from_VTK = fb.from_VTK(data_address)
silent
meta
x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
xc = from_VTK.meta['xc']
yc = from_VTK.meta['yc']
zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
dx = from_VTK.meta['dx']/from_VTK.meta['R']
dy = from_VTK.meta['dy']/from_VTK.meta['R']
dz = from_VTK.meta['dz']/from_VTK.meta['R']
list i_good = []
list lot = []
list lat = []
list sph = []
list Jpar_good = []
conv_J = -(4.*np.pi*30.)*(400./0.027)*(0.16)
Jparx
Jpary
Jparz
fibo_obj
None
tar_var
rad = np.sqrt(x[ix]**2+y[iy]**2+z[iz]**2)
rho = np.sqrt(x[ix]**2+y[iy]**2)
senphi = y[iy]/rho
cosphi = x[ix]/rho
costhe = z[iz]/rad
out = open('output_plot_Jpargf3.txt','w')
int Nx = 50
int Ny = 50
grid_x = np.linspace(-1,1,Nx)
grid_y = np.linspace(0,1,Ny)
maap = np.zeros([Nx,Ny])
Jpar
unpack
tuple igood = (costhe<grid_y[iy+1])*(costhe>grid_y[iy])*(cosphi<grid_x[ix+1])*(cosphi>grid_x[ix])*(senphi>0)
filter_sigma
clim_min
clim_max
Log
Function Documentation
scalr()
def plot_Jpar-planet.scalr (a)
Definition at line 43 of file plot_Jpar-planet.py.
def scalr(a):
    return np.sqrt(a[0]**2+a[1]**2+a[2]**2)
#----load-Jpar------------------
Referenced by plot2_paper_nBJ.main().
Variable Documentation
alldata
plot_Jpar-planet.alldata = fb.fibo(fibo_name)
Definition at line 18 of file plot_Jpar-planet.py.
clim_max
plot_Jpar-planet.clim_max
Definition at line 90 of file plot_Jpar-planet.py.
clim_min
plot_Jpar-planet.clim_min
Definition at line 90 of file plot_Jpar-planet.py.
compute_Flag
bool plot_Jpar-planet.compute_Flag = False
Definition at line 9 of file plot_Jpar-planet.py.
conv_J
plot_Jpar-planet.conv_J = -(4.*np.pi*30.)*(400./0.027)*(0.16)
Definition at line 49 of file plot_Jpar-planet.py.
cosphi
plot_Jpar-planet.cosphi = x[ix]/rho
Definition at line 60 of file plot_Jpar-planet.py.
costhe
plot_Jpar-planet.costhe = z[iz]/rad
Definition at line 61 of file plot_Jpar-planet.py.
cycle
plot_Jpar-planet.cycle = 6000
Definition at line 8 of file plot_Jpar-planet.py.
Referenced by OutputWrapperFPP.append_output(), OutputWrapperFPP.append_restart(), EMfields3D.calculateE(), iPic3D::c_Solver.CalculateField(), Particles3D.deleteParticlesInsideSphere(), Particles3D.deleteParticlesInsideSphere2DPlaneXZ(), PSK::OutputManager< Toa >.output(), myOutputAgent< Toa >.output(), iPic3D::c_Solver.ParticlesMover(), TimeTasks.print_cycle_times(), readscalar(), readvect(), readwriteparticles(), readwritepartproc(), Particles3D.rotateAndCountParticlesInsideSphere(), Particles3D.rotateAndCountParticlesInsideSphere2DPlaneXZ(), iPic3D::c_Solver.WriteConserved(), writedensity(), writedensity4(), iPic3D::c_Solver.WriteFields(), WriteFieldsH5hut(), WriteFieldsVTK(), WriteFieldsVTKNonblk(), WriteMomentsVTK(), WriteMomentsVTKNonblk(), iPic3D::c_Solver.WriteOutput(), WriteOutputParallel(), WritePartclH5hut(), iPic3D::c_Solver.WriteParticles(), iPic3D::c_Solver.WriteRestart(), writescalar(), writetensor(), iPic3D::c_Solver.WriteTestParticles(), WriteTestPclsVTK(), writevect(), and iPic3D::c_Solver.WriteVelocityDistribution().
data_address
plot_Jpar-planet.data_address = sys.argv[1]
-—path-to-run----------------—
Definition at line 14 of file plot_Jpar-planet.py.
dx
plot_Jpar-planet.dx = from_VTK.meta['dx']/from_VTK.meta['R']
Definition at line 33 of file plot_Jpar-planet.py.
dy
plot_Jpar-planet.dy = from_VTK.meta['dy']/from_VTK.meta['R']
Definition at line 34 of file plot_Jpar-planet.py.
dz
plot_Jpar-planet.dz = from_VTK.meta['dz']/from_VTK.meta['R']
Definition at line 35 of file plot_Jpar-planet.py.
fibo_name
string plot_Jpar-planet.fibo_name = 'ipic3d'
Definition at line 17 of file plot_Jpar-planet.py.
fibo_obj
plot_Jpar-planet.fibo_obj
Definition at line 50 of file plot_Jpar-planet.py.
filter_sigma
plot_Jpar-planet.filter_sigma
Definition at line 90 of file plot_Jpar-planet.py.
from_VTK
plot_Jpar-planet.from_VTK = fb.from_VTK(data_address)
Definition at line 19 of file plot_Jpar-planet.py.
grid_x
plot_Jpar-planet.grid_x = np.linspace(-1,1,Nx)
Definition at line 81 of file plot_Jpar-planet.py.
grid_y
plot_Jpar-planet.grid_y = np.linspace(0,1,Ny)
Definition at line 82 of file plot_Jpar-planet.py.
i_good
list plot_Jpar-planet.i_good = []
Definition at line 36 of file plot_Jpar-planet.py.
igood
tuple plot_Jpar-planet.igood = (costhe<grid_y[iy+1])*(costhe>grid_y[iy])*(cosphi<grid_x[ix+1])*(cosphi>grid_x[ix])*(senphi>0)
Definition at line 88 of file plot_Jpar-planet.py.
imaging_Flag
bool plot_Jpar-planet.imaging_Flag = True
Definition at line 10 of file plot_Jpar-planet.py.
Jpar
plot_Jpar-planet.Jpar
Definition at line 85 of file plot_Jpar-planet.py.
Jpar_good
plot_Jpar-planet.Jpar_good = []
Definition at line 40 of file plot_Jpar-planet.py.
Jparx
plot_Jpar-planet.Jparx
Definition at line 50 of file plot_Jpar-planet.py.
Jpary
plot_Jpar-planet.Jpary
Definition at line 50 of file plot_Jpar-planet.py.
Jparz
plot_Jpar-planet.Jparz
Definition at line 50 of file plot_Jpar-planet.py.
lat
plot_Jpar-planet.lat = []
Definition at line 38 of file plot_Jpar-planet.py.
Log
plot_Jpar-planet.Log
Definition at line 90 of file plot_Jpar-planet.py.
lot
plot_Jpar-planet.lot = []
Definition at line 37 of file plot_Jpar-planet.py.
maap
plot_Jpar-planet.maap = np.zeros([Nx,Ny])
Definition at line 83 of file plot_Jpar-planet.py.
meta
plot_Jpar-planet.meta
Definition at line 23 of file plot_Jpar-planet.py.
None
plot_Jpar-planet.None
Definition at line 50 of file plot_Jpar-planet.py.
Nx
int plot_Jpar-planet.Nx = 50
Definition at line 79 of file plot_Jpar-planet.py.
Ny
int plot_Jpar-planet.Ny = 50
Definition at line 80 of file plot_Jpar-planet.py.
out
plot_Jpar-planet.out = open('output_plot_Jpargf3.txt','w')
Definition at line 71 of file plot_Jpar-planet.py.
Referenced by getRidGhost(), main(), InterfaceFluid.ReadIdlAscii(), and InterfaceFluid.ReadVariables().
rad
plot_Jpar-planet.rad = np.sqrt(x[ix]**2+y[iy]**2+z[iz]**2)
Definition at line 57 of file plot_Jpar-planet.py.
rho
plot_Jpar-planet.rho = np.sqrt(x[ix]**2+y[iy]**2)
Definition at line 58 of file plot_Jpar-planet.py.
senphi
plot_Jpar-planet.senphi = y[iy]/rho
Definition at line 59 of file plot_Jpar-planet.py.
silent
plot_Jpar-planet.silent
Definition at line 22 of file plot_Jpar-planet.py.
sph
plot_Jpar-planet.sph = []
Definition at line 39 of file plot_Jpar-planet.py.
tar_var
plot_Jpar-planet.tar_var
Definition at line 50 of file plot_Jpar-planet.py.
unpack
plot_Jpar-planet.unpack
Definition at line 85 of file plot_Jpar-planet.py.
x
tuple plot_Jpar-planet.x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
Definition at line 24 of file plot_Jpar-planet.py.
Referenced by add_moments_for_pcl(), add_moments_for_pcl_vec(), compute_moments(), drd(), drf(), Dvec4.Dvec4(), Grid3DCU.get_safe_cell_coordinates(), EMfields3D.initDipole(), EMfields3D.initDipole2D(), initialize_vector(), loopX(), loopY(), loopZ(), modulo(), pow2rounddown(), pow2roundup(), Collective.read_particles_restart(), EMfields3D.SetLambda(), EMfields3D.sumMoments(), EMfields3D.sumMoments_vectorized(), EMfields3D.sumMomentsOld(), and Larray< type >.swap().
xc
plot_Jpar-planet.xc = from_VTK.meta['xc']
Definition at line 27 of file plot_Jpar-planet.py.
Referenced by EMfields3D.initDipole(), EMfields3D.initDipole2D(), loopX(), loopY(), loopZ(), and EMfields3D.SetLambda().
y
tuple plot_Jpar-planet.y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
Definition at line 25 of file plot_Jpar-planet.py.
Referenced by add_moments_for_pcl(), add_moments_for_pcl_vec(), compute_moments(), drd(), drf(), Dvec4.Dvec4(), Grid3DCU.get_safe_cell_coordinates(), GMRES(), EMfields3D.initDipole(), initialize_vector(), loopX(), loopY(), loopZ(), Collective.read_particles_restart(), EMfields3D.SetLambda(), EMfields3D.sumMoments(), EMfields3D.sumMoments_vectorized(), and EMfields3D.sumMomentsOld().
yc
plot_Jpar-planet.yc = from_VTK.meta['yc']
Definition at line 28 of file plot_Jpar-planet.py.
Referenced by EMfields3D.initDipole(), loopX(), loopY(), loopZ(), and EMfields3D.SetLambda().
z
tuple plot_Jpar-planet.z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
Definition at line 26 of file plot_Jpar-planet.py.
Referenced by add_moments_for_pcl(), add_moments_for_pcl_vec(), CG(), compute_moments(), drd(), drf(), Dvec4.Dvec4(), Grid3DCU.get_safe_cell_coordinates(), EMfields3D.initDipole(), EMfields3D.initDipole2D(), initialize_vector(), loopX(), loopY(), loopZ(), Collective.read_particles_restart(), EMfields3D.SetLambda(), EMfields3D.sumMoments(), EMfields3D.sumMoments_vectorized(), and EMfields3D.sumMomentsOld().
zc
plot_Jpar-planet.zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
Definition at line 29 of file plot_Jpar-planet.py.
Referenced by EMfields3D.initDipole(), EMfields3D.initDipole2D(), loopX(), loopY(), loopZ(), and EMfields3D.SetLambda().