iPIC3DxPEACE: plot1_paper-2_precipitation Namespace Reference
plot1_paper-2_precipitation Namespace Reference
Functions
def convF (lat)
def integral (Flux, binx_cent, biny_cent)
def Planck (x, T, n)
def Maxw (x, T, n)
def doubleMaxw (x, T1, n1, T2, n2)
Variables
data_address = sys.argv[1]
define input parameters ###
string save_name = 'map_PR1-minusBz_0-inf_xLiz'
int Nbinx = 50
int Nbiny = 25
list species = ['e','i']
string filter_region = ''
int ppc = 64.
int n_sw = 30.
float T_isw = 21.5
float T_esw = 21.5
float conv_di_to_cm = 23.7e5
float conv_wpi_to_s = 2.8e-3
from_VTK = fb.from_VTK(data_address)
silent
cycle = cycle[np.where(cycle<clim)]
x = x[np.where(cycle<clim)]
y = y[np.where(cycle<clim)]
z = z[np.where(cycle<clim)]
u = u[np.where(cycle<clim)]
v = v[np.where(cycle<clim)]
w = w[np.where(cycle<clim)]
q = q[np.where(cycle<clim)]
unpack
True
skiprows
int clim = cycle[0]+1000000
slow = np.where((u**2+v**2+w**2)<0.3)
dx = from_VTK.meta['dx']
dy = from_VTK.meta['dy']
dz = from_VTK.meta['dz']
dt = from_VTK.meta['dt']
xc = from_VTK.meta['xc']
yc = from_VTK.meta['yc']
zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
R = from_VTK.meta['R']
vth_e = from_VTK.meta['vths'][0]
vth_i = from_VTK.meta['vths'][1]
float rad_lim = 0.0
index_radiality = np.abs(x*u+y*v+z*w)/np.sqrt(x**2+y**2+z**2)/np.sqrt(u**2+v**2+w**2)
int theta = np.arctan2(np.sqrt(x**2+y**2),-z)*180./3.14
int phi = np.arctan2(y,x)*180./3.14
index_f = np.where((theta>160.)*(theta<170.)*(phi>-5.)*(phi<5.))
cycles = np.unique(cycle)
tuple Ekin = (u**2+v**2+w**2)
tuple Ekin_rad = (u*x+v*y+w*z)**2/(x**2+y**2+z**2)
index_q = np.where((q<0))
histo = plt.hist2d(phi[index_q],theta[index_q],bins=[Nbinx,Nbiny],range=[[-180,180],[0,180]])
Flux = histo[0]
Temp = np.zeros(np.shape(Flux))
Pram = np.zeros(np.shape(Flux))
Ener = np.zeros(np.shape(Flux))
ERad = np.zeros(np.shape(Flux))
binx_lim = histo[1]
biny_lim = histo[2]
binx_cen = np.zeros(int(Nbinx))
biny_cen = np.zeros(int(Nbiny))
index = np.where((q<0)*(phi<binx_lim[ix+1])*(phi>=binx_lim[ix])*(theta<biny_lim[iy+1])*(theta>=biny_lim[iy]))
Vavg_x = np.mean(u[index])
Vavg_y = np.mean(v[index])
Vavg_z = np.mean(w[index])
tuple Ekin_trasl = ((u[index]-Vavg_x)**2+(v[index]-Vavg_y)**2+(w[index]-Vavg_z)**2)
tuple lot = (binx_cen+180.)
int lat = biny_cen-90.
list files_names = []
ff = open(ff_name,'w')
string sep = ','
int ex = 2.*(np.pi*2.4e8)**2/Nbinx/Nbiny*abs(np.sin(llat*3.14/180.))
def Integral_Flux = integral(Flux,binx_cen,biny_cen)
PRINT INTEGRAL TOTAL ###.
Mean_Ener = np.nanmean(Ener)
PRINT MEAN ENERGY ###.
Mean_Ener1 = np.nanmean(Ekin[index_q])
Mean_Temp = np.nanmean(Temp)
Mean_Pram = np.nanmean(Pram)
Mean_ERad = np.nanmean(ERad)
x_axis = np.linspace(0,6e3,200)
PLOT D.F.
fontsize
histo_df = histo[0]
id_max = np.argmax(histo_df)
x_max = x_axis[id_max]
y_max = histo_df[id_max]
int y_fwhm = y_max/2.
x_array = histo[1]
popt
pcov
p0
chi2 = np.sum(((histo_df-doubleMaxw(x_array[1:],popt[0],popt[1],popt[2],popt[3]))**2)/histo_df)
label
loc
color
linestyle
format
Function Documentation
convF()
def plot1_paper-2_precipitation.convF (lat)
Definition at line 149 of file plot1_paper-2_precipitation.py.
def convF(lat):
    conv_pcls = n_sw*dx*dy*dz/ppc*(conv_di_to_cm**3)
    deltaT = len(cycles)*dt*(conv_wpi_to_s)
    deltaS = 2.*(np.pi*R*conv_di_to_cm)**2/Nbinx/Nbiny*abs(np.sin(lat*3.14/180.))
    return conv_pcls/deltaT/deltaS
# integrate flux over surface
doubleMaxw()
def plot1_paper-2_precipitation.doubleMaxw (x, T1, n1, T2, n2)
Definition at line 355 of file plot1_paper-2_precipitation.py.
        def doubleMaxw(x,T1,n1,T2,n2):
            return (n1*np.sqrt(x/T1)*np.exp(-x/T1)+n2*np.sqrt(x/T2)*np.exp(-x/T2))*2./np.sqrt(np.pi)
integral()
def plot1_paper-2_precipitation.integral (Flux, binx_cent, biny_cent)
Definition at line 156 of file plot1_paper-2_precipitation.py.
def integral(Flux,binx_cent,biny_cent):
    sum_Flux = 0.
    for iy,lat in enumerate(biny_cen):
        deltaS = 2.*(np.pi*R*conv_di_to_cm)**2/Nbinx/Nbiny*abs(np.sin(lat*3.14/180.))
        for ix,lon in enumerate(binx_cent):
            sum_Flux += np.sum(Flux[ix,iy])*Nbinx*deltaS
    return sum_Flux
# compute Flux (histogram)
Maxw()
def plot1_paper-2_precipitation.Maxw (x, T, n)
Definition at line 353 of file plot1_paper-2_precipitation.py.
        def Maxw(x,T,n):
            return n*np.sqrt(x/T)*np.exp(-x/T)*2./np.sqrt(np.pi)
Planck()
def plot1_paper-2_precipitation.Planck (x, T, n)
Definition at line 351 of file plot1_paper-2_precipitation.py.
        def Planck(x,T,n):
            return n*(x/T)**3/(np.exp(x/T)-1.)*15./(np.pi**4)
Variable Documentation
binx_cen
plot1_paper-2_precipitation.binx_cen = np.zeros(int(Nbinx))
Definition at line 187 of file plot1_paper-2_precipitation.py.
binx_lim
plot1_paper-2_precipitation.binx_lim = histo[1]
Definition at line 183 of file plot1_paper-2_precipitation.py.
biny_cen
plot1_paper-2_precipitation.biny_cen = np.zeros(int(Nbiny))
Definition at line 190 of file plot1_paper-2_precipitation.py.
biny_lim
plot1_paper-2_precipitation.biny_lim = histo[2]
Definition at line 184 of file plot1_paper-2_precipitation.py.
chi2
plot1_paper-2_precipitation.chi2 = np.sum(((histo_df-doubleMaxw(x_array[1:],popt[0],popt[1],popt[2],popt[3]))**2)/histo_df)
Definition at line 359 of file plot1_paper-2_precipitation.py.
clim
int plot1_paper-2_precipitation.clim = cycle[0]+1000000
Definition at line 31 of file plot1_paper-2_precipitation.py.
color
plot1_paper-2_precipitation.color
Definition at line 366 of file plot1_paper-2_precipitation.py.
conv_di_to_cm
float plot1_paper-2_precipitation.conv_di_to_cm = 23.7e5
Definition at line 19 of file plot1_paper-2_precipitation.py.
conv_wpi_to_s
float plot1_paper-2_precipitation.conv_wpi_to_s = 2.8e-3
Definition at line 20 of file plot1_paper-2_precipitation.py.
cycle
plot1_paper-2_precipitation.cycle = cycle[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
cycles
plot1_paper-2_precipitation.cycles = np.unique(cycle)
Definition at line 128 of file plot1_paper-2_precipitation.py.
data_address
plot1_paper-2_precipitation.data_address = sys.argv[1]
define input parameters ###
Definition at line 9 of file plot1_paper-2_precipitation.py.
dt
plot1_paper-2_precipitation.dt = from_VTK.meta['dt']
Definition at line 59 of file plot1_paper-2_precipitation.py.
dx
plot1_paper-2_precipitation.dx = from_VTK.meta['dx']
Definition at line 56 of file plot1_paper-2_precipitation.py.
dy
plot1_paper-2_precipitation.dy = from_VTK.meta['dy']
Definition at line 57 of file plot1_paper-2_precipitation.py.
dz
plot1_paper-2_precipitation.dz = from_VTK.meta['dz']
Definition at line 58 of file plot1_paper-2_precipitation.py.
Ekin
tuple plot1_paper-2_precipitation.Ekin = (u**2+v**2+w**2)
Definition at line 145 of file plot1_paper-2_precipitation.py.
Ekin_rad
tuple plot1_paper-2_precipitation.Ekin_rad = (u*x+v*y+w*z)**2/(x**2+y**2+z**2)
Definition at line 146 of file plot1_paper-2_precipitation.py.
Ekin_trasl
tuple plot1_paper-2_precipitation.Ekin_trasl = ((u[index]-Vavg_x)**2+(v[index]-Vavg_y)**2+(w[index]-Vavg_z)**2)
Definition at line 210 of file plot1_paper-2_precipitation.py.
Ener
plot1_paper-2_precipitation.Ener = np.zeros(np.shape(Flux))
Definition at line 179 of file plot1_paper-2_precipitation.py.
ERad
plot1_paper-2_precipitation.ERad = np.zeros(np.shape(Flux))
Definition at line 180 of file plot1_paper-2_precipitation.py.
ex
int plot1_paper-2_precipitation.ex = 2.*(np.pi*2.4e8)**2/Nbinx/Nbiny*abs(np.sin(llat*3.14/180.))
Definition at line 299 of file plot1_paper-2_precipitation.py.
ff
plot1_paper-2_precipitation.ff = open(ff_name,'w')
Definition at line 244 of file plot1_paper-2_precipitation.py.
Referenced by EMfields3D.ConstantChargeOpenBC(), EMfields3D.ConstantChargeOpenBCv2(), EMfields3D.ConstantChargePlanet(), and EMfields3D.ConstantChargePlanet2DPlaneXZ().
files_names
list plot1_paper-2_precipitation.files_names = []
Definition at line 234 of file plot1_paper-2_precipitation.py.
filter_region
string plot1_paper-2_precipitation.filter_region = ''
Definition at line 14 of file plot1_paper-2_precipitation.py.
Flux
plot1_paper-2_precipitation.Flux = histo[0]
Definition at line 171 of file plot1_paper-2_precipitation.py.
fontsize
plot1_paper-2_precipitation.fontsize
Definition at line 336 of file plot1_paper-2_precipitation.py.
format
plot1_paper-2_precipitation.format
Definition at line 375 of file plot1_paper-2_precipitation.py.
from_VTK
plot1_paper-2_precipitation.from_VTK = fb.from_VTK(data_address)
Definition at line 24 of file plot1_paper-2_precipitation.py.
histo
plot1_paper-2_precipitation.histo = plt.hist2d(phi[index_q],theta[index_q],bins=[Nbinx,Nbiny],range=[[-180,180],[0,180]])
Definition at line 170 of file plot1_paper-2_precipitation.py.
histo_df
plot1_paper-2_precipitation.histo_df = histo[0]
Definition at line 338 of file plot1_paper-2_precipitation.py.
id_max
plot1_paper-2_precipitation.id_max = np.argmax(histo_df)
Definition at line 339 of file plot1_paper-2_precipitation.py.
index
plot1_paper-2_precipitation.index = np.where((q<0)*(phi<binx_lim[ix+1])*(phi>=binx_lim[ix])*(theta<biny_lim[iy+1])*(theta>=biny_lim[iy]))
Definition at line 203 of file plot1_paper-2_precipitation.py.
index_f
plot1_paper-2_precipitation.index_f = np.where((theta>160.)*(theta<170.)*(phi>-5.)*(phi<5.))
Definition at line 91 of file plot1_paper-2_precipitation.py.
index_q
plot1_paper-2_precipitation.index_q = np.where((q<0))
Definition at line 167 of file plot1_paper-2_precipitation.py.
index_radiality
plot1_paper-2_precipitation.index_radiality = np.abs(x*u+y*v+z*w)/np.sqrt(x**2+y**2+z**2)/np.sqrt(u**2+v**2+w**2)
Definition at line 74 of file plot1_paper-2_precipitation.py.
Integral_Flux
plot1_paper-2_precipitation.Integral_Flux = integral(Flux,binx_cen,biny_cen)
PRINT INTEGRAL TOTAL ###.
Definition at line 320 of file plot1_paper-2_precipitation.py.
label
plot1_paper-2_precipitation.label
Definition at line 360 of file plot1_paper-2_precipitation.py.
lat
int plot1_paper-2_precipitation.lat = biny_cen-90.
Definition at line 228 of file plot1_paper-2_precipitation.py.
linestyle
plot1_paper-2_precipitation.linestyle
Definition at line 366 of file plot1_paper-2_precipitation.py.
loc
plot1_paper-2_precipitation.loc
Definition at line 364 of file plot1_paper-2_precipitation.py.
lot
tuple plot1_paper-2_precipitation.lot = (binx_cen+180.)
Definition at line 224 of file plot1_paper-2_precipitation.py.
Mean_Ener
plot1_paper-2_precipitation.Mean_Ener = np.nanmean(Ener)
PRINT MEAN ENERGY ###.
Definition at line 323 of file plot1_paper-2_precipitation.py.
Mean_Ener1
plot1_paper-2_precipitation.Mean_Ener1 = np.nanmean(Ekin[index_q])
Definition at line 324 of file plot1_paper-2_precipitation.py.
Mean_ERad
plot1_paper-2_precipitation.Mean_ERad = np.nanmean(ERad)
Definition at line 327 of file plot1_paper-2_precipitation.py.
Mean_Pram
plot1_paper-2_precipitation.Mean_Pram = np.nanmean(Pram)
Definition at line 326 of file plot1_paper-2_precipitation.py.
Mean_Temp
plot1_paper-2_precipitation.Mean_Temp = np.nanmean(Temp)
Definition at line 325 of file plot1_paper-2_precipitation.py.
n_sw
int plot1_paper-2_precipitation.n_sw = 30.
Definition at line 16 of file plot1_paper-2_precipitation.py.
Nbinx
int plot1_paper-2_precipitation.Nbinx = 50
Definition at line 11 of file plot1_paper-2_precipitation.py.
Nbiny
int plot1_paper-2_precipitation.Nbiny = 25
Definition at line 12 of file plot1_paper-2_precipitation.py.
p0
plot1_paper-2_precipitation.p0
Definition at line 358 of file plot1_paper-2_precipitation.py.
Referenced by Particles3D.pitch_angle_energy().
pcov
plot1_paper-2_precipitation.pcov
Definition at line 358 of file plot1_paper-2_precipitation.py.
phi
int plot1_paper-2_precipitation.phi = np.arctan2(y,x)*180./3.14
Definition at line 86 of file plot1_paper-2_precipitation.py.
popt
plot1_paper-2_precipitation.popt
Definition at line 358 of file plot1_paper-2_precipitation.py.
ppc
int plot1_paper-2_precipitation.ppc = 64.
Definition at line 15 of file plot1_paper-2_precipitation.py.
Pram
plot1_paper-2_precipitation.Pram = np.zeros(np.shape(Flux))
Definition at line 178 of file plot1_paper-2_precipitation.py.
q
plot1_paper-2_precipitation.q = q[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
Referenced by add_moments_for_pcl(), add_moments_for_pcl_vec(), compute_moments(), Collective.read_particles_restart(), EMfields3D.sumMoments(), EMfields3D.sumMoments_vectorized(), and EMfields3D.sumMomentsOld().
R
plot1_paper-2_precipitation.R = from_VTK.meta['R']
Definition at line 63 of file plot1_paper-2_precipitation.py.
Referenced by Particles3D.AddIonizedExosphere(), EMfields3D.ConstantChargePlanet(), EMfields3D.ConstantChargePlanet2DPlaneXZ(), Particles3D.deleteParticlesInsideSphere(), Particles3D.deleteParticlesInsideSphere2DPlaneXZ(), Particles3D.maxwellianDipole(), iPic3D::c_Solver.ParticlesMover(), Particles3D.rotateAndCountParticlesInsideSphere(), and Particles3D.rotateAndCountParticlesInsideSphere2DPlaneXZ().
rad_lim
float plot1_paper-2_precipitation.rad_lim = 0.0
Definition at line 73 of file plot1_paper-2_precipitation.py.
save_name
string plot1_paper-2_precipitation.save_name = 'map_PR1-minusBz_0-inf_xLiz'
Definition at line 10 of file plot1_paper-2_precipitation.py.
sep
string plot1_paper-2_precipitation.sep = ','
Definition at line 284 of file plot1_paper-2_precipitation.py.
silent
plot1_paper-2_precipitation.silent
Definition at line 25 of file plot1_paper-2_precipitation.py.
skiprows
plot1_paper-2_precipitation.skiprows
Definition at line 28 of file plot1_paper-2_precipitation.py.
slow
plot1_paper-2_precipitation.slow = np.where((u**2+v**2+w**2)<0.3)
Definition at line 42 of file plot1_paper-2_precipitation.py.
species
list plot1_paper-2_precipitation.species = ['e','i']
Definition at line 13 of file plot1_paper-2_precipitation.py.
T_esw
float plot1_paper-2_precipitation.T_esw = 21.5
Definition at line 18 of file plot1_paper-2_precipitation.py.
T_isw
float plot1_paper-2_precipitation.T_isw = 21.5
Definition at line 17 of file plot1_paper-2_precipitation.py.
Temp
plot1_paper-2_precipitation.Temp = np.zeros(np.shape(Flux))
Definition at line 177 of file plot1_paper-2_precipitation.py.
theta
int plot1_paper-2_precipitation.theta = np.arctan2(np.sqrt(x**2+y**2),-z)*180./3.14
Definition at line 85 of file plot1_paper-2_precipitation.py.
True
plot1_paper-2_precipitation.True
Definition at line 28 of file plot1_paper-2_precipitation.py.
u
plot1_paper-2_precipitation.u = u[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
Referenced by add_moments_for_pcl(), add_moments_for_pcl_vec(), compute_moments(), Collective.read_particles_restart(), sample_maxwellian(), sample_standard_maxwellian(), EMfields3D.sumMoments(), EMfields3D.sumMoments_vectorized(), and EMfields3D.sumMomentsOld().
unpack
plot1_paper-2_precipitation.unpack
Definition at line 28 of file plot1_paper-2_precipitation.py.
v
plot1_paper-2_precipitation.v = v[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
Referenced by ConfigFile.add(), add_moments_for_pcl(), add_moments_for_pcl_vec(), CG(), compute_moments(), Collective.read_particles_restart(), sample_maxwellian(), sample_standard_maxwellian(), EMfields3D.sumMoments(), EMfields3D.sumMoments_vectorized(), and EMfields3D.sumMomentsOld().
Vavg_x
plot1_paper-2_precipitation.Vavg_x = np.mean(u[index])
Definition at line 207 of file plot1_paper-2_precipitation.py.
Vavg_y
plot1_paper-2_precipitation.Vavg_y = np.mean(v[index])
Definition at line 208 of file plot1_paper-2_precipitation.py.
Vavg_z
plot1_paper-2_precipitation.Vavg_z = np.mean(w[index])
Definition at line 209 of file plot1_paper-2_precipitation.py.
vth_e
plot1_paper-2_precipitation.vth_e = from_VTK.meta['vths'][0]
Definition at line 64 of file plot1_paper-2_precipitation.py.
vth_i
plot1_paper-2_precipitation.vth_i = from_VTK.meta['vths'][1]
Definition at line 65 of file plot1_paper-2_precipitation.py.
w
plot1_paper-2_precipitation.w = w[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
Referenced by add_moments_for_pcl(), add_moments_for_pcl_vec(), compute_moments(), GMRES(), Collective.read_particles_restart(), sample_maxwellian(), sample_standard_maxwellian(), EMfields3D.sumMoments(), EMfields3D.sumMoments_vectorized(), and EMfields3D.sumMomentsOld().
x
tuple plot1_paper-2_precipitation.x = x[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
x_array
plot1_paper-2_precipitation.x_array = histo[1]
Definition at line 349 of file plot1_paper-2_precipitation.py.
x_axis
plot1_paper-2_precipitation.x_axis = np.linspace(0,6e3,200)
PLOT D.F.
ENERGY WHOLE REGION ###
Definition at line 335 of file plot1_paper-2_precipitation.py.
x_max
plot1_paper-2_precipitation.x_max = x_axis[id_max]
Definition at line 340 of file plot1_paper-2_precipitation.py.
xc
plot1_paper-2_precipitation.xc = from_VTK.meta['xc']
Definition at line 60 of file plot1_paper-2_precipitation.py.
y
tuple plot1_paper-2_precipitation.y = y[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
y_fwhm
int plot1_paper-2_precipitation.y_fwhm = y_max/2.
Definition at line 342 of file plot1_paper-2_precipitation.py.
y_max
plot1_paper-2_precipitation.y_max = histo_df[id_max]
Definition at line 341 of file plot1_paper-2_precipitation.py.
yc
plot1_paper-2_precipitation.yc = from_VTK.meta['yc']
Definition at line 61 of file plot1_paper-2_precipitation.py.
z
tuple plot1_paper-2_precipitation.z = z[np.where(cycle<clim)]
Definition at line 28 of file plot1_paper-2_precipitation.py.
zc
plot1_paper-2_precipitation.zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
Definition at line 62 of file plot1_paper-2_precipitation.py.