iPIC3DxPEACE: include/debug.h File Reference
debug.h File Reference
#include <cstdarg>
#include <cstdio>
#include "errors.h"
Macros
#define dprintf(args...) fprintf_fileLine(stdout, "DEBUG", __func__, __FILE__, __LINE__,## args)
#define dprint(var) printvar_fileLine(__func__, __FILE__,__LINE__,#var,var);
#define declare_dprintvar_fileLine(type) void printvar_fileLine(const char*,const char*,int,const char*,type);
Functions
void fprintf_fileLine (FILE *fptr, const char *type, const char *func, const char *file, int line_number, const char *format,...)
declare_dprintvar_fileLine (int)
declare_dprintvar_fileLine (long long)
declare_dprintvar_fileLine (double)
declare_dprintvar_fileLine (const char *)
declare_dprintvar_fileLine (const void *)
Macro Definition Documentation
declare_dprintvar_fileLine
#define declare_dprintvar_fileLine (type) void printvar_fileLine(const char*,const char*,int,const char*,type);
Definition at line 37 of file debug.h.
dprint
#define dprint (var) printvar_fileLine(__func__, __FILE__,__LINE__,#var,var);
Definition at line 36 of file debug.h.
dprintf
#define dprintf (args...) fprintf_fileLine(stdout, "DEBUG", __func__, __FILE__, __LINE__,## args)
Definition at line 35 of file debug.h.
Function Documentation
declare_dprintvar_fileLine() [1/5]
declare_dprintvar_fileLine (const char *)
declare_dprintvar_fileLine() [2/5]
declare_dprintvar_fileLine (const void *)
declare_dprintvar_fileLine() [3/5]
declare_dprintvar_fileLine (double)
declare_dprintvar_fileLine() [4/5]
declare_dprintvar_fileLine (int)
declare_dprintvar_fileLine() [5/5]
declare_dprintvar_fileLine (long long)
fprintf_fileLine()
void fprintf_fileLine (FILE * fptr, const char * type, const char * func, const char * file, int line_number, const char * format, ...)
Definition at line 101 of file debug.cpp.
{
  //if(MPIdata::get_rank()) return;
  // writing directly to fptr would avoid limiting the length
  // of the output string, but by first writing to a string
  // we achieve thread safety.
  //
  // write the message to a string.
  //
  const int maxchars = 1024;
  char error_msg[maxchars+2];
  // identify the process and thread
  char process_thread_str[20];
  #ifndef NO_MPI
    #ifdef _OPENMP
      snprintf(process_thread_str, 20, "(%d.%d) ",
        MPIdata::get_rank(), omp_get_thread_num());
    #else
      snprintf(process_thread_str, 20, "(%d)",
        MPIdata::get_rank());
    #endif
  #else
    #ifdef _OPENMP
      snprintf(process_thread_str, 20, "(.%d) ",
        omp_get_thread_num());
    #else
      snprintf(process_thread_str, 20, "");
    #endif
  #endif
  char *sptr = error_msg;
  int chars_so_far=0;
  va_list args;
  va_start(args, format);
  chars_so_far = snprintf(sptr, maxchars,
    "%s%s %s(), %s:%d: ",
    process_thread_str,
    type,
    func, /*file,*/ my_basename(file),
    line_number);
  /* print out remainder of message */
  chars_so_far += vsnprintf(sptr+chars_so_far, maxchars-chars_so_far, format, args);
  va_end(args);
  sprintf(sptr+chars_so_far, "\n");
  // print the message
  fflush(fptr);
  fprintf(fptr,"%s",error_msg);
  fflush(fptr);
}
References print_planet_main::args, plot1_paper_nBJ::format, MPIdata::get_rank(), my_basename(), and omp_get_thread_num().