iPIC3DxPEACE: vtk_routines Namespace Reference
vtk_routines Namespace Reference
Classes
class from_vtk
Functions
def open_vtk_scal (file_path)
def open_vtk_vect (file_path)
def convert_vtk_scal (data_file)
def convert_vtk_vect (data_file, string)
def print_vtk (field, output_path, tar_name, dl, digits=None)
def print_vtk_scal (field, output_path, tar_name, dl, digits='%.9f')
def print_vtk_vect (field, output_path, tar_name, dl, digits_x='%.7f', digits_y='%.7f', digits_z='%.7f')
Function Documentation
convert_vtk_scal()
def vtk_routines.convert_vtk_scal (data_file)
Definition at line 30 of file vtk_routines.py.
def convert_vtk_scal(data_file):
        data = VN.vtk_to_numpy(data_file.GetPointData().GetScalars())
        dims = data_file.GetDimensions()
        data = data.reshape(dims[2],dims[1],dims[0]) # need to regive the right shape to np.array because VN givs it flatten
        data = data.transpose(2,1,0)
        return np.array(data)
Referenced by print_planet_routines.unpack().
convert_vtk_vect()
def vtk_routines.convert_vtk_vect (data_file, string)
Definition at line 40 of file vtk_routines.py.
                           string):     # string with the name of the array we want to unpack, e.g. B,E,Ji,Je
    data = VN.vtk_to_numpy(data_file.GetPointData().GetArray(string))
    dims = data_file.GetDimensions()
    data_x = data[:,0].reshape(dims[2],dims[1],dims[0])
    data_y = data[:,1].reshape(dims[2],dims[1],dims[0])
    data_z = data[:,2].reshape(dims[2],dims[1],dims[0])
    data_x = data_x.transpose(2,1,0)
    data_y = data_y.transpose(2,1,0)
    data_z = data_z.transpose(2,1,0)
    return np.array([data_x, data_y, data_z])
Referenced by print_planet_routines.unpack().
open_vtk_scal()
def vtk_routines.open_vtk_scal (file_path)
Definition at line 8 of file vtk_routines.py.
def open_vtk_scal(file_path):
    reader = vtk.vtkStructuredPointsReader()
    reader.SetFileName(file_path)
    reader.ReadAllScalarsOn()
    reader.Update()
    return reader.GetOutput()
# open vtk vector file and prepare it for conversion to numpy array
Referenced by print_planet_routines.main().
open_vtk_vect()
def vtk_routines.open_vtk_vect (file_path)
Definition at line 19 of file vtk_routines.py.
def open_vtk_vect(file_path):
    reader = vtk.vtkStructuredPointsReader()
    reader.SetFileName(file_path)
    reader.ReadAllVectorsOn()
    reader.Update()
    return reader.GetOutput()
# conversion to numpy array
Referenced by print_planet_routines.main().
print_vtk()
def vtk_routines.print_vtk (field, output_path, tar_name, dl, digits = None)
Definition at line 58 of file vtk_routines.py.
              digits=None):             # z format you will use for printing
    if len(dl)!=3:
        print('Either your field is not 3D, either your dl is wrong')
        return 0
    shape = np.shape(field)
    if (len(shape)<3) or (len(shape)>4):
        print('Your input field is incorrect.')
        print('Your field must scale either as a scalar field (shape=[nx,ny,nz]), either as a vector field (shape=[3,nx,ny,nz]).')
        return 0
    elif len(shape)==3:
        if digits is not None:
            print_vtk_scal(field,output_path,tar_name,dl,digits=digits)
        else:
            print_vtk_scal(field,output_path,tar_name,dl)
    elif len(shape)==4:
        if shape[0]!=3:
            print('The field format is wrong. Field must be an array of shape=[3,nx,ny,nz].')
        else:
            if digits is not None:
                print_vtk_vect(field,output_path,tar_name,dl,digits_x=digits,digits_y=digits,digits_z=digits)
            else:
                print_vtk_vect(field,output_path,tar_name,dl)
    else:
        print('If you have this message, it means you found a totally unexpected bug in my routine.')
        print('Congratulation!')
        print("Can you please tell me what you've done?")
    return 0
References print_vtk_scal(), and print_vtk_vect().
print_vtk_scal()
def vtk_routines.print_vtk_scal (field, output_path, tar_name, dl, digits = '%.9f')
Definition at line 99 of file vtk_routines.py.
                   digits = '%.9f'):    # z format you will use for printing
    #determine the coefficients
    nx,ny,nz = np.shape(field)
    dx = dl[0]
    dy = dl[1]
    dz = dl[2]
    wf = open(output_path, 'w')
    wf.write('# vtk DataFile Version 1.0 \n')
    wf.write(tar_name+'\n')
    wf.write('ASCII'+'\n')
    wf.write('DATASET STRUCTURED_POINTS'+'\n')
    wf.write('DIMENSIONS'+' '+str(nx)+' '+str(ny)+' '+str(nz)+'\n')
    wf.write('ORIGIN  0.0  0.0  0.0'+'\n')
    wf.write('SPACING'+' '+str(dx)+' '+str(dy)+' '+str(dz)+'\n')
    wf.write('                '+'\n')
    wf.write('POINT_DATA'+' '+str(nx*ny*nz)+'\n')
    wf.write('SCALARS    '+tar_name+'    float  1'+'\n')
    wf.write('LOOKUP_TABLE default'+'\n')
    for iz in range(0, nz):
        #print the first time in y
        for iy in range(0, ny):
            for ix in range(0, nx):
                to_write = digits %field[ix,iy,iz]
                wf.write(to_write+'\n')
    wf.close()
    print('done with the print!'+output_path)
    return 0
References plot2_paper_df.range.
Referenced by print_vtk().
print_vtk_vect()
def vtk_routines.print_vtk_vect (field, output_path, tar_name, dl, digits_x = '%.7f', digits_y = '%.7f', digits_z = '%.7f')
Definition at line 137 of file vtk_routines.py.
                   digits_z = '%.7f'):  # z format you will use for printing
    #determine the coefficients
    nx,ny,nz = np.shape(field[0,...])
    dx = dl[0]
    dy = dl[1]
    dz = dl[2]
    wf = open(output_path, 'w')
    wf.write('# vtk DataFile Version 1.0 \n')
    wf.write(tar_name+'\n')
    wf.write('ASCII'+'\n')
    wf.write('DATASET STRUCTURED_POINTS \n')
    wf.write('DIMENSIONS'+' '+str(nx)+' '+str(ny)+' '+str(nz)+'\n')
    wf.write('ORIGIN  0.0  0.0  0.0'+'\n')
    wf.write('SPACING'+' '+str(dx)+' '+str(dy)+' '+str(dz)+'\n')
    wf.write('                '+'\n')
    wf.write('POINT_DATA'+' '+str(nx*ny*nz)+'\n')
    wf.write('VECTORS    '+tar_name+'    float'+'\n')
    for iz in range(0, nz):
        #print the first time in y
        for iy in range(0, ny):
            for ix in range(0, nx):
                to_write_x = digits_x %field[0,ix,iy,iz]
                to_write_y = digits_y %field[1,ix,iy,iz]
                to_write_z = digits_z %field[2,ix,iy,iz]
                wf.write(to_write_x+' \t'+to_write_y+' \t'+to_write_z+'\n')
    wf.close()
    print('done with the print!'+output_path)
    return 0
#---------------------------------------------------------------------------------------
References plot2_paper_df.range.
Referenced by print_vtk().