iPIC3DxPEACE: plot1_paper_nBJ Namespace Reference
plot1_paper_nBJ Namespace Reference
Functions
def scalr (a)
Variables
data_address = sys.argv[1]
int cycle_min = 6000
int cycle_max = 6700
int d_cycle = 100
list xlim = [4.1,-6.1]
list ylim = [4.1,-4.1]
list zlim = [-4.1,4.1]
int conv_B = 20./0.00562
conv_J = -(4.*np.pi*30.)*(400./0.027)*(0.16)
int conv_N = 30.
from_VTK = fb.from_VTK(data_address)
silent
x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
xc = from_VTK.meta['xc']
yc = from_VTK.meta['yc']
zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
list ix = [np.argmin(abs(x-xlim[0])), np.argmin(abs(x-xlim[1]))]
list iy = [np.argmin(abs(y-ylim[0])), np.argmin(abs(y-ylim[1]))]
list iz = [np.argmin(abs(z-zlim[0])), np.argmin(abs(z-zlim[1]))]
theta = np.linspace(-np.pi/1.1,np.pi/1.1,10000)
float Rmp = 1.45*(2./(1.+np.cos(theta)))**(0.5)
float Rbs = 2.75*1.04/(1+1.04*np.cos(theta))
float x_mp = Rmp*np.cos(theta)
float y_mp = Rmp*np.sin(theta)
float z_mp = 0.2+Rmp*np.sin(theta)
float x_bs = 0.5+Rbs*np.cos(theta)
float y_bs = Rbs*np.sin(theta)
float z_bs = 0.2+Rbs*np.sin(theta)
tuple inside_mp = (x_mp<max(x))*(x_mp>min(x))*(y_mp<max(y))*(y_mp>min(y))*(z_mp<max(z))*(z_mp>min(z))
tuple inside_bs = (x_bs<max(x))*(x_bs>min(x))*(y_bs<max(y))*(y_bs>min(y))*(z_bs<max(z))*(z_bs>min(z))
float xx_mp = x_mp[inside_mp]
float yy_mp = y_mp[inside_mp]
float zz_mp = z_mp[inside_mp]
float xx_bs = x_bs[inside_bs]
float yy_bs = y_bs[inside_bs]
float zz_bs = z_bs[inside_bs]
int Bdp = conv_B*scalr(from_VTK.get_vect(from_VTK.meta['name']+'_Bdp_%i'%cycle,cycle,fibo_obj=None,tar_var='B'))
int Beq = conv_B*scalr(from_VTK.get_vect(from_VTK.meta['name']+'_Beq_%i'%cycle,cycle,fibo_obj=None,tar_var='B'))
Jidp = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jidp_%i'%cycle,cycle,fibo_obj=None,tar_var='Ji')[1]
Jedp = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jedp_%i'%cycle,cycle,fibo_obj=None,tar_var='Je')[1]
Jdp = Jidp + Jedp
Jieq = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jieq_%i'%cycle,cycle,fibo_obj=None,tar_var='Ji')[1]
Jeeq = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jeeq_%i'%cycle,cycle,fibo_obj=None,tar_var='Je')[1]
Jeq = Jieq + Jeeq
int Ndp = conv_N*from_VTK.get_scal(from_VTK.meta['name']+'_rhoi1dp_%i'%cycle,cycle,fibo_obj=None,tar_var='rhoi1')
int Neq = conv_N*from_VTK.get_scal(from_VTK.meta['name']+'_rhoi1eq_%i'%cycle,cycle,fibo_obj=None,tar_var='rhoi1')
iz_cut = int(len(Bdp[0,0,:])/2)
int B_cut = Bdp[ix[0]:ix[1],0,iz_cut]
Ji_cut = Jidp[ix[0]:ix[1],0,iz_cut]
Je_cut = Jedp[ix[0]:ix[1],0,iz_cut]
int N_cut = Ndp[ix[0]:ix[1],0,iz_cut]
fig = plt.figure(figsize=(17,10))
fontsize
ax = fig.add_subplot(231)
im1 = plt.imshow(np.transpose(Ndp[ix[0]:ix[1],0,iz[0]:iz[1]]), cmap='jet', origin='lower', norm=colors.LogNorm(vmin=1., vmax=120.), extent=(max(x),min(x),min(z),max(z)), aspect=1)
linestyle
color
w1 = Wedge((0.,0.), 1., 90., 270., fc='black')
w2 = Wedge((0.,0.), 1., 270., 90., fc='grey')
cmap
origin
norm
extent
aspect
im2 = plt.imshow(np.transpose(Bdp[ix[0]:ix[1],0,iz[0]:iz[1]]), cmap='seismic', origin='lower', norm=colors.LogNorm(vmin=1e-1, vmax=1e3), extent=(max(x),min(x),min(z),max(z)), aspect=1)
im3 = plt.imshow(np.transpose(Jdp[ix[0]:ix[1],0,iz[0]:iz[1]]), cmap='seismic', origin='lower', extent=(max(x),min(x),min(z),max(z)), aspect=1)
cax1 = fig.add_axes([0.128, 0.05, 0.237, 0.015])
cbar = plt.colorbar(im1, cax=cax1, orientation='horizontal')
labelsize
cax2 = fig.add_axes([0.395, 0.05, 0.237, 0.015])
cax3 = fig.add_axes([0.668, 0.05, 0.237, 0.015])
wspace
hspace
cycle
format
Function Documentation
scalr()
def plot1_paper_nBJ.scalr (a)
Definition at line 41 of file plot1_paper_nBJ.py.
def scalr(a):
    return np.sqrt(a[0]**2+a[1]**2+a[2]**2)
Variable Documentation
aspect
plot1_paper_nBJ.aspect
Definition at line 104 of file plot1_paper_nBJ.py.
ax
plot1_paper_nBJ.ax = fig.add_subplot(231)
Definition at line 90 of file plot1_paper_nBJ.py.
B_cut
int plot1_paper_nBJ.B_cut = Bdp[ix[0]:ix[1],0,iz_cut]
Definition at line 79 of file plot1_paper_nBJ.py.
Bdp
int plot1_paper_nBJ.Bdp = conv_B*scalr(from_VTK.get_vect(from_VTK.meta['name']+'_Bdp_%i'%cycle,cycle,fibo_obj=None,tar_var='B'))
Definition at line 66 of file plot1_paper_nBJ.py.
Beq
int plot1_paper_nBJ.Beq = conv_B*scalr(from_VTK.get_vect(from_VTK.meta['name']+'_Beq_%i'%cycle,cycle,fibo_obj=None,tar_var='B'))
Definition at line 67 of file plot1_paper_nBJ.py.
cax1
plot1_paper_nBJ.cax1 = fig.add_axes([0.128, 0.05, 0.237, 0.015])
Definition at line 203 of file plot1_paper_nBJ.py.
cax2
plot1_paper_nBJ.cax2 = fig.add_axes([0.395, 0.05, 0.237, 0.015])
Definition at line 206 of file plot1_paper_nBJ.py.
cax3
plot1_paper_nBJ.cax3 = fig.add_axes([0.668, 0.05, 0.237, 0.015])
Definition at line 209 of file plot1_paper_nBJ.py.
cbar
plot1_paper_nBJ.cbar = plt.colorbar(im1, cax=cax1, orientation='horizontal')
Definition at line 204 of file plot1_paper_nBJ.py.
cmap
plot1_paper_nBJ.cmap
Definition at line 104 of file plot1_paper_nBJ.py.
color
plot1_paper_nBJ.color
Definition at line 92 of file plot1_paper_nBJ.py.
conv_B
int plot1_paper_nBJ.conv_B = 20./0.00562
Definition at line 19 of file plot1_paper_nBJ.py.
conv_J
plot1_paper_nBJ.conv_J = -(4.*np.pi*30.)*(400./0.027)*(0.16)
Definition at line 20 of file plot1_paper_nBJ.py.
conv_N
int plot1_paper_nBJ.conv_N = 30.
Definition at line 21 of file plot1_paper_nBJ.py.
cycle
plot1_paper_nBJ.cycle
Definition at line 215 of file plot1_paper_nBJ.py.
cycle_max
int plot1_paper_nBJ.cycle_max = 6700
Definition at line 12 of file plot1_paper_nBJ.py.
cycle_min
int plot1_paper_nBJ.cycle_min = 6000
Definition at line 11 of file plot1_paper_nBJ.py.
d_cycle
int plot1_paper_nBJ.d_cycle = 100
Definition at line 13 of file plot1_paper_nBJ.py.
data_address
plot1_paper_nBJ.data_address = sys.argv[1]
Definition at line 10 of file plot1_paper_nBJ.py.
extent
plot1_paper_nBJ.extent
Definition at line 104 of file plot1_paper_nBJ.py.
fig
plot1_paper_nBJ.fig = plt.figure(figsize=(17,10))
Definition at line 86 of file plot1_paper_nBJ.py.
fontsize
plot1_paper_nBJ.fontsize
Definition at line 88 of file plot1_paper_nBJ.py.
format
plot1_paper_nBJ.format
Definition at line 215 of file plot1_paper_nBJ.py.
Referenced by dfprintf_fileLine(), eprintf_fileLine(), and fprintf_fileLine().
from_VTK
plot1_paper_nBJ.from_VTK = fb.from_VTK(data_address)
Definition at line 24 of file plot1_paper_nBJ.py.
hspace
plot1_paper_nBJ.hspace
Definition at line 214 of file plot1_paper_nBJ.py.
im1
plot1_paper_nBJ.im1 = plt.imshow(np.transpose(Ndp[ix[0]:ix[1],0,iz[0]:iz[1]]), cmap='jet', origin='lower', norm=colors.LogNorm(vmin=1., vmax=120.), extent=(max(x),min(x),min(z),max(z)), aspect=1)
Definition at line 91 of file plot1_paper_nBJ.py.
im2
plot1_paper_nBJ.im2 = plt.imshow(np.transpose(Bdp[ix[0]:ix[1],0,iz[0]:iz[1]]), cmap='seismic', origin='lower', norm=colors.LogNorm(vmin=1e-1, vmax=1e3), extent=(max(x),min(x),min(z),max(z)), aspect=1)
Definition at line 129 of file plot1_paper_nBJ.py.
im3
plot1_paper_nBJ.im3 = plt.imshow(np.transpose(Jdp[ix[0]:ix[1],0,iz[0]:iz[1]]), cmap='seismic', origin='lower', extent=(max(x),min(x),min(z),max(z)), aspect=1)
Definition at line 165 of file plot1_paper_nBJ.py.
inside_bs
tuple plot1_paper_nBJ.inside_bs = (x_bs<max(x))*(x_bs>min(x))*(y_bs<max(y))*(y_bs>min(y))*(z_bs<max(z))*(z_bs>min(z))
Definition at line 53 of file plot1_paper_nBJ.py.
inside_mp
tuple plot1_paper_nBJ.inside_mp = (x_mp<max(x))*(x_mp>min(x))*(y_mp<max(y))*(y_mp>min(y))*(z_mp<max(z))*(z_mp>min(z))
Definition at line 52 of file plot1_paper_nBJ.py.
ix
list plot1_paper_nBJ.ix = [np.argmin(abs(x-xlim[0])), np.argmin(abs(x-xlim[1]))]
Definition at line 35 of file plot1_paper_nBJ.py.
Referenced by get_field_components_for_cell(), Particles3D.mover_PC(), NBDerivedHaloComm(), EMfields3D.sumMoments(), EMfields3D.sumMoments_AoS(), EMfields3D.sumMoments_AoS_intr(), EMfields3D.sumMoments_vectorized(), EMfields3D.sumMoments_vectorized_AoS(), EMfields3D.sumMomentsOld(), WriteFieldsVTK(), WriteFieldsVTKNonblk(), WriteMomentsVTK(), and WriteMomentsVTKNonblk().
iy
list plot1_paper_nBJ.iy = [np.argmin(abs(y-ylim[0])), np.argmin(abs(y-ylim[1]))]
Definition at line 36 of file plot1_paper_nBJ.py.
Referenced by get_field_components_for_cell(), Particles3D.mover_PC(), NBDerivedHaloComm(), EMfields3D.sumMoments(), EMfields3D.sumMoments_AoS(), EMfields3D.sumMoments_AoS_intr(), EMfields3D.sumMoments_vectorized(), EMfields3D.sumMoments_vectorized_AoS(), EMfields3D.sumMomentsOld(), WriteFieldsVTK(), WriteFieldsVTKNonblk(), WriteMomentsVTK(), and WriteMomentsVTKNonblk().
iz
list plot1_paper_nBJ.iz = [np.argmin(abs(z-zlim[0])), np.argmin(abs(z-zlim[1]))]
Definition at line 37 of file plot1_paper_nBJ.py.
Referenced by get_field_components_for_cell(), Particles3D.mover_PC(), NBDerivedHaloComm(), EMfields3D.sumMoments(), EMfields3D.sumMoments_AoS(), EMfields3D.sumMoments_AoS_intr(), EMfields3D.sumMoments_vectorized(), EMfields3D.sumMoments_vectorized_AoS(), EMfields3D.sumMomentsOld(), WriteFieldsVTK(), WriteFieldsVTKNonblk(), WriteMomentsVTK(), and WriteMomentsVTKNonblk().
iz_cut
plot1_paper_nBJ.iz_cut = int(len(Bdp[0,0,:])/2)
Definition at line 78 of file plot1_paper_nBJ.py.
Jdp
plot1_paper_nBJ.Jdp = Jidp + Jedp
Definition at line 70 of file plot1_paper_nBJ.py.
Je_cut
plot1_paper_nBJ.Je_cut = Jedp[ix[0]:ix[1],0,iz_cut]
Definition at line 82 of file plot1_paper_nBJ.py.
Jedp
plot1_paper_nBJ.Jedp = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jedp_%i'%cycle,cycle,fibo_obj=None,tar_var='Je')[1]
Definition at line 69 of file plot1_paper_nBJ.py.
Jeeq
plot1_paper_nBJ.Jeeq = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jeeq_%i'%cycle,cycle,fibo_obj=None,tar_var='Je')[1]
Definition at line 72 of file plot1_paper_nBJ.py.
Jeq
plot1_paper_nBJ.Jeq = Jieq + Jeeq
Definition at line 73 of file plot1_paper_nBJ.py.
Ji_cut
plot1_paper_nBJ.Ji_cut = Jidp[ix[0]:ix[1],0,iz_cut]
Definition at line 81 of file plot1_paper_nBJ.py.
Jidp
plot1_paper_nBJ.Jidp = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jidp_%i'%cycle,cycle,fibo_obj=None,tar_var='Ji')[1]
Definition at line 68 of file plot1_paper_nBJ.py.
Jieq
plot1_paper_nBJ.Jieq = conv_J*from_VTK.get_vect(from_VTK.meta['name']+'_Jieq_%i'%cycle,cycle,fibo_obj=None,tar_var='Ji')[1]
Definition at line 71 of file plot1_paper_nBJ.py.
labelsize
plot1_paper_nBJ.labelsize
Definition at line 205 of file plot1_paper_nBJ.py.
linestyle
plot1_paper_nBJ.linestyle
Definition at line 92 of file plot1_paper_nBJ.py.
N_cut
int plot1_paper_nBJ.N_cut = Ndp[ix[0]:ix[1],0,iz_cut]
Definition at line 83 of file plot1_paper_nBJ.py.
Ndp
int plot1_paper_nBJ.Ndp = conv_N*from_VTK.get_scal(from_VTK.meta['name']+'_rhoi1dp_%i'%cycle,cycle,fibo_obj=None,tar_var='rhoi1')
Definition at line 74 of file plot1_paper_nBJ.py.
Neq
int plot1_paper_nBJ.Neq = conv_N*from_VTK.get_scal(from_VTK.meta['name']+'_rhoi1eq_%i'%cycle,cycle,fibo_obj=None,tar_var='rhoi1')
Definition at line 75 of file plot1_paper_nBJ.py.
norm
plot1_paper_nBJ.norm
Definition at line 104 of file plot1_paper_nBJ.py.
origin
plot1_paper_nBJ.origin
Definition at line 104 of file plot1_paper_nBJ.py.
Rbs
float plot1_paper_nBJ.Rbs = 2.75*1.04/(1+1.04*np.cos(theta))
Definition at line 45 of file plot1_paper_nBJ.py.
Rmp
float plot1_paper_nBJ.Rmp = 1.45*(2./(1.+np.cos(theta)))**(0.5)
Definition at line 44 of file plot1_paper_nBJ.py.
silent
plot1_paper_nBJ.silent
Definition at line 25 of file plot1_paper_nBJ.py.
theta
plot1_paper_nBJ.theta = np.linspace(-np.pi/1.1,np.pi/1.1,10000)
Definition at line 43 of file plot1_paper_nBJ.py.
Referenced by Particles3D.delta_f(), EMfields3D.initEM_rotate(), loopX(), loopY(), loopZ(), Particles3D.rotateAndCountParticlesInsideSphere(), Particles3D.rotateAndCountParticlesInsideSphere2DPlaneXZ(), Particles3D.RotatePlaneXY(), and sample_standard_maxwellian().
w1
plot1_paper_nBJ.w1 = Wedge((0.,0.), 1., 90., 270., fc='black')
Definition at line 94 of file plot1_paper_nBJ.py.
w2
plot1_paper_nBJ.w2 = Wedge((0.,0.), 1., 270., 90., fc='grey')
Definition at line 95 of file plot1_paper_nBJ.py.
wspace
plot1_paper_nBJ.wspace
Definition at line 214 of file plot1_paper_nBJ.py.
x
tuple plot1_paper_nBJ.x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
Definition at line 26 of file plot1_paper_nBJ.py.
x_bs
float plot1_paper_nBJ.x_bs = 0.5+Rbs*np.cos(theta)
Definition at line 49 of file plot1_paper_nBJ.py.
x_mp
float plot1_paper_nBJ.x_mp = Rmp*np.cos(theta)
Definition at line 46 of file plot1_paper_nBJ.py.
xc
plot1_paper_nBJ.xc = from_VTK.meta['xc']
Definition at line 29 of file plot1_paper_nBJ.py.
xlim
list plot1_paper_nBJ.xlim = [4.1,-6.1]
Definition at line 14 of file plot1_paper_nBJ.py.
xx_bs
plot1_paper_nBJ.xx_bs = x_bs[inside_bs]
Definition at line 57 of file plot1_paper_nBJ.py.
xx_mp
plot1_paper_nBJ.xx_mp = x_mp[inside_mp]
Definition at line 54 of file plot1_paper_nBJ.py.
y
tuple plot1_paper_nBJ.y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
Definition at line 27 of file plot1_paper_nBJ.py.
y_bs
float plot1_paper_nBJ.y_bs = Rbs*np.sin(theta)
Definition at line 50 of file plot1_paper_nBJ.py.
y_mp
float plot1_paper_nBJ.y_mp = Rmp*np.sin(theta)
Definition at line 47 of file plot1_paper_nBJ.py.
yc
plot1_paper_nBJ.yc = from_VTK.meta['yc']
Definition at line 30 of file plot1_paper_nBJ.py.
ylim
list plot1_paper_nBJ.ylim = [4.1,-4.1]
Definition at line 15 of file plot1_paper_nBJ.py.
yy_bs
plot1_paper_nBJ.yy_bs = y_bs[inside_bs]
Definition at line 58 of file plot1_paper_nBJ.py.
yy_mp
plot1_paper_nBJ.yy_mp = y_mp[inside_mp]
Definition at line 55 of file plot1_paper_nBJ.py.
z
tuple plot1_paper_nBJ.z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
Definition at line 28 of file plot1_paper_nBJ.py.
z_bs
float plot1_paper_nBJ.z_bs = 0.2+Rbs*np.sin(theta)
Definition at line 51 of file plot1_paper_nBJ.py.
z_mp
float plot1_paper_nBJ.z_mp = 0.2+Rmp*np.sin(theta)
Definition at line 48 of file plot1_paper_nBJ.py.
zc
plot1_paper_nBJ.zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
Definition at line 31 of file plot1_paper_nBJ.py.
zlim
list plot1_paper_nBJ.zlim = [-4.1,4.1]
Definition at line 16 of file plot1_paper_nBJ.py.
zz_bs
plot1_paper_nBJ.zz_bs = z_bs[inside_bs]
Definition at line 59 of file plot1_paper_nBJ.py.
zz_mp
plot1_paper_nBJ.zz_mp = z_mp[inside_mp]
Definition at line 56 of file plot1_paper_nBJ.py.