iPIC3DxPEACE: plot4_Blines Namespace Reference
plot4_Blines Namespace Reference
Functions
def integrator (r, ds)
Variables
data_address = sys.argv[1]
int cycle = 6500
float radius = 5.5*1.1
int Npoints = 6
float ds = 0.02
int Nmax = 200
int conv_B = 20./0.00562
from_VTK = fb.from_VTK(data_address)
silent
x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
xc = from_VTK.meta['xc']
yc = from_VTK.meta['yc']
zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
dx = from_VTK.meta['dx']
dy = from_VTK.meta['dy']
dz = from_VTK.meta['dz']
Bx
By
Bz
fibo_obj
None
tar_var
fx = RegularGridInterpolator((x,y,z), Bx)
fy = RegularGridInterpolator((x,y,z), By)
fz = RegularGridInterpolator((x,y,z), Bz)
colors = pl.cm.jet(np.linspace(0,1,Npoints))
list line1 = []
list line2 = []
fontsize
int theta_lim = np.arcsin(np.sqrt(Bline1[ip,0,0]/np.max(Bline1[ip,:ibreak1[ip,0],1])))*180./3.14
label
color
leg1 = pl.legend(handles=line1,loc='lower left',fontsize=12)
leg2 = pl.legend(handles=line2,loc='lower right',fontsize=12)
handles
loc
wspace
format
Function Documentation
integrator()
def plot4_Blines.integrator (r, ds)
Definition at line 47 of file plot4_Blines.py.
def integrator(r,ds):
    # void fields to be filled
    Bline = np.ones((Npoints,Nmax,2))
    traj = np.ones((3,Npoints,Nmax,2))
    ibreak = np.ones((Npoints,2),dtype=int)*Nmax
    # loop on points (along phi)
    for ip in range(0,Npoints):
        phi=float(ip)/float(Npoints)*2.*np.pi
        print('point phi=%.3f'%phi)
        x00 = xc+r*np.cos(phi)
        y00 = yc+r*np.sin(phi)
        z00 = zc-from_VTK.meta['Doff']
        # two loops forward and backward
        for il in range(2):
            # integrator field-line
            for n in range(0,Nmax):
                if n==0:
                    x0=x00
                    y0=y00
                    z0=z00
                point = np.array([[x0,y0,z0],[0,0,0]])
                Bxval = fx(point)[0]
                Byval = fy(point)[0]
                Bzval = fz(point)[0]
                Bval = np.sqrt(Bxval**2+Byval**2+Bzval**2)
                Bline[ip,n,il]=(conv_B*Bval)
                traj[0][ip,n,il]=x0
                traj[1][ip,n,il]=y0
                traj[2][ip,n,il]=z0
                x0 += Bxval/Bval*ds
                y0 += Byval/Bval*ds
                z0 += Bzval/Bval*ds
                if np.sqrt((x0-xc)**2+(y0-yc)**2+(z0-zc)**2)<from_VTK.meta['R']:
                    ibreak[ip,il]=n
                    break
            ds=-ds
    return Bline, traj, ibreak
Bline1,traj1,ibreak1 = integrator(radius,ds)
Bline2,traj2,ibreak2 = integrator(radius+0.2,ds)
Bline3,traj3,ibreak3 = integrator(radius+0.4,ds)
'''
fig = plt.figure(1)
ax = Axes3D(fig)
for ip in range(Npoints):
    ax.plot(traj[0][ip,:ibreak[ip,0],0],traj[1][ip,:ibreak[ip,0],0],traj[2][ip,:ibreak[ip,0],0],color='red')
    ax.plot(traj[0][ip,:ibreak[ip,1],1],traj[1][ip,:ibreak[ip,1],1],traj[2][ip,:ibreak[ip,1],1],color='blue')
ax.set_xlabel('x[di]',fontsize=16)
ax.set_ylabel('y[di]',fontsize=16)
ax.set_zlabel('z[di]',fontsize=16)
plt.xlim(xc-10,xc+10)
plt.ylim(yc-10,yc+10)
ax.set_zlim(zc-10,zc+10)
plt.savefig('./images/plot4_paper_3D-Blines_1_%i.png'%cycle,format='png')
plt.close()
'''
pl.figure(figsize=(15,6))
References fx, fy, fz, integrator(), and plot2_paper_df.range.
Referenced by integrator().
Variable Documentation
Bx
plot4_Blines.Bx
Definition at line 39 of file plot4_Blines.py.
Referenced by loopX(), loopY(), and loopZ().
By
plot4_Blines.By
Definition at line 39 of file plot4_Blines.py.
Referenced by loopX(), loopY(), and loopZ().
Bz
plot4_Blines.Bz
Definition at line 39 of file plot4_Blines.py.
Referenced by loopX(), loopY(), and loopZ().
color
plot4_Blines.color
Definition at line 128 of file plot4_Blines.py.
colors
plot4_Blines.colors = pl.cm.jet(np.linspace(0,1,Npoints))
Definition at line 120 of file plot4_Blines.py.
conv_B
int plot4_Blines.conv_B = 20./0.00562
Definition at line 23 of file plot4_Blines.py.
cycle
plot4_Blines.cycle = 6500
Definition at line 16 of file plot4_Blines.py.
data_address
plot4_Blines.data_address = sys.argv[1]
Definition at line 15 of file plot4_Blines.py.
ds
float plot4_Blines.ds = 0.02
Definition at line 19 of file plot4_Blines.py.
dx
plot4_Blines.dx = from_VTK.meta['dx']
Definition at line 34 of file plot4_Blines.py.
dy
plot4_Blines.dy = from_VTK.meta['dy']
Definition at line 35 of file plot4_Blines.py.
dz
plot4_Blines.dz = from_VTK.meta['dz']
Definition at line 36 of file plot4_Blines.py.
fibo_obj
plot4_Blines.fibo_obj
Definition at line 39 of file plot4_Blines.py.
fontsize
plot4_Blines.fontsize
Definition at line 125 of file plot4_Blines.py.
format
plot4_Blines.format
Definition at line 200 of file plot4_Blines.py.
from_VTK
plot4_Blines.from_VTK = fb.from_VTK(data_address)
Definition at line 26 of file plot4_Blines.py.
fx
plot4_Blines.fx = RegularGridInterpolator((x,y,z), Bx)
Definition at line 42 of file plot4_Blines.py.
Referenced by integrator().
fy
plot4_Blines.fy = RegularGridInterpolator((x,y,z), By)
Definition at line 43 of file plot4_Blines.py.
Referenced by integrator().
fz
plot4_Blines.fz = RegularGridInterpolator((x,y,z), Bz)
Definition at line 44 of file plot4_Blines.py.
Referenced by integrator().
handles
plot4_Blines.handles
Definition at line 159 of file plot4_Blines.py.
label
plot4_Blines.label
Definition at line 128 of file plot4_Blines.py.
leg1
plot4_Blines.leg1 = pl.legend(handles=line1,loc='lower left',fontsize=12)
Definition at line 131 of file plot4_Blines.py.
leg2
plot4_Blines.leg2 = pl.legend(handles=line2,loc='lower right',fontsize=12)
Definition at line 138 of file plot4_Blines.py.
line1
list plot4_Blines.line1 = []
Definition at line 123 of file plot4_Blines.py.
line2
list plot4_Blines.line2 = []
Definition at line 124 of file plot4_Blines.py.
loc
plot4_Blines.loc
Definition at line 159 of file plot4_Blines.py.
Nmax
int plot4_Blines.Nmax = 200
Definition at line 20 of file plot4_Blines.py.
None
plot4_Blines.None
Definition at line 39 of file plot4_Blines.py.
Npoints
int plot4_Blines.Npoints = 6
Definition at line 18 of file plot4_Blines.py.
radius
float plot4_Blines.radius = 5.5*1.1
Definition at line 17 of file plot4_Blines.py.
Referenced by EMfields3D.initBEAM().
silent
plot4_Blines.silent
Definition at line 27 of file plot4_Blines.py.
tar_var
plot4_Blines.tar_var
Definition at line 39 of file plot4_Blines.py.
theta_lim
int plot4_Blines.theta_lim = np.arcsin(np.sqrt(Bline1[ip,0,0]/np.max(Bline1[ip,:ibreak1[ip,0],1])))*180./3.14
Definition at line 127 of file plot4_Blines.py.
wspace
plot4_Blines.wspace
Definition at line 199 of file plot4_Blines.py.
x
plot4_Blines.x = np.linspace(0,from_VTK.meta['xl'],from_VTK.meta['nx'])
Definition at line 28 of file plot4_Blines.py.
xc
plot4_Blines.xc = from_VTK.meta['xc']
Definition at line 31 of file plot4_Blines.py.
y
plot4_Blines.y = np.linspace(0,from_VTK.meta['yl'],from_VTK.meta['ny'])
Definition at line 29 of file plot4_Blines.py.
yc
plot4_Blines.yc = from_VTK.meta['yc']
Definition at line 32 of file plot4_Blines.py.
z
plot4_Blines.z = np.linspace(0,from_VTK.meta['zl'],from_VTK.meta['nz'])
Definition at line 30 of file plot4_Blines.py.
zc
plot4_Blines.zc = from_VTK.meta['zc']+from_VTK.meta['Doff']
Definition at line 33 of file plot4_Blines.py.