iPIC3DxPEACE: Grid3DCU Class Reference
Grid3DCU Class Reference
Uniform cartesian local grid 3D.
#include <Grid3DCU.h>
Public Member Functions
Grid3DCU (CollectiveIO *col, VirtualTopology3D *vct)
constructor
Grid3DCU (int nxc_, int nyc_, int nzc_, double dx_, double dy_, double dz_, double xStart_, double yStart_, double zStart_)
~Grid3DCU ()
destructor
void print () const
allocate grid arrays for this domain
void gradC2N (arr3_double gradXN, arr3_double gradYN, arr3_double gradZN, const_arr3_double scFieldC) const
calculate a derivative along a direction on nodes
void gradN2C (arr3_double gradXC, arr3_double gradYC, arr3_double gradZC, const_arr3_double scFieldN) const
calculate gradient on nodes, given a scalar field defined on central points
void divN2C (arr3_double divC, const_arr3_double vecFieldXN, const_arr3_double vecFieldYN, const_arr3_double vecFieldZN) const
calculate divergence on central points, given a vector field defined on nodes
void divC2N (arr3_double divN, const_arr3_double vecFieldXC, const_arr3_double vecFieldYC, const_arr3_double vecFieldZC) const
calculate divergence on nodes, given a vector field defined on central points
void curlC2N (arr3_double curlXN, arr3_double curlYN, arr3_double curlZN, const_arr3_double vecFieldXC, const_arr3_double vecFieldYC, const_arr3_double vecFieldZC) const
calculate curl on nodes, given a vector field defined on central points
void curlN2C (arr3_double curlXC, arr3_double curlYC, arr3_double curlZC, const_arr3_double vecFieldXN, const_arr3_double vecFieldYN, const_arr3_double vecFieldZN) const
calculate curl on central points, given a vector field defined on nodes
void divSymmTensorN2C (arr3_double divCX, arr3_double divCY, arr3_double divCZ, const_arr4_double pXX, const_arr4_double pXY, const_arr4_double pXZ, const_arr4_double pYY, const_arr4_double pYZ, const_arr4_double pZZ, int ns) const
calculate divergence on central points, given a Tensor field defined on nodes
void lapN2N (arr3_double lapN, const_arr3_double scFieldN, EMfields3D *EMf) const
calculate laplacian on nodes, given a scalar field defined on nodes
void lapC2Cpoisson (arr3_double lapC, arr3_double scFieldC, EMfields3D *EMf) const
calculate laplacian on central points, given a scalar field defined on central points for Poisson
void lapC2C (arr3_double lapC, const_arr3_double scFieldC) const
calculate laplacian on central points, given a scalar field defined on central points
void divBCleft (arr3_double divBC, const_arr3_double vectorX, const_arr3_double vectorY, const_arr3_double vectorZ, int leftActiveNode, int dirDER) const
calculate divergence on boundaries
void divBCright (arr3_double divBC, const_arr3_double vectorX, const_arr3_double vectorY, const_arr3_double vectorZ, int rightActiveNode, int dirDER) const
calculate divergence on boundaries
void derBC (arr3_double derBC, const_arr3_double vector, int leftActiveNode, int dirDER) const
calculate derivative on boundaries
void interpC2N (arr3_double vecFieldN, const_arr3_double vecFieldC) const
interpolate on nodes from central points
void interpN2C (arr3_double vecFieldC, const_arr3_double vecFieldN) const
interpolate on central points from nodes
void interpN2C (arr4_double vecFieldC, int ns, const_arr4_double vecFieldN) const
interpolate on central points from nodes
const VirtualTopology3D & get_vct () const
int getNXC () const
int getNXN () const
int getNYC () const
int getNYN () const
int getNZC () const
int getNZN () const
int get_nxc_r () const
int get_nyc_r () const
int get_nzc_r () const
int get_num_cells_rr () const
double getDX () const
double getDY () const
double getDZ () const
double get_invdx () const
double get_invdy () const
double get_invdz () const
double calcXN (int X) const
double calcYN (int Y) const
double calcZN (int Z) const
const double & getXN (int X) const
const double & getYN (int Y) const
const double & getZN (int Z) const
const double & getXC (int X) const
const double & getYC (int Y) const
const double & getZC (int Z) const
const double & getXN (int X, int Y, int Z) const
const double & getYN (int X, int Y, int Z) const
const double & getZN (int X, int Y, int Z) const
const double & getXC (int X, int Y, int Z) const
const double & getYC (int X, int Y, int Z) const
const double & getZC (int X, int Y, int Z) const
double getXstart () const
double getXend () const
double getYstart () const
double getYend () const
double getZstart () const
double getZend () const
double getVOL () const
double getInvVOL () const
void get_cell_coordinates (int &cx, int &cy, int &cz, double xpos, double ypos, double zpos) const
void make_grid_position_safe (double &cx_pos, double &cy_pos, double &cz_pos) const
void assert_cell_coordinates_safe (int cx, int cy, int cz) const
void make_cell_coordinates_safe (int &cx, int &cy, int &cz) const
void get_safe_cell_coordinates (int &cx, int &cy, int &cz, double x, double y, double z) const
void get_safe_cell_and_weights (double xpos, double ypos, double zpos, int &cx, int &cy, int &cz, double weights[8]) const
void get_safe_cell_and_weights (double xpos[3], int cx[3], double weights[8]) const
Static Public Member Functions
static void get_weights (double weights[8], double w0x, double w0y, double w0z, double w1x, double w1y, double w1z)
Private Member Functions
void init_derived_parameters ()
Private Attributes
const VirtualTopology3D & _vct
int nxc
number of cells - X direction, including + 2 (guard cells)
int nxn
number of nodes - X direction, including + 2 extra nodes for guard cells
int nyc
number of cell - Y direction, including + 2 (guard cells)
int nyn
number of nodes - Y direction, including + 2 extra nodes for guard cells
int nzc
number of cell - Z direction, including + 2 (guard cells)
int nzn
number of nodes - Z direction, including + 2 extra nodes for guard cells
double dx
dx = space step - X direction
double dy
dy = space step - Y direction
double dz
dz = space step - Z direction
double invdx
invdx = 1/dx
double invdy
invdy = 1/dy
double invdz
invdz = 1/dz
double VOL
volume of mesh cell
double invVOL
invol = inverse of volume
int cxlast
index of last cell including ghost cells
int cylast
int czlast
int nxc_r
int nyc_r
int nzc_r
int num_cells_rr
pfloat * pfloat_node_xcoord
node coordinate
pfloat * pfloat_node_ycoord
pfloat * pfloat_node_zcoord
double * node_xcoord
double * node_ycoord
double * node_zcoord
double * center_xcoord
center coordinate
double * center_ycoord
double * center_zcoord
double xStart
local grid boundaries coordinate of proper subdomain
double xEnd
double yStart
double yEnd
double zStart
double zEnd
double xStart_g
double yStart_g
double zStart_g
double epsilon
double nxc_minus_epsilon
double nyc_minus_epsilon
double nzc_minus_epsilon
Static Private Attributes
static const bool suppress_runaway_particle_instability = true
Detailed Description
Uniform cartesian local grid 3D.
Date
Fri Jun 4 2008
Copyright:
Author
Stefano Markidis, Giovanni Lapenta
Version
3.0
Definition at line 44 of file Grid3DCU.h.
Member Function Documentation
assert_cell_coordinates_safe()
void Grid3DCU::assert_cell_coordinates_safe (int cx, int cy, int cz) const inline
Definition at line 390 of file Grid3DCU.h.
  {
    assert(cx >= 0);
    assert(cy >= 0);
    assert(cz >= 0);
    assert(cx < nxc);
    assert(cy < nyc);
    assert(cz < nzc);
  }
calcXN()
double Grid3DCU::calcXN (int X) const inline
Definition at line 296 of file Grid3DCU.h.
{ return xStart+(X-1)*dx;}
calcYN()
double Grid3DCU::calcYN (int Y) const inline
Definition at line 297 of file Grid3DCU.h.
{ return yStart+(Y-1)*dy;}
calcZN()
double Grid3DCU::calcZN (int Z) const inline
Definition at line 298 of file Grid3DCU.h.
{ return zStart+(Z-1)*dz;}
get_cell_coordinates()
void Grid3DCU::get_cell_coordinates (int & cx, int & cy, int & cz, double xpos, double ypos, double zpos) const inline
Definition at line 362 of file Grid3DCU.h.
  {
      // xStart marks start of domain excluding ghosts
      const double rel_xpos = xpos - xStart;
      const double rel_ypos = ypos - yStart;
      const double rel_zpos = zpos - zStart;
      // cell position minus 1 (due to ghost cells)
      const double cxm1_pos = rel_xpos * invdx;
      const double cym1_pos = rel_ypos * invdy;
      const double czm1_pos = rel_zpos * invdz;
      cx = 1 + int(floor(cxm1_pos));
      cy = 1 + int(floor(cym1_pos));
      cz = 1 + int(floor(czm1_pos));
  }
get_invdx()
double Grid3DCU::get_invdx () const inline
Definition at line 289 of file Grid3DCU.h.
{ return (invdx); }
get_invdy()
double Grid3DCU::get_invdy () const inline
Definition at line 290 of file Grid3DCU.h.
{ return (invdy); }
get_invdz()
double Grid3DCU::get_invdz () const inline
Definition at line 291 of file Grid3DCU.h.
{ return (invdz); }
get_num_cells_rr()
int Grid3DCU::get_num_cells_rr () const inline
Definition at line 285 of file Grid3DCU.h.
{return num_cells_rr;}
get_nxc_r()
int Grid3DCU::get_nxc_r () const inline
Definition at line 282 of file Grid3DCU.h.
{return nxc_r;}
get_nyc_r()
int Grid3DCU::get_nyc_r () const inline
Definition at line 283 of file Grid3DCU.h.
{return nyc_r;}
get_nzc_r()
int Grid3DCU::get_nzc_r () const inline
Definition at line 284 of file Grid3DCU.h.
{return nzc_r;}
get_safe_cell_and_weights() [1/2]
void Grid3DCU::get_safe_cell_and_weights (double xpos, double ypos, double zpos, int & cx, int & cy, int & cz, double weights[8]) const inline
Definition at line 418 of file Grid3DCU.h.
  {
    //convert_xpos_to_cxpos(xpos,ypos,zpos,cx_pos,cy_pos,cz_pos);
    // gxStart marks start of guarded domain (including ghosts)
    const double rel_xpos = xpos - xStart_g;
    const double rel_ypos = ypos - yStart_g;
    const double rel_zpos = zpos - zStart_g;
    // cell position (in guarded array)
    double cx_pos = rel_xpos * invdx;
    double cy_pos = rel_ypos * invdy;
    double cz_pos = rel_zpos * invdz;
    //
    if(suppress_runaway_particle_instability)
      make_grid_position_safe(cx_pos,cy_pos,cz_pos);
    //
    cx = int(floor(cx_pos));
    cy = int(floor(cy_pos));
    cz = int(floor(cz_pos));
    // this was the old algorithm.
    if(!suppress_runaway_particle_instability)
      make_cell_coordinates_safe(cx,cy,cz);
    assert_cell_coordinates_safe(cx,cy,cz);
    // fraction of distance from the left
    const double w0x = cx_pos - cx;
    const double w0y = cy_pos - cy;
    const double w0z = cz_pos - cz;
    // fraction of the distance from the right of the cell
    const double w1x = 1.-w0x;
    const double w1y = 1.-w0y;
    const double w1z = 1.-w0z;
    get_weights(weights, w0x, w0y, w0z, w1x, w1y, w1z);
  }
get_safe_cell_and_weights() [2/2]
void Grid3DCU::get_safe_cell_and_weights (double xpos[3], int cx[3], double weights[8]) const inline
Definition at line 455 of file Grid3DCU.h.
  {
    get_safe_cell_and_weights(xpos[0],xpos[1],xpos[2],cx[0],cx[1],cx[2],weights);
  }
get_safe_cell_coordinates()
void Grid3DCU::get_safe_cell_coordinates (int & cx, int & cy, int & cz, double x, double y, double z) const inline
Definition at line 411 of file Grid3DCU.h.
  {
    get_cell_coordinates(cx,cy,cz,x,y,z);
    make_cell_coordinates_safe(cx,cy,cz);
  }
get_vct()
const VirtualTopology3D & Grid3DCU::get_vct () const inline
Definition at line 275 of file Grid3DCU.h.
{return _vct;}
get_weights()
static void Grid3DCU::get_weights (double weights[8], double w0x, double w0y, double w0z, double w1x, double w1y, double w1z) inline static
Definition at line 330 of file Grid3DCU.h.
  {
    // which of the following is faster?
    //
    // this:
    //
    //const double weight00 = w0x*w0y;
    //const double weight01 = w0x*w1y;
    //const double weight10 = w1x*w0y;
    //const double weight11 = w1x*w1y;
    //weights[0] = weight00*w0z; // weight000
    //weights[1] = weight00*w1z; // weight001
    //weights[2] = weight01*w0z; // weight010
    //weights[3] = weight01*w1z; // weight011
    //weights[4] = weight10*w0z; // weight100
    //weights[5] = weight10*w1z; // weight101
    //weights[6] = weight11*w0z; // weight110
    //weights[7] = weight11*w1z; // weight111
    //
    // or this:
    //
    weights[0] = w0x*w0y*w0z; // weight000
    weights[1] = w0x*w0y*w1z; // weight001
    weights[2] = w0x*w1y*w0z; // weight010
    weights[3] = w0x*w1y*w1z; // weight011
    weights[4] = w1x*w0y*w0z; // weight100
    weights[5] = w1x*w0y*w1z; // weight101
    weights[6] = w1x*w1y*w0z; // weight110
    weights[7] = w1x*w1y*w1z; // weight111
  }
getDX()
double Grid3DCU::getDX () const inline
Definition at line 286 of file Grid3DCU.h.
{ return (dx); }
getDY()
double Grid3DCU::getDY () const inline
Definition at line 287 of file Grid3DCU.h.
{ return (dy); }
getDZ()
double Grid3DCU::getDZ () const inline
Definition at line 288 of file Grid3DCU.h.
{ return (dz); }
getInvVOL()
double Grid3DCU::getInvVOL () const inline
Definition at line 327 of file Grid3DCU.h.
{ return (invVOL); }
getNXC()
int Grid3DCU::getNXC () const inline
Definition at line 276 of file Grid3DCU.h.
{ return (nxc); }
getNXN()
int Grid3DCU::getNXN () const inline
Definition at line 277 of file Grid3DCU.h.
{ return (nxn); }
getNYC()
int Grid3DCU::getNYC () const inline
Definition at line 278 of file Grid3DCU.h.
{ return (nyc); }
getNYN()
int Grid3DCU::getNYN () const inline
Definition at line 279 of file Grid3DCU.h.
{ return (nyn); }
getNZC()
int Grid3DCU::getNZC () const inline
Definition at line 280 of file Grid3DCU.h.
{ return (nzc); }
getNZN()
int Grid3DCU::getNZN () const inline
Definition at line 281 of file Grid3DCU.h.
{ return (nzn); }
getVOL()
double Grid3DCU::getVOL () const inline
Definition at line 326 of file Grid3DCU.h.
{ return (VOL); }
getXC() [1/2]
const double & Grid3DCU::getXC (int X) const inline
Definition at line 305 of file Grid3DCU.h.
{ return center_xcoord[X];}
getXC() [2/2]
const double & Grid3DCU::getXC (int X, int Y, int Z) const inline
Definition at line 316 of file Grid3DCU.h.
{ return center_xcoord[X];}
getXend()
double Grid3DCU::getXend () const inline
Definition at line 321 of file Grid3DCU.h.
{ return (xEnd); }
getXN() [1/2]
const double & Grid3DCU::getXN (int X) const inline
Definition at line 302 of file Grid3DCU.h.
{ return node_xcoord[X];}
getXN() [2/2]
const double & Grid3DCU::getXN (int X, int Y, int Z) const inline
Definition at line 313 of file Grid3DCU.h.
{ return node_xcoord[X];}
getXstart()
double Grid3DCU::getXstart () const inline
Definition at line 320 of file Grid3DCU.h.
{ return (xStart); }
getYC() [1/2]
const double & Grid3DCU::getYC (int X, int Y, int Z) const inline
Definition at line 317 of file Grid3DCU.h.
{ return center_ycoord[Y];}
getYC() [2/2]
const double & Grid3DCU::getYC (int Y) const inline
Definition at line 306 of file Grid3DCU.h.
{ return center_ycoord[Y];}
getYend()
double Grid3DCU::getYend () const inline
Definition at line 323 of file Grid3DCU.h.
{ return (yEnd); }
getYN() [1/2]
const double & Grid3DCU::getYN (int X, int Y, int Z) const inline
Definition at line 314 of file Grid3DCU.h.
{ return node_ycoord[Y];}
getYN() [2/2]
const double & Grid3DCU::getYN (int Y) const inline
Definition at line 303 of file Grid3DCU.h.
{ return node_ycoord[Y];}
getYstart()
double Grid3DCU::getYstart () const inline
Definition at line 322 of file Grid3DCU.h.
{ return (yStart); }
getZC() [1/2]
const double & Grid3DCU::getZC (int X, int Y, int Z) const inline
Definition at line 318 of file Grid3DCU.h.
{ return center_zcoord[Z];}
getZC() [2/2]
const double & Grid3DCU::getZC (int Z) const inline
Definition at line 307 of file Grid3DCU.h.
{ return center_zcoord[Z];}
getZend()
double Grid3DCU::getZend () const inline
Definition at line 325 of file Grid3DCU.h.
{ return (zEnd); }
getZN() [1/2]
const double & Grid3DCU::getZN (int X, int Y, int Z) const inline
Definition at line 315 of file Grid3DCU.h.
{ return node_zcoord[Z];}
getZN() [2/2]
const double & Grid3DCU::getZN (int Z) const inline
Definition at line 304 of file Grid3DCU.h.
{ return node_zcoord[Z];}
getZstart()
double Grid3DCU::getZstart () const inline
Definition at line 324 of file Grid3DCU.h.
{ return (zStart); }
gradC2N()
void Grid3DCU::gradC2N (arr3_double gradXN, arr3_double gradYN, arr3_double gradZN, const_arr3_double scFieldC) const
calculate a derivative along a direction on nodes
calculate gradient on nodes, given a scalar field defined on central points
Referenced by EMfields3D::calculateB(), EMfields3D::calculateE(), EMfields3D::MaxwellImage(), and EMfields3D::MaxwellSource().
make_cell_coordinates_safe()
void Grid3DCU::make_cell_coordinates_safe (int & cx, int & cy, int & cz) const inline
Definition at line 399 of file Grid3DCU.h.
  {
    // if the cell is outside the domain, then treat it as
    // in the nearest ghost cell.
    //
    if (cx < 0) cx = 0;
    if (cy < 0) cy = 0;
    if (cz < 0) cz = 0;
    if (cx > cxlast) cx = cxlast; //nxc-1;
    if (cy > cylast) cy = cylast; //nyc-1;
    if (cz > czlast) cz = czlast; //nzc-1;
  }
make_grid_position_safe()
void Grid3DCU::make_grid_position_safe (double & cx_pos, double & cy_pos, double & cz_pos) const inline
Definition at line 378 of file Grid3DCU.h.
  {
    // if the position is outside the domain, then map
    // it to the edge of the guarded subdomain
    //
    if (cx_pos < epsilon) cx_pos = epsilon;
    if (cy_pos < epsilon) cy_pos = epsilon;
    if (cz_pos < epsilon) cz_pos = epsilon;
    if (cx_pos > nxc_minus_epsilon) cx_pos = nxc_minus_epsilon;
    if (cy_pos > nyc_minus_epsilon) cy_pos = nyc_minus_epsilon;
    if (cz_pos > nzc_minus_epsilon) cz_pos = nzc_minus_epsilon;
  }
print()
void Grid3DCU::print () const
allocate grid arrays for this domain
deallocate grid arrays for this domain print grid info
Member Data Documentation
_vct
const VirtualTopology3D& Grid3DCU::_vct private
Definition at line 214 of file Grid3DCU.h.
center_xcoord
double* Grid3DCU::center_xcoord private
center coordinate
Definition at line 263 of file Grid3DCU.h.
center_ycoord
double* Grid3DCU::center_ycoord private
Definition at line 264 of file Grid3DCU.h.
center_zcoord
double* Grid3DCU::center_zcoord private
Definition at line 265 of file Grid3DCU.h.
cxlast
int Grid3DCU::cxlast private
index of last cell including ghost cells
Definition at line 245 of file Grid3DCU.h.
cylast
int Grid3DCU::cylast private
Definition at line 246 of file Grid3DCU.h.
czlast
int Grid3DCU::czlast private
Definition at line 247 of file Grid3DCU.h.
dx
double Grid3DCU::dx private
dx = space step - X direction
Definition at line 228 of file Grid3DCU.h.
dy
double Grid3DCU::dy private
dy = space step - Y direction
Definition at line 230 of file Grid3DCU.h.
dz
double Grid3DCU::dz private
dz = space step - Z direction
Definition at line 232 of file Grid3DCU.h.
epsilon
double Grid3DCU::epsilon private
Definition at line 269 of file Grid3DCU.h.
invdx
double Grid3DCU::invdx private
invdx = 1/dx
Definition at line 234 of file Grid3DCU.h.
invdy
double Grid3DCU::invdy private
invdy = 1/dy
Definition at line 236 of file Grid3DCU.h.
invdz
double Grid3DCU::invdz private
invdz = 1/dz
Definition at line 238 of file Grid3DCU.h.
invVOL
double Grid3DCU::invVOL private
invol = inverse of volume
Definition at line 242 of file Grid3DCU.h.
node_xcoord
double* Grid3DCU::node_xcoord private
Definition at line 259 of file Grid3DCU.h.
node_ycoord
double* Grid3DCU::node_ycoord private
Definition at line 260 of file Grid3DCU.h.
node_zcoord
double* Grid3DCU::node_zcoord private
Definition at line 261 of file Grid3DCU.h.
num_cells_rr
int Grid3DCU::num_cells_rr private
Definition at line 254 of file Grid3DCU.h.
nxc
int Grid3DCU::nxc private
number of cells - X direction, including + 2 (guard cells)
Definition at line 216 of file Grid3DCU.h.
nxc_minus_epsilon
double Grid3DCU::nxc_minus_epsilon private
Definition at line 270 of file Grid3DCU.h.
nxc_r
int Grid3DCU::nxc_r private
Definition at line 250 of file Grid3DCU.h.
nxn
int Grid3DCU::nxn private
number of nodes - X direction, including + 2 extra nodes for guard cells
Definition at line 218 of file Grid3DCU.h.
nyc
int Grid3DCU::nyc private
number of cell - Y direction, including + 2 (guard cells)
Definition at line 220 of file Grid3DCU.h.
nyc_minus_epsilon
double Grid3DCU::nyc_minus_epsilon private
Definition at line 271 of file Grid3DCU.h.
nyc_r
int Grid3DCU::nyc_r private
Definition at line 251 of file Grid3DCU.h.
nyn
int Grid3DCU::nyn private
number of nodes - Y direction, including + 2 extra nodes for guard cells
Definition at line 222 of file Grid3DCU.h.
nzc
int Grid3DCU::nzc private
number of cell - Z direction, including + 2 (guard cells)
Definition at line 224 of file Grid3DCU.h.
nzc_minus_epsilon
double Grid3DCU::nzc_minus_epsilon private
Definition at line 272 of file Grid3DCU.h.
nzc_r
int Grid3DCU::nzc_r private
Definition at line 252 of file Grid3DCU.h.
nzn
int Grid3DCU::nzn private
number of nodes - Z direction, including + 2 extra nodes for guard cells
Definition at line 226 of file Grid3DCU.h.
pfloat_node_xcoord
pfloat* Grid3DCU::pfloat_node_xcoord private
node coordinate
Definition at line 256 of file Grid3DCU.h.
pfloat_node_ycoord
pfloat* Grid3DCU::pfloat_node_ycoord private
Definition at line 257 of file Grid3DCU.h.
pfloat_node_zcoord
pfloat* Grid3DCU::pfloat_node_zcoord private
Definition at line 258 of file Grid3DCU.h.
suppress_runaway_particle_instability
const bool Grid3DCU::suppress_runaway_particle_instability = true static private
Definition at line 213 of file Grid3DCU.h.
VOL
double Grid3DCU::VOL private
volume of mesh cell
Definition at line 240 of file Grid3DCU.h.
xEnd
double Grid3DCU::xEnd private
Definition at line 267 of file Grid3DCU.h.
xStart
double Grid3DCU::xStart private
local grid boundaries coordinate of proper subdomain
Definition at line 267 of file Grid3DCU.h.
xStart_g
double Grid3DCU::xStart_g private
Definition at line 268 of file Grid3DCU.h.
yEnd
double Grid3DCU::yEnd private
Definition at line 267 of file Grid3DCU.h.
yStart
double Grid3DCU::yStart private
Definition at line 267 of file Grid3DCU.h.
yStart_g
double Grid3DCU::yStart_g private
Definition at line 268 of file Grid3DCU.h.
zEnd
double Grid3DCU::zEnd private
Definition at line 267 of file Grid3DCU.h.
zStart
double Grid3DCU::zStart private
Definition at line 267 of file Grid3DCU.h.
zStart_g
double Grid3DCU::zStart_g private
Definition at line 268 of file Grid3DCU.h.
The documentation for this class was generated from the following file:
include/Grid3DCU.h