iPIC3DxPEACE: post-process/post-process/fields/EMfields3D.cpp File Reference
EMfields3D.cpp File Reference
#include <mpi.h>
#include "ipichdf5.h"
#include "EMfields3D.h"
#include "Collective.h"
#include "Basic.h"
#include "Com3DNonblk.h"
#include "VCtopology3D.h"
#include "Grid3DCU.h"
#include "CG.h"
#include "GMRES.h"
#include "Particles3Dcomm.h"
#include "Moments.h"
#include "Parameters.h"
#include "ompdefs.h"
#include "debug.h"
#include "string.h"
#include "mic_particles.h"
#include "TimeTasks.h"
#include "ipicmath.h"
#include "Alloc.h"
#include "asserts.h"
#include <iostream>
Functions
void compute_moments (double velmoments[10], double weights[8], int i, double const *const x, double const *const y, double const *const z, double const *const u, double const *const v, double const *const w, double const *const q, double xstart, double ystart, double zstart, double inv_dx, double inv_dy, double inv_dz, int cx, int cy, int cz)
void add_moments_for_pcl (double momentsAcc[8][10], int i, double const *const x, double const *const y, double const *const z, double const *const u, double const *const v, double const *const w, double const *const q, double xstart, double ystart, double zstart, double inv_dx, double inv_dy, double inv_dz, int cx, int cy, int cz)
void add_moments_for_pcl_vec (double momentsAccVec[8][10][8], double velmoments[10][8], double weights[8][8], int i, int imod, double const *const x, double const *const y, double const *const z, double const *const u, double const *const v, double const *const w, double const *const q, double xstart, double ystart, double zstart, double inv_dx, double inv_dy, double inv_dz, int cx, int cy, int cz)
void solver2phys (arr3_double vectPhys, double *vectSolver, int nx, int ny, int nz)
method to convert a 1D field in a 3D field not considering guard cells
void solver2phys (arr3_double vectPhys1, arr3_double vectPhys2, arr3_double vectPhys3, double *vectSolver, int nx, int ny, int nz)
method to convert a 1D field in a 3D field not considering guard cells
void phys2solver (double *vectSolver, const arr3_double vectPhys, int nx, int ny, int nz)
method to convert a 3D field in a 1D field not considering guard cells
void phys2solver (double *vectSolver, const arr3_double vectPhys1, const arr3_double vectPhys2, const arr3_double vectPhys3, int nx, int ny, int nz)
method to convert a 3D field in a 1D field not considering guard cells
Function Documentation
add_moments_for_pcl()
void add_moments_for_pcl (double momentsAcc[8][10], int i, double const *const x, double const *const y, double const *const z, double const *const u, double const *const v, double const *const w, double const *const q, double xstart, double ystart, double zstart, double inv_dx, double inv_dy, double inv_dz, int cx, int cy, int cz) inline
Definition at line 1524 of file EMfields3D.cpp.
{
  double velmoments[10];
  double weights[8];
  compute_moments(velmoments,weights,
    i, x, y, z, u, v, w, q,
    xstart, ystart, zstart,
    inv_dx, inv_dy, inv_dz,
    cx, cy, cz);
  // add moments for this particle
  {
    // which is the superior order for the following loop?
    for(int c=0; c<8; c++)
    for(int m=0; m<10; m++)
    {
      momentsAcc[c][m] += velmoments[m]*weights[c];
    }
  }
}
References plot2_paper_df::c, compute_moments(), test_new-features::i, plot1_paper-2_precipitation::q, plot1_paper-2_precipitation::u, plot1_paper-2_precipitation::v, plot1_paper-2_precipitation::w, plot_Jpar-planet::x, plot_Jpar-planet::y, and plot_Jpar-planet::z.
add_moments_for_pcl_vec()
void add_moments_for_pcl_vec (double momentsAccVec[8][10][8], double velmoments[10][8], double weights[8][8], int i, int imod, double const *const x, double const *const y, double const *const z, double const *const u, double const *const v, double const *const w, double const *const q, double xstart, double ystart, double zstart, double inv_dx, double inv_dy, double inv_dz, int cx, int cy, int cz) inline
Definition at line 1565 of file EMfields3D.cpp.
{
  ALIGNED(x);
  ALIGNED(y);
  ALIGNED(z);
  ALIGNED(u);
  ALIGNED(v);
  ALIGNED(w);
  ALIGNED(q);
  // compute the quadratic moments of velocity
  //
  const double ui=u[i];
  const double vi=v[i];
  const double wi=w[i];
  const double uui=ui*ui;
  const double uvi=ui*vi;
  const double uwi=ui*wi;
  const double vvi=vi*vi;
  const double vwi=vi*wi;
  const double wwi=wi*wi;
  //double velmoments[10];
  velmoments[0][imod] = 1.;
  velmoments[1][imod] = ui;
  velmoments[2][imod] = vi;
  velmoments[3][imod] = wi;
  velmoments[4][imod] = uui;
  velmoments[5][imod] = uvi;
  velmoments[6][imod] = uwi;
  velmoments[7][imod] = vvi;
  velmoments[8][imod] = vwi;
  velmoments[9][imod] = wwi;
  // compute the weights to distribute the moments
  //
  //double weights[8];
  const double abs_xpos = x[i];
  const double abs_ypos = y[i];
  const double abs_zpos = z[i];
  const double rel_xpos = abs_xpos - xstart;
  const double rel_ypos = abs_ypos - ystart;
  const double rel_zpos = abs_zpos - zstart;
  const double cxm1_pos = rel_xpos * inv_dx;
  const double cym1_pos = rel_ypos * inv_dy;
  const double czm1_pos = rel_zpos * inv_dz;
  //if(true)
  //{
  //  const int cx_inf = int(floor(cxm1_pos));
  //  const int cy_inf = int(floor(cym1_pos));
  //  const int cz_inf = int(floor(czm1_pos));
  //  assert_eq(cx-1,cx_inf);
  //  assert_eq(cy-1,cy_inf);
  //  assert_eq(cz-1,cz_inf);
  //}
  // fraction of the distance from the right of the cell
  const double w1x = cx - cxm1_pos;
  const double w1y = cy - cym1_pos;
  const double w1z = cz - czm1_pos;
  // fraction of distance from the left
  const double w0x = 1-w1x;
  const double w0y = 1-w1y;
  const double w0z = 1-w1z;
  // we are calculating a charge moment.
  const double qi=q[i];
  const double weight0 = qi*w0x;
  const double weight1 = qi*w1x;
  const double weight00 = weight0*w0y;
  const double weight01 = weight0*w1y;
  const double weight10 = weight1*w0y;
  const double weight11 = weight1*w1y;
  weights[0][imod] = weight00*w0z; // weight000
  weights[1][imod] = weight00*w1z; // weight001
  weights[2][imod] = weight01*w0z; // weight010
  weights[3][imod] = weight01*w1z; // weight011
  weights[4][imod] = weight10*w0z; // weight100
  weights[5][imod] = weight10*w1z; // weight101
  weights[6][imod] = weight11*w0z; // weight110
  weights[7][imod] = weight11*w1z; // weight111
  // add moments for this particle
  {
    for(int c=0; c<8; c++)
    for(int m=0; m<10; m++)
    {
      momentsAccVec[c][m][imod] += velmoments[m][imod]*weights[c][imod];
    }
  }
}
References ALIGNED, plot2_paper_df::c, test_new-features::i, plot1_paper-2_precipitation::q, plot1_paper-2_precipitation::u, plot1_paper-2_precipitation::v, plot1_paper-2_precipitation::w, plot_Jpar-planet::x, plot_Jpar-planet::y, and plot_Jpar-planet::z.
compute_moments()
void compute_moments (double velmoments[10], double weights[8], int i, double const *const x, double const *const y, double const *const z, double const *const u, double const *const v, double const *const w, double const *const q, double xstart, double ystart, double zstart, double inv_dx, double inv_dy, double inv_dz, int cx, int cy, int cz) inline
Definition at line 1427 of file EMfields3D.cpp.
{
  ALIGNED(x);
  ALIGNED(y);
  ALIGNED(z);
  ALIGNED(u);
  ALIGNED(v);
  ALIGNED(w);
  ALIGNED(q);
  // compute the quadratic moments of velocity
  //
  const double ui=u[i];
  const double vi=v[i];
  const double wi=w[i];
  const double uui=ui*ui;
  const double uvi=ui*vi;
  const double uwi=ui*wi;
  const double vvi=vi*vi;
  const double vwi=vi*wi;
  const double wwi=wi*wi;
  //double velmoments[10];
  velmoments[0] = 1.;
  velmoments[1] = ui;
  velmoments[2] = vi;
  velmoments[3] = wi;
  velmoments[4] = uui;
  velmoments[5] = uvi;
  velmoments[6] = uwi;
  velmoments[7] = vvi;
  velmoments[8] = vwi;
  velmoments[9] = wwi;
  // compute the weights to distribute the moments
  //
  //double weights[8];
  const double abs_xpos = x[i];
  const double abs_ypos = y[i];
  const double abs_zpos = z[i];
  const double rel_xpos = abs_xpos - xstart;
  const double rel_ypos = abs_ypos - ystart;
  const double rel_zpos = abs_zpos - zstart;
  const double cxm1_pos = rel_xpos * inv_dx;
  const double cym1_pos = rel_ypos * inv_dy;
  const double czm1_pos = rel_zpos * inv_dz;
  //if(true)
  //{
  //  const int cx_inf = int(floor(cxm1_pos));
  //  const int cy_inf = int(floor(cym1_pos));
  //  const int cz_inf = int(floor(czm1_pos));
  //  assert_eq(cx-1,cx_inf);
  //  assert_eq(cy-1,cy_inf);
  //  assert_eq(cz-1,cz_inf);
  //}
  // fraction of the distance from the right of the cell
  const double w1x = cx - cxm1_pos;
  const double w1y = cy - cym1_pos;
  const double w1z = cz - czm1_pos;
  // fraction of distance from the left
  const double w0x = 1-w1x;
  const double w0y = 1-w1y;
  const double w0z = 1-w1z;
  // we are calculating a charge moment.
  const double qi=q[i];
  const double weight0 = qi*w0x;
  const double weight1 = qi*w1x;
  const double weight00 = weight0*w0y;
  const double weight01 = weight0*w1y;
  const double weight10 = weight1*w0y;
  const double weight11 = weight1*w1y;
  weights[0] = weight00*w0z; // weight000
  weights[1] = weight00*w1z; // weight001
  weights[2] = weight01*w0z; // weight010
  weights[3] = weight01*w1z; // weight011
  weights[4] = weight10*w0z; // weight100
  weights[5] = weight10*w1z; // weight101
  weights[6] = weight11*w0z; // weight110
  weights[7] = weight11*w1z; // weight111
}
References ALIGNED, test_new-features::i, plot1_paper-2_precipitation::q, plot1_paper-2_precipitation::u, plot1_paper-2_precipitation::v, plot1_paper-2_precipitation::w, plot_Jpar-planet::x, plot_Jpar-planet::y, and plot_Jpar-planet::z.
phys2solver() [1/2]
void phys2solver (double * vectSolver, const arr3_double vectPhys, int nx, int ny, int nz)
method to convert a 3D field in a 1D field not considering guard cells
Definition at line 2064 of file EMfields3D.cpp.
{
  for (register int i = 1; i < nx - 1; i++)
    for (register int j = 1; j < ny - 1; j++)
      for (register int k = 1; k < nz - 1; k++)
        *vectSolver++ = vectPhys.get(i,j,k);
}
References iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
phys2solver() [2/2]
void phys2solver (double * vectSolver, const arr3_double vectPhys1, const arr3_double vectPhys2, const arr3_double vectPhys3, int nx, int ny, int nz)
method to convert a 3D field in a 1D field not considering guard cells
Definition at line 2071 of file EMfields3D.cpp.
{
  for (register int i = 1; i < nx - 1; i++)
    for (register int j = 1; j < ny - 1; j++)
      for (register int k = 1; k < nz - 1; k++) {
        *vectSolver++ = vectPhys1.get(i,j,k);
        *vectSolver++ = vectPhys2.get(i,j,k);
        *vectSolver++ = vectPhys3.get(i,j,k);
      }
}
References iPic3D::const_array_ref3< type >::get(), test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
solver2phys() [1/2]
void solver2phys (arr3_double vectPhys, double * vectSolver, int nx, int ny, int nz)
method to convert a 1D field in a 3D field not considering guard cells
Definition at line 2046 of file EMfields3D.cpp.
{
  for (register int i = 1; i < nx - 1; i++)
    for (register int j = 1; j < ny - 1; j++)
      for (register int k = 1; k < nz - 1; k++)
        vectPhys[i][j][k] = *vectSolver++;
}
References test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.
solver2phys() [2/2]
void solver2phys (arr3_double vectPhys1, arr3_double vectPhys2, arr3_double vectPhys3, double * vectSolver, int nx, int ny, int nz)
method to convert a 1D field in a 3D field not considering guard cells
Definition at line 2054 of file EMfields3D.cpp.
{
  for (register int i = 1; i < nx - 1; i++)
    for (register int j = 1; j < ny - 1; j++)
      for (register int k = 1; k < nz - 1; k++) {
        vectPhys1[i][j][k] = *vectSolver++;
        vectPhys2[i][j][k] = *vectSolver++;
        vectPhys3[i][j][k] = *vectSolver++;
      }
}
References test_new-features::i, test_to2D::nx, test_to2D::ny, and test_to2D::nz.